<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Advanced Designs | Introduction to Statistical Modeling</title>
  <meta name="description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Advanced Designs | Introduction to Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  <meta name="github-repo" content="tjfisher19/introStatModeling" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Advanced Designs | Introduction to Statistical Modeling" />
  
  <meta name="twitter:description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  

<meta name="author" content="Michael Hughes and Thomas Fisher" />


<meta name="date" content="2021-12-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-factor-designed-experiments.html"/>
<link rel="next" href="introduction-to-multiple-regression.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Inroduction to Statistical Modeling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html"><i class="fa fa-check"></i>Important Preliminary Review</a>
<ul>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#statistics-background"><i class="fa fa-check"></i>Statistics background</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#software"><i class="fa fa-check"></i>Software</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#add-on-packages"><i class="fa fa-check"></i>Add-on packages</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#help-with-rmarkdown"><i class="fa fa-check"></i>Help with RMarkdown</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#managing-your-work-in-r"><i class="fa fa-check"></i>Managing your work in R</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#data-in-this-text"><i class="fa fa-check"></i>Data in this text</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html"><i class="fa fa-check"></i><b>1</b> Introductory Statistics in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#goals-of-a-statistical-analysis"><i class="fa fa-check"></i><b>1.1</b> Goals of a statistical analysis</a></li>
<li class="chapter" data-level="1.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#before-you-begin-an-analysis"><i class="fa fa-check"></i><b>1.2</b> Before you begin an analysis</a></li>
<li class="chapter" data-level="1.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#data-frames"><i class="fa fa-check"></i><b>1.3</b> Data frames</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#built-in-data"><i class="fa fa-check"></i><b>1.3.1</b> Built-in data</a></li>
<li class="chapter" data-level="1.3.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#types-of-data"><i class="fa fa-check"></i><b>1.3.2</b> Types of Data</a></li>
<li class="chapter" data-level="1.3.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#importing-datasets-into-r"><i class="fa fa-check"></i><b>1.3.3</b> Importing datasets into R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#referencing-data-from-inside-a-data-frame"><i class="fa fa-check"></i><b>1.4</b> Referencing data from inside a data frame</a></li>
<li class="chapter" data-level="1.5" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#missing-values-and-computer-arithmetic-in-r"><i class="fa fa-check"></i><b>1.5</b> Missing values and computer arithmetic in R</a></li>
<li class="chapter" data-level="1.6" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#exploratory-data-analysis-eda"><i class="fa fa-check"></i><b>1.6</b> Exploratory Data Analysis (EDA)</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#numeric-summaries"><i class="fa fa-check"></i><b>1.6.1</b> Numeric Summaries</a></li>
<li class="chapter" data-level="1.6.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#numeric-summaries-in-r"><i class="fa fa-check"></i><b>1.6.2</b> Numeric Summaries in R</a></li>
<li class="chapter" data-level="1.6.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#graphical-summaries"><i class="fa fa-check"></i><b>1.6.3</b> Graphical Summaries</a></li>
<li class="chapter" data-level="1.6.4" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#distribution-of-univariate-variables"><i class="fa fa-check"></i><b>1.6.4</b> Distribution of Univariate Variables</a></li>
<li class="chapter" data-level="1.6.5" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-by-levels-of-a-factor-variable"><i class="fa fa-check"></i><b>1.6.5</b> Descriptive statistics and visualizations by levels of a factor variable</a></li>
<li class="chapter" data-level="1.6.6" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-for-two-numeric-variables"><i class="fa fa-check"></i><b>1.6.6</b> Descriptive statistics and visualizations for two numeric variables</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#sampling-distributions-describing-how-a-statistic-varies"><i class="fa fa-check"></i><b>1.7</b> Sampling distributions: describing how a statistic varies</a></li>
<li class="chapter" data-level="1.8" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#two-sample-inference"><i class="fa fa-check"></i><b>1.8</b> Two-sample inference</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html"><i class="fa fa-check"></i><b>2</b> Introduction to Statistical Modeling and Designed Experiments</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#statistical-analyses-is-modeling"><i class="fa fa-check"></i><b>2.1</b> Statistical Analyses is Modeling</a></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#observational-studies-versus-designed-experiments"><i class="fa fa-check"></i><b>2.2</b> Observational Studies versus designed experiments</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#observational-studies"><i class="fa fa-check"></i><b>2.2.1</b> Observational Studies</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#designed-experiments"><i class="fa fa-check"></i><b>2.2.2</b> Designed experiments</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#designed-experiement-vocabulary"><i class="fa fa-check"></i><b>2.3</b> Designed experiement vocabulary</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#what-is-an-experiment"><i class="fa fa-check"></i><b>2.3.1</b> What is an experiment?</a></li>
<li class="chapter" data-level="2.3.2" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#analysis-of-variance"><i class="fa fa-check"></i><b>2.3.2</b> Analysis of variance</a></li>
<li class="chapter" data-level="2.3.3" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#elements-of-a-designed-experiment"><i class="fa fa-check"></i><b>2.3.3</b> Elements of a designed experiment</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#paired-t-test"><i class="fa fa-check"></i><b>2.4</b> Paired <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="2.5" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#one-way-anova"><i class="fa fa-check"></i><b>2.5</b> One-Way ANOVA</a></li>
<li class="chapter" data-level="2.6" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#assumption-checking"><i class="fa fa-check"></i><b>2.6</b> Assumption Checking</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#independence"><i class="fa fa-check"></i><b>2.6.1</b> Independence</a></li>
<li class="chapter" data-level="2.6.2" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#constant-variance"><i class="fa fa-check"></i><b>2.6.2</b> Constant Variance</a></li>
<li class="chapter" data-level="2.6.3" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#checking-normality"><i class="fa fa-check"></i><b>2.6.3</b> Checking Normality</a></li>
<li class="chapter" data-level="2.6.4" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#code-to-check-assumption"><i class="fa fa-check"></i><b>2.6.4</b> Code to check assumption</a></li>
<li class="chapter" data-level="2.6.5" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#transforming-your-response"><i class="fa fa-check"></i><b>2.6.5</b> Transforming your response</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#follow-up-procedures-multiple-comparisons"><i class="fa fa-check"></i><b>2.7</b> Follow-up procedures – Multiple Comparisons</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#tukeys-hsd-method"><i class="fa fa-check"></i><b>2.7.1</b> Tukey’s HSD method</a></li>
<li class="chapter" data-level="2.7.2" data-path="introduction-to-statistical-modeling-and-designed-experiments.html"><a href="introduction-to-statistical-modeling-and-designed-experiments.html#dunnett-multiple-comparisons"><i class="fa fa-check"></i><b>2.7.2</b> Dunnett multiple comparisons</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html"><i class="fa fa-check"></i><b>3</b> Multiple Factor Designed Experiments</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#blocking"><i class="fa fa-check"></i><b>3.1</b> Blocking</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#data-structure-model-form-and-analysis-of-variance-of-a-randomized-block-design"><i class="fa fa-check"></i><b>3.1.1</b> Data structure, model form and analysis of variance of a Randomized Block Design</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#two-factor-designs"><i class="fa fa-check"></i><b>3.2</b> Two-factor Designs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#analysis"><i class="fa fa-check"></i><b>3.2.1</b> Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="advanced-designs.html"><a href="advanced-designs.html"><i class="fa fa-check"></i><b>4</b> Advanced Designs</a>
<ul>
<li class="chapter" data-level="4.1" data-path="advanced-designs.html"><a href="advanced-designs.html#higher-order-factor-models"><i class="fa fa-check"></i><b>4.1</b> Higher order factor models</a></li>
<li class="chapter" data-level="4.2" data-path="advanced-designs.html"><a href="advanced-designs.html#within-subject-designs"><i class="fa fa-check"></i><b>4.2</b> Within-subject designs</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="advanced-designs.html"><a href="advanced-designs.html#blocks-revisited-an-approach-to-handling-within-subjects-factors"><i class="fa fa-check"></i><b>4.2.1</b> Blocks revisited: an approach to handling within-subjects factors</a></li>
<li class="chapter" data-level="4.2.2" data-path="advanced-designs.html"><a href="advanced-designs.html#a-more-involved-repeated-measures-case-study"><i class="fa fa-check"></i><b>4.2.2</b> A more involved repeated measures case study</a></li>
<li class="chapter" data-level="4.2.3" data-path="advanced-designs.html"><a href="advanced-designs.html#further-study"><i class="fa fa-check"></i><b>4.2.3</b> Further study</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html"><i class="fa fa-check"></i><b>5</b> Introduction to Multiple Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#regression-model"><i class="fa fa-check"></i><b>5.1</b> Regression Model</a></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#fitting-a-regression-model"><i class="fa fa-check"></i><b>5.2</b> Fitting a regression model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#why-should-we-use-more-than-one-predictor"><i class="fa fa-check"></i><b>5.2.1</b> Why should we use more than one predictor?</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#interpreting-beta-parameter-estimates-in-mlr"><i class="fa fa-check"></i><b>5.3</b> Interpreting <span class="math inline">\(\beta\)</span>-parameter estimates in MLR</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#designed-experiments-1"><i class="fa fa-check"></i><b>5.3.1</b> Designed experiments</a></li>
<li class="chapter" data-level="5.3.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#observational-studies-1"><i class="fa fa-check"></i><b>5.3.2</b> Observational studies</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html"><i class="fa fa-check"></i><b>6</b> Inference regarding Multiple Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#assumption-checking-1"><i class="fa fa-check"></i><b>6.1</b> Assumption checking</a></li>
<li class="chapter" data-level="6.2" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#overall-f-test-for-model-signifance"><i class="fa fa-check"></i><b>6.2</b> Overall <span class="math inline">\(F\)</span>-test for model signifance</a></li>
<li class="chapter" data-level="6.3" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#individual-parameter-inference"><i class="fa fa-check"></i><b>6.3</b> Individual parameter inference</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#t-tests"><i class="fa fa-check"></i><b>6.3.1</b> <span class="math inline">\(t\)</span>-tests</a></li>
<li class="chapter" data-level="6.3.2" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#confidence-intervals"><i class="fa fa-check"></i><b>6.3.2</b> Confidence Intervals</a></li>
<li class="chapter" data-level="6.3.3" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#confidence-and-prediction-bands"><i class="fa fa-check"></i><b>6.3.3</b> Confidence and prediction bands</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#goodness-of-fit"><i class="fa fa-check"></i><b>6.4</b> Goodness-of-fit</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#coefficient-of-determination"><i class="fa fa-check"></i><b>6.4.1</b> Coefficient of determination</a></li>
<li class="chapter" data-level="6.4.2" data-path="inference-regarding-multiple-regression.html"><a href="inference-regarding-multiple-regression.html#akaikes-information-criterion"><i class="fa fa-check"></i><b>6.4.2</b> Akaike’s Information Criterion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html"><i class="fa fa-check"></i><b>7</b> More on multiple linear regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#model-comparision-reduced-f-tests"><i class="fa fa-check"></i><b>7.1</b> Model comparision – Reduced <span class="math inline">\(F\)</span>-tests</a></li>
<li class="chapter" data-level="7.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#categorical-predictor-variables"><i class="fa fa-check"></i><b>7.2</b> Categorical Predictor Variables</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#a-qualitative-predictor-with-two-levels"><i class="fa fa-check"></i><b>7.2.1</b> A qualitative predictor with two levels</a></li>
<li class="chapter" data-level="7.2.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#a-qualitative-predictor-with-more-than-two-levels"><i class="fa fa-check"></i><b>7.2.2</b> A qualitative predictor with more than two levels</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#bridging-regression-and-designed-experiments-ancova"><i class="fa fa-check"></i><b>7.3</b> Bridging Regression and Designed Experiments – ANCOVA</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#an-ancova-example-with-a-two-level-factor"><i class="fa fa-check"></i><b>7.3.1</b> An ANCOVA example with a two-level factor</a></li>
<li class="chapter" data-level="7.3.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#ancova-with-a-multi-level-factor"><i class="fa fa-check"></i><b>7.3.2</b> ANCOVA with a multi-level factor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="model-building-considerations.html"><a href="model-building-considerations.html"><i class="fa fa-check"></i><b>8</b> Model Building Considerations</a>
<ul>
<li class="chapter" data-level="8.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#regression-assumptions-revisited"><i class="fa fa-check"></i><b>8.1</b> Regression assumptions revisited</a></li>
<li class="chapter" data-level="8.2" data-path="model-building-considerations.html"><a href="model-building-considerations.html#violations-of-the-independence-assumption"><i class="fa fa-check"></i><b>8.2</b> Violations of the independence assumption</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#collecting-data-that-are-temporal-or-spatial-in-nature"><i class="fa fa-check"></i><b>8.2.1</b> Collecting data that are temporal or spatial in nature</a></li>
<li class="chapter" data-level="8.2.2" data-path="model-building-considerations.html"><a href="model-building-considerations.html#pseudoreplication"><i class="fa fa-check"></i><b>8.2.2</b> Pseudoreplication</a></li>
<li class="chapter" data-level="8.2.3" data-path="model-building-considerations.html"><a href="model-building-considerations.html#what-if-we-have-non-independent-errors"><i class="fa fa-check"></i><b>8.2.3</b> What if we have non-independent errors?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="model-building-considerations.html"><a href="model-building-considerations.html#constant-variance-violations"><i class="fa fa-check"></i><b>8.3</b> Constant Variance Violations</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#box-cox-power-tranformations"><i class="fa fa-check"></i><b>8.3.1</b> Box-Cox Power Tranformations</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="model-building-considerations.html"><a href="model-building-considerations.html#normality-violations"><i class="fa fa-check"></i><b>8.4</b> Normality violations</a></li>
<li class="chapter" data-level="8.5" data-path="model-building-considerations.html"><a href="model-building-considerations.html#violations-of-the-linearity-assumption"><i class="fa fa-check"></i><b>8.5</b> Violations of the linearity assumption</a></li>
<li class="chapter" data-level="8.6" data-path="model-building-considerations.html"><a href="model-building-considerations.html#detecting-and-dealing-with-unusual-observations"><i class="fa fa-check"></i><b>8.6</b> Detecting and dealing with unusual observations</a></li>
<li class="chapter" data-level="8.7" data-path="model-building-considerations.html"><a href="model-building-considerations.html#multicollinearity"><i class="fa fa-check"></i><b>8.7</b> Multicollinearity</a></li>
<li class="chapter" data-level="8.8" data-path="model-building-considerations.html"><a href="model-building-considerations.html#standardizingPredictors"><i class="fa fa-check"></i><b>8.8</b> Scale changes</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>9</b> Model Selection</a>
<ul>
<li class="chapter" data-level="9.1" data-path="model-selection.html"><a href="model-selection.html#stepwise-procedures"><i class="fa fa-check"></i><b>9.1</b> Stepwise Procedures</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="model-selection.html"><a href="model-selection.html#backward-selection"><i class="fa fa-check"></i><b>9.1.1</b> Backward Selection</a></li>
<li class="chapter" data-level="9.1.2" data-path="model-selection.html"><a href="model-selection.html#forward-selection"><i class="fa fa-check"></i><b>9.1.2</b> Forward selection</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="model-selection.html"><a href="model-selection.html#best-subsets"><i class="fa fa-check"></i><b>9.2</b> Best subsets</a></li>
<li class="chapter" data-level="9.3" data-path="model-selection.html"><a href="model-selection.html#shrinkage-methods"><i class="fa fa-check"></i><b>9.3</b> Shrinkage Methods</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="model-validation.html"><a href="model-validation.html"><i class="fa fa-check"></i><b>10</b> Model Validation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="model-validation.html"><a href="model-validation.html#underfitting-vs.-overfitting-models"><i class="fa fa-check"></i><b>10.1</b> Underfitting vs. Overfitting Models</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="model-validation.html"><a href="model-validation.html#the-bias-variance-trade-off"><i class="fa fa-check"></i><b>10.1.1</b> The Bias-Variance Trade-off</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="model-validation.html"><a href="model-validation.html#validation-techniques"><i class="fa fa-check"></i><b>10.2</b> Validation Techniques</a></li>
<li class="chapter" data-level="10.3" data-path="model-validation.html"><a href="model-validation.html#basic-validation-with-a-single-holdout-sample"><i class="fa fa-check"></i><b>10.3</b> Basic Validation with a single holdout sample</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="model-validation.html"><a href="model-validation.html#use-the-training-data-to-fit-and-select-models"><i class="fa fa-check"></i><b>10.3.1</b> Use the training data to fit and select models</a></li>
<li class="chapter" data-level="10.3.2" data-path="model-validation.html"><a href="model-validation.html#model-training"><i class="fa fa-check"></i><b>10.3.2</b> Model training:</a></li>
<li class="chapter" data-level="10.3.3" data-path="model-validation.html"><a href="model-validation.html#model-validation-step"><i class="fa fa-check"></i><b>10.3.3</b> Model validation step:</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="model-validation.html"><a href="model-validation.html#hold-out-sample-validation-using-caret"><i class="fa fa-check"></i><b>10.4</b> Hold-out sample validation using <code>caret</code></a></li>
<li class="chapter" data-level="10.5" data-path="model-validation.html"><a href="model-validation.html#leave-one-out-cross-validation-loocv"><i class="fa fa-check"></i><b>10.5</b> “Leave one out” Cross-Validation (LOOCV)</a></li>
<li class="chapter" data-level="10.6" data-path="model-validation.html"><a href="model-validation.html#k-fold-cross-validation"><i class="fa fa-check"></i><b>10.6</b> <span class="math inline">\(k\)</span>-fold Cross-Validation</a></li>
<li class="chapter" data-level="10.7" data-path="model-validation.html"><a href="model-validation.html#a-final-note"><i class="fa fa-check"></i><b>10.7</b> A final note</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="statistical-odds.html"><a href="statistical-odds.html"><i class="fa fa-check"></i><b>11</b> Statistical Odds</a>
<ul>
<li class="chapter" data-level="11.1" data-path="statistical-odds.html"><a href="statistical-odds.html#probability-versus-odds"><i class="fa fa-check"></i><b>11.1</b> Probability versus Odds</a></li>
<li class="chapter" data-level="11.2" data-path="statistical-odds.html"><a href="statistical-odds.html#odds-ratios"><i class="fa fa-check"></i><b>11.2</b> Odds ratios</a></li>
<li class="chapter" data-level="11.3" data-path="statistical-odds.html"><a href="statistical-odds.html#ideas-of-modeling-odds"><i class="fa fa-check"></i><b>11.3</b> Ideas of modeling odds</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-model"><i class="fa fa-check"></i><b>12.1</b> Logistic Model</a></li>
<li class="chapter" data-level="12.2" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-interpreting-and-assessing-a-logistic-model"><i class="fa fa-check"></i><b>12.2</b> Fitting, Interpreting and assessing a logistic model</a></li>
<li class="chapter" data-level="12.3" data-path="logistic-regression.html"><a href="logistic-regression.html#case-study---titanic-dataset"><i class="fa fa-check"></i><b>12.3</b> Case Study - Titanic Dataset</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>13</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="13.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>13.1</b> Poisson Regression</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-distribution"><i class="fa fa-check"></i><b>13.1.1</b> Poisson distribution</a></li>
<li class="chapter" data-level="13.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression-development"><i class="fa fa-check"></i><b>13.1.2</b> Poisson Regression Development</a></li>
<li class="chapter" data-level="13.1.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#example---tropical-cyclone-counts-in-the-north-atlantic"><i class="fa fa-check"></i><b>13.1.3</b> Example - Tropical Cyclone Counts in the North Atlantic</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#handling-overdispersion"><i class="fa fa-check"></i><b>13.2</b> Handling overdispersion</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#example-attendnace-records"><i class="fa fa-check"></i><b>13.2.1</b> Example – Attendnace Records</a></li>
<li class="chapter" data-level="13.2.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#incorrect-poisson-model"><i class="fa fa-check"></i><b>13.2.2</b> Incorrect Poisson Model</a></li>
<li class="chapter" data-level="13.2.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#a-quasi-poisson-approach"><i class="fa fa-check"></i><b>13.2.3</b> A quasi-Poisson approach</a></li>
<li class="chapter" data-level="13.2.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#fitting-a-negative-binomial-regression"><i class="fa fa-check"></i><b>13.2.4</b> Fitting a Negative Binomial regression</a></li>
<li class="chapter" data-level="13.2.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#picking-between-quasi-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>13.2.5</b> Picking between Quasi-Poisson and Negative Binomial</a></li>
<li class="chapter" data-level="13.2.6" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#infererence-on-predictor-variables"><i class="fa fa-check"></i><b>13.2.6</b> Infererence on predictor variables</a></li>
<li class="chapter" data-level="13.2.7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#plotting-fitted-model"><i class="fa fa-check"></i><b>13.2.7</b> Plotting fitted model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="advanced-designs" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Advanced Designs</h1>
<p>The previous chapters have established the groundwork of experimental designed. We discussed the key elements of experimental units, factors, response variables, treatments, confounding influences and the purpose of replication and randomization. This former work just scratches the surface of the field of experimental design and the analyses associated with those designs. The objective of this chapter includes:</p>
<ul>
<li>Understanding the basic structure of factorial designs</li>
<li>Understanding the basic structure of within-subject designs</li>
<li>Building an appreciation for the complexity of experimental design</li>
</ul>
<div id="higher-order-factor-models" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Higher order factor models</h2>
<p>In the previous two chapters we’ve seen a One-Way and Two-Way ANOVA. In the former, a single factor consisted of <span class="math inline">\(k\)</span>-levels (and thus <span class="math inline">\(k\)</span>-treatments) while in the latter the first factor may consist of <span class="math inline">\(k\)</span> levels and the second factor <span class="math inline">\(j\)</span> levels (and therefore <span class="math inline">\(k\times j\)</span> treatments). Consider the following example.</p>
<p><strong>Example.</strong> Marketing research contractors. A marketing research consultant evaluated the effects of free schedule, scope of work and type of supervisory control on the quality of work performed under contract by independent marketing research agencies. The design of this experiment can be summarized as follows</p>
<p><span class="math display">\[\begin{array}{ll} 
\textbf{Factor} &amp; \textbf{Factor Levels} \\
\hline
\textrm{Fee level} &amp; \textrm{High} \\
 &amp; \textrm{Average} \\
 &amp; \textrm{Low}\\
 \hline
\textrm{Scope} &amp; \textrm{In house} \\
 &amp; \textrm{Subcontracted} \\
\hline
\textrm{Supervision} &amp; \textrm{Local Supervisors}\\
 &amp; \textrm{Traveling Supervisors} \\
\end{array}\]</span></p>
<p>The quality of work performed was measured by an index taking into account several characteristics of quality.</p>
<p>You should note there are three factors in this experiment, with 3, 2 and 2 levels for each factor. This means the number of treatments is <span class="math inline">\(3\times 2\times 2 = 12\)</span> and can be summarized in the following table.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="4">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Supervision
</div>
</th>
</tr>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Local Supervisers
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Traveling Supervisors
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Fee Level
</th>
<th style="text-align:left;">
In house
</th>
<th style="text-align:left;">
Subcontracted
</th>
<th style="text-align:left;">
In house
</th>
<th style="text-align:left;">
Subcontracted
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
High
</td>
<td style="text-align:left;">
Treatment 1
</td>
<td style="text-align:left;">
Treatment 2
</td>
<td style="text-align:left;">
Treatment 3
</td>
<td style="text-align:left;">
Treatment 4
</td>
</tr>
<tr>
<td style="text-align:left;">
Average
</td>
<td style="text-align:left;">
Treatment 5
</td>
<td style="text-align:left;">
Treatment 6
</td>
<td style="text-align:left;">
Treatment 7
</td>
<td style="text-align:left;">
Treatment 8
</td>
</tr>
<tr>
<td style="text-align:left;">
Low
</td>
<td style="text-align:left;">
Treatment 9
</td>
<td style="text-align:left;">
Treatment 10
</td>
<td style="text-align:left;">
Treatment 11
</td>
<td style="text-align:left;">
Treatment 12
</td>
</tr>
</tbody>
</table>
<p>Recall the main idea from two-factor experiments, the interaction terms are typically very important. In this three factor design we have the three main effects (Fee level, Scope and Supervision) but then we also have pairwise interactions between these variables and an interaction among all three. From a statistical modeling perspective, we are now essentially fitting the model</p>
<p><span class="math display">\[Y_{ijkm} = \mu + \alpha_i + \beta_j + \gamma_k + (\alpha\beta)_{ij} + (\alpha\gamma)_{ik} + (\beta\gamma)_{jk} + (\alpha\beta\gamma)_{ijk} + \varepsilon_{ijkm}\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Y_{ijkm}\)</span> is the <span class="math inline">\(m^\mathrm{th}\)</span> observation in the <span class="math inline">\(i^\mathrm{th}\)</span> level of the first factor, the <span class="math inline">\(j^\mathrm{th}\)</span> level of the second factor and the <span class="math inline">\(k^\mathrm{th}\)</span> level of the third factor.</li>
<li><span class="math inline">\(\mu\)</span> is an overall mean</li>
<li>Fee level main effect <span class="math inline">\(\alpha_i\)</span></li>
<li>Scope main effect <span class="math inline">\(\beta_j\)</span></li>
<li>Supervision main effect <span class="math inline">\(\gamma_k\)</span></li>
<li>Fee level and Scope interaction effect <span class="math inline">\((\alpha\beta)_{ij}\)</span></li>
<li>Fee level and Supervision interaction effect <span class="math inline">\((\alpha\gamma)_{ik}\)</span></li>
<li>Scope and Supervision interaction effect <span class="math inline">\((\beta\gamma)_{jk}\)</span></li>
<li>Fee level, Scope and Supervision interaction effect <span class="math inline">\((\alpha\beta\gamma)_{ijk}\)</span></li>
<li><span class="math inline">\(\varepsilon_{ijkm}\)</span> is the random error term</li>
</ul>
<p>As you can see this model has grown greater compare to to the two-way ANOVA examples from before.</p>
<p><strong>What will happen if there are four factors?</strong></p>
<p>In general, if an experiment consisted of <span class="math inline">\(n\)</span> factors, we would potentially have <span class="math inline">\(2^n - 1\)</span> terms in our model, thus with four factors you are looking at 15 terms in your ANOVA decomposition. With five factors, 31 terms. This will quickly grow out of control.</p>
<p>Fortunately, for higher order factor problems there are statisticians available to help formulate a better design and potentially <em>optimize</em> some of the variables of study. We leave out the details of these topics in this Introductory text but want to provide insight that these advanced designs and analyses can be done. Please consult a statistician before your experiment if you are planning a complex design!!</p>
<p><strong>Example continued.</strong> Below we complete the example involving the marketing research contractors.</p>
<p>First we read in the data and make sure R properly treats the factors.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="advanced-designs.html#cb140-1" aria-hidden="true" tabindex="-1"></a>marketing <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;marketingResearch.txt&quot;</span>, <span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb140-2"><a href="advanced-designs.html#cb140-2" aria-hidden="true" tabindex="-1"></a>marketing <span class="ot">&lt;-</span> marketing <span class="sc">%&gt;%</span></span>
<span id="cb140-3"><a href="advanced-designs.html#cb140-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Fee =</span> <span class="fu">as.factor</span>(Fee),</span>
<span id="cb140-4"><a href="advanced-designs.html#cb140-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Scope =</span> <span class="fu">as.factor</span>(Scope),</span>
<span id="cb140-5"><a href="advanced-designs.html#cb140-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Supervision =</span> <span class="fu">as.factor</span>(Supervision))</span></code></pre></div>
<p>We leave out EDA and residual analysis from this example for brevity. We fit the ANOVA model.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="advanced-designs.html#cb141-1" aria-hidden="true" tabindex="-1"></a>marketing.anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Quality <span class="sc">~</span> Fee<span class="sc">*</span>Scope<span class="sc">*</span>Supervision, <span class="at">data=</span>marketing)</span></code></pre></div>
<p>Here we used the notation <code>Fee*Scope*Supervision</code> so R will fit a full factorial model (that is, all main effects and interaction terms). Now look at the ANOVA output.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="advanced-designs.html#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(marketing.anova)</span></code></pre></div>
<pre><code>##                       Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## Fee                    2  10044    5022  679.34 &lt; 2e-16 ***
## Scope                  1   1834    1834  248.08 &lt; 2e-16 ***
## Supervision            1   3832    3832  518.40 &lt; 2e-16 ***
## Fee:Scope              2      2       1    0.11    0.90    
## Fee:Supervision        2      1       0    0.05    0.95    
## Scope:Supervision      1    575     575   77.75 1.6e-10 ***
## Fee:Scope:Supervision  2      4       2    0.27    0.77    
## Residuals             36    266       7                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Here we see that the three factor interaction term is not significant but the interaction between Scope and Supervision is significant. Interactions involving the Fee level factor are not significant, thus we can interpret the Fee level main effect as being a significant influence on quality. We can also conclude that some combination of Scope and Supervision influence quality. We leave out any multiple comparisons analysis here as it gets incredibly complex when three factors are involved.</p>
</div>
<div id="within-subject-designs" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Within-subject designs</h2>
<p>In the previous two chapters, you have seen different experimental designs where a factor(s) levels are manipulated by the researcher in order to measure a response. In simpler design settings, the factors that are manipulated are of the “between-subjects” type. The one-way ANOVA example in chapter 2 on drug effects on alertness is illustrative of this: each participant (experimental unit) had exactly one drug randomly assigned to them. As such, there is only one observation per experimental unit in the design. Drug was a <strong>between-subjects factor</strong>.</p>
<p><em>Why is that important to note?</em> Because, as you should realize by now, that assures that the observations in the data are all independent. It will be elaborated upon later in this course how crucial this assumption is to the validity of any statistical inferences we draw from the tests/CIs we derive. In fact, independence is more important to inference validity than either normality or constant variance assumptions.</p>
<p>Now, contrast this with the <strong>paired <span class="math inline">\(t\)</span>-test</strong> (see section 2.4). The example we saw there involved giving a sample of 10 mice a dietary treatment drug in order to study its effect on the weight of the mice. Let us think of that problem from a design of experiments point of view: what was/were the factor(s) that were manipulated by the researcher?</p>
<ul>
<li>It was not the diet! Why? Because in the experiment, only one diet was studied: there was no “comparison” diet or placebo used to form a basis for comparison. As such, the dietary treatment in that problem was not a variable at all: it was a constant.</li>
<li>So what is left? The answer is TIME. The researcher measured weight at two time points on each mouse (experimental unit): [1] just before the start of the diet, and [2] three months later. The factor here is time, and it has two levels. Time is a <strong>within-subject factor</strong>.</li>
</ul>
<p>In a designed experiment that involves several measurements made on the same experimental unit over time, the design is called a <strong>repeated measures design</strong>.</p>
<p>The important thing to recognize here is that each mouse provided two observations, not one. It stands to reason that <em>what a particular subject’s weight is after three months might have something to do with (i.e. be related to) what their starting weight was before the diet</em>. That is the layman’s way of saying that the measurements within a subject are <strong>not independent</strong> (i.e. the observations are correlated). If in any analysis we ignored this basic truth, that analysis would be seriously flawed.</p>
<p>So how did we handle this before? A simple strategy which is common with paired data comparisons is to calculate each subject’s difference score (yielding a single difference measurement per subject) and then performing a one-sample <span class="math inline">\(t\)</span>-test on the differences. Each difference score is independent, because each came from a different randomly chosen subject. This is what was done in the paired <span class="math inline">\(t\)</span>-test analysis in section 2.4. Check back and remind yourself of this.</p>
<div id="blocks-revisited-an-approach-to-handling-within-subjects-factors" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Blocks revisited: an approach to handling within-subjects factors</h3>
<p>The notion and purpose of blocking in an experimental design was introduced in section 3.1. If you recall that witty definition of blocks as relatively homogeneously sets of experimental material, it may occur to you that subjects can serve as blocks. In fact, this was already stated in section 3.1. What this means for us now is that using a block design approach in analysis is a way to handle correlated (non-independent) observations such as in the paired <span class="math inline">\(t\)</span>-test problem above. We illustrate that here.</p>
<p><strong>Example.</strong> 10 mice received a dietary treatment during 3 months. We want to know whether the dietary treatment has an impact on the weight of the mice. To answer to this question, the weight of the 20 mice has been measured before and after the treatment and is in the file <code>mice.csv</code>. Below is some code to quickly look at the data:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="advanced-designs.html#cb144-1" aria-hidden="true" tabindex="-1"></a>mice <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;http://www.users.miamioh.edu/hughesmr/sta363/miceWeighttallform.csv&quot;</span>)</span>
<span id="cb144-2"><a href="advanced-designs.html#cb144-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mice)</span></code></pre></div>
<pre><code>##   id  group weight
## 1  1 before  200.1
## 2  2 before  190.9
## 3  3 before  192.7
## 4  4 before  213.0
## 5  5 before  241.4
## 6  6 before  196.9</code></pre>
<p>Note the difference in the layout of the data here as compared to the file <code>miceWeightwideform.csv</code> used in the paired <span class="math inline">\(t\)</span>-test in section 2.4. The data here is in what is called “tall mode”: each observation occupies a single row of the data file now, and there is a new variable (id) that identifies which subject every observation belongs to. The variable group refers to the time factor.</p>
<p>We will analyze this same data (addressing the same research question) by using a <strong>block design approach</strong>:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="advanced-designs.html#cb146-1" aria-hidden="true" tabindex="-1"></a>mice.block.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(weight <span class="sc">~</span> <span class="fu">factor</span>(id) <span class="sc">+</span> group, <span class="at">data=</span>mice)</span>
<span id="cb146-2"><a href="advanced-designs.html#cb146-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mice.block.aov)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## factor(id)   9   6946     772    1.78     0.2    
## group        1 189132  189132  436.11 6.2e-09 ***
## Residuals    9   3903     434                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Look at the <span class="math inline">\(F\)</span>-test for the time factor (labeled group here). This is identical to the result of the paired t-test in section 2.4 (<span class="math inline">\(F\)</span> = 436.11, <span class="math inline">\(\textrm{df}_1\)</span> = 1, <span class="math inline">\(\textrm{df}_2\)</span> = 9, <span class="math inline">\(p\)</span>-value <span class="math inline">\(\approx 6.2\times 10^{-9}\)</span>).</p>
<p><em>How does the block approach work here?</em> You will note that the test of group (the within subjects effect) uses the residual effect as the error term. Because the blocks are accounted for in the model (and here, the blocks constitutes the overall between-mice variability source), the only variation left over for the “residuals” is the variability due to the within-mouse differences. In essence, there are <strong>two components</strong> to the random error now:</p>
<ul>
<li>Aggregated variability between mice (block effect)</li>
<li>Remaining unexplained (random) variability after accounting for aggregate mouse-to-mouse differences and aggregated time-to-time differences. We will call this leftover stuff “pure” error.</li>
</ul>
<p>For a correct analysis, it is important that each factor of interest in the study be tested against the proper component of the error. Here, <strong>we test a within-subjects effect against the random error component dealing with “pure” random error</strong>.</p>
<p>Perhaps <strong>a more general approach</strong> to within-subjects analysis is to specify to R the fact that there are layers of random variability in the data introduced by the fact that we have more than one measurement per experimental unit. This can be done using an <code>aov</code> model specification that explicitly cites these layers with an Error option. The model specification in R is generally</p>
<pre><code>aov(response ~ between-subjects factor structure + Error(EU variable/WS factor)</code></pre>
<p>In the present example, this would be as follows:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="advanced-designs.html#cb149-1" aria-hidden="true" tabindex="-1"></a>WS_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(weight <span class="sc">~</span> group <span class="sc">+</span> <span class="fu">Error</span>(<span class="fu">factor</span>(id)<span class="sc">/</span>group), <span class="at">data=</span>mice)</span>
<span id="cb149-2"><a href="advanced-designs.html#cb149-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(WS_aov)</span></code></pre></div>
<pre><code>## 
## Error: factor(id)
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals  9   6946     772               
## 
## Error: factor(id):group
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## group      1 189132  189132     436 6.2e-09 ***
## Residuals  9   3903     434                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Again we see the same result. It turns out that for more complex studies this general approach is preferred.</p>
</div>
<div id="a-more-involved-repeated-measures-case-study" class="section level3" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> A more involved repeated measures case study</h3>
<p>If we can handle within-subjects factors using blocks, why not just stick with that all the time? Well, the reason is that repeated measures designs can get complicated: multiple time measurement points (not just two), the addition of between-subjects factors, etc. The following case study example illustrates this.</p>
<p><strong>Example: Cholesterol study.</strong> A study tested whether cholesterol was reduced after using a certain brand of margarine as part of a low fat, low cholesterol diet. The subjects consumed on average 2.31g of the active ingredient, stanol ester, a day. This data set <code>cholesterolreduction.csv</code> contains information on 18 people using margarine to reduce cholesterol over three time points.</p>
<p>Source: The University of Sheffield.</p>
<table>
<thead>
<tr>
<th style="text-align:left;">
Variable Name
</th>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Data type
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
ID
</td>
<td style="text-align:left;">
Participant Number
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Before
</td>
<td style="text-align:left;">
Cholesterol befoore the diet (mmol/L)
</td>
<td style="text-align:left;">
Scale
</td>
</tr>
<tr>
<td style="text-align:left;">
After4weeks
</td>
<td style="text-align:left;">
Cholesterol after 4 weeks on diet (mmol/L)
</td>
<td style="text-align:left;">
Scale
</td>
</tr>
<tr>
<td style="text-align:left;">
After8weeks
</td>
<td style="text-align:left;">
Cholesterol after 8 weeks on diet (mmol/L)
</td>
<td style="text-align:left;">
Scale
</td>
</tr>
<tr>
<td style="text-align:left;">
Margarine
</td>
<td style="text-align:left;">
Margarine type A or B
</td>
<td style="text-align:left;">
Binary
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="advanced-designs.html#cb151-1" aria-hidden="true" tabindex="-1"></a>chol <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;http://www.users.miamioh.edu/hughesmr/sta363/cholesterolreduction.csv&quot;</span>)</span>
<span id="cb151-2"><a href="advanced-designs.html#cb151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(chol)</span></code></pre></div>
<pre><code>## Rows: 18
## Columns: 5
## $ ID          &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,~
## $ Before      &lt;dbl&gt; 6.42, 6.76, 6.56, 4.80, 8.43, 7.49, 8.05, 5.05, 5.77, 3.91~
## $ After4weeks &lt;dbl&gt; 5.83, 6.20, 5.83, 4.27, 7.71, 7.12, 7.25, 4.63, 5.31, 3.70~
## $ After8weeks &lt;dbl&gt; 5.75, 6.13, 5.71, 4.15, 7.67, 7.05, 7.10, 4.67, 5.33, 3.66~
## $ Margarine   &lt;chr&gt; &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;B&quot;~</code></pre>
<p>There are two factors of interest here:</p>
<ul>
<li><code>time.pt</code> (3 levels within-subjects: before, after4weeks, after8weeks)</li>
<li><code>Margarine</code> (2 level between-subjects: A or B)</li>
</ul>
<p>Note that the data is currently in wide form. We need to convert it to tall form:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="advanced-designs.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb153-2"><a href="advanced-designs.html#cb153-2" aria-hidden="true" tabindex="-1"></a>chol_tall <span class="ot">&lt;-</span> chol <span class="sc">%&gt;%</span> </span>
<span id="cb153-3"><a href="advanced-designs.html#cb153-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols=</span>Before<span class="sc">:</span>After8weeks, <span class="at">names_to=</span><span class="st">&quot;time.pt&quot;</span>, <span class="at">values_to=</span><span class="st">&quot;chol.level&quot;</span>)</span>
<span id="cb153-4"><a href="advanced-designs.html#cb153-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chol_tall)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##      ID Margarine time.pt     chol.level
##   &lt;int&gt; &lt;chr&gt;     &lt;chr&gt;            &lt;dbl&gt;
## 1     1 B         Before            6.42
## 2     1 B         After4weeks       5.83
## 3     1 B         After8weeks       5.75
## 4     2 A         Before            6.76
## 5     2 A         After4weeks       6.2 
## 6     2 A         After8weeks       6.13</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="advanced-designs.html#cb155-1" aria-hidden="true" tabindex="-1"></a>chol_tall <span class="ot">&lt;-</span> chol_tall <span class="sc">%&gt;%</span></span>
<span id="cb155-2"><a href="advanced-designs.html#cb155-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time.pt =</span> <span class="fu">factor</span>(time.pt, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;Before&quot;</span>, <span class="st">&quot;After4weeks&quot;</span>, <span class="st">&quot;After8weeks&quot;</span>),</span>
<span id="cb155-3"><a href="advanced-designs.html#cb155-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Before&quot;</span>, <span class="st">&quot;After 4 weeks&quot;</span>, <span class="st">&quot;After 8 weeks&quot;</span>)))</span></code></pre></div>
<p>Note here change the variable <code>time.pt</code> to be a factor and we order the factors levels so they are sequential (in context)..</p>
<div id="exploratory-data-analysis" class="section level4" number="4.2.2.1">
<h4><span class="header-section-number">4.2.2.1</span> Exploratory Data Analysis</h4>
<p>We are now ready for some EDA. A table of descriptive statistics by combinations of time and margarine group is our first cut:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="advanced-designs.html#cb156-1" aria-hidden="true" tabindex="-1"></a>chol.summary <span class="ot">&lt;-</span> chol_tall <span class="sc">%&gt;%</span></span>
<span id="cb156-2"><a href="advanced-designs.html#cb156-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Margarine, time.pt) <span class="sc">%&gt;%</span></span>
<span id="cb156-3"><a href="advanced-designs.html#cb156-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Mean =</span> <span class="fu">mean</span>(chol.level),</span>
<span id="cb156-4"><a href="advanced-designs.html#cb156-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">SD =</span> <span class="fu">sd</span>(chol.level),</span>
<span id="cb156-5"><a href="advanced-designs.html#cb156-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">SE =</span> <span class="fu">sd</span>(chol.level)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(chol.level)),</span>
<span id="cb156-6"><a href="advanced-designs.html#cb156-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">length</span>(chol.level))</span>
<span id="cb156-7"><a href="advanced-designs.html#cb156-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(chol.summary)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
Margarine
</th>
<th style="text-align:left;">
time.pt
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
SD
</th>
<th style="text-align:right;">
SE
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
Before
</td>
<td style="text-align:right;">
6.03556
</td>
<td style="text-align:right;">
1.363232
</td>
<td style="text-align:right;">
0.454411
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
After 4 weeks
</td>
<td style="text-align:right;">
5.55000
</td>
<td style="text-align:right;">
1.320672
</td>
<td style="text-align:right;">
0.440224
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:left;">
After 8 weeks
</td>
<td style="text-align:right;">
5.48889
</td>
<td style="text-align:right;">
1.307282
</td>
<td style="text-align:right;">
0.435761
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:left;">
Before
</td>
<td style="text-align:right;">
6.78000
</td>
<td style="text-align:right;">
0.919008
</td>
<td style="text-align:right;">
0.306336
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:left;">
After 4 weeks
</td>
<td style="text-align:right;">
6.13333
</td>
<td style="text-align:right;">
0.863713
</td>
<td style="text-align:right;">
0.287904
</td>
<td style="text-align:right;">
9
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:left;">
After 8 weeks
</td>
<td style="text-align:right;">
6.06889
</td>
<td style="text-align:right;">
0.825825
</td>
<td style="text-align:right;">
0.275275
</td>
<td style="text-align:right;">
9
</td>
</tr>
</tbody>
</table>
<p>We generally observe that cholesterol levels with margarine A appear lower than with margarine B. Also, there does appear to be some reduction in cholesterol level using both products: however, there also appears to be more unexplained variability (“noise”) in the cholesterol measurements under margarine A. We can further check this using some data visualizations. First let us try boxplots as seen in Figure <a href="advanced-designs.html#fig:ch4-7">4.1</a>.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="advanced-designs.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chol_tall) <span class="sc">+</span></span>
<span id="cb157-2"><a href="advanced-designs.html#cb157-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>time.pt, <span class="at">y=</span>chol.level)) <span class="sc">+</span></span>
<span id="cb157-3"><a href="advanced-designs.html#cb157-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Margarine) <span class="sc">+</span></span>
<span id="cb157-4"><a href="advanced-designs.html#cb157-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Time Point of Measurement&quot;</span>) <span class="sc">+</span></span>
<span id="cb157-5"><a href="advanced-designs.html#cb157-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cholesterol level (mmol/L)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-7"></span>
<img src="introStatModeling_files/figure-html/ch4-7-1.png" alt="Boxplot distribution of the Cholesterol level as a function of Treatment and Time of measurement." width="100%" />
<p class="caption">
Figure 4.1: Boxplot distribution of the Cholesterol level as a function of Treatment and Time of measurement.
</p>
</div>
<p>We see in Figure <a href="advanced-designs.html#fig:ch4-7">4.1</a> that perhaps cholesterol levels are generally more consistent under margarine B, and that it is just some outlier(s) that are the issue. However, this plot does not reveal a crucial piece of information: <strong>the responses are correlated over time</strong>. A better depiction would allow us to see how each individual subject’s cholesterol changed over the span of the experiment as seen in Figure <a href="advanced-designs.html#fig:ch4-8">4.2</a>.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="advanced-designs.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the individual-level cholesterol profiles</span></span>
<span id="cb158-2"><a href="advanced-designs.html#cb158-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chol_tall, <span class="fu">aes</span>(<span class="at">x=</span>time.pt, <span class="at">y=</span>chol.level, <span class="at">colour=</span>Margarine, <span class="at">group=</span>ID)) <span class="sc">+</span></span>
<span id="cb158-3"><a href="advanced-designs.html#cb158-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">21</span>, <span class="at">fill=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span> </span>
<span id="cb158-4"><a href="advanced-designs.html#cb158-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Margarine) <span class="sc">+</span></span>
<span id="cb158-5"><a href="advanced-designs.html#cb158-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Time Point of Measurement&quot;</span>) <span class="sc">+</span></span>
<span id="cb158-6"><a href="advanced-designs.html#cb158-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cholesterol level (mmol/L)&quot;</span>) <span class="sc">+</span></span>
<span id="cb158-7"><a href="advanced-designs.html#cb158-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Subject-level cholesterol profiles by Margarine group&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-8"></span>
<img src="introStatModeling_files/figure-html/ch4-8-1.png" alt="Profile plots of the Cholesterol level as a function of Treatment and Time of measurement." width="100%" />
<p class="caption">
Figure 4.2: Profile plots of the Cholesterol level as a function of Treatment and Time of measurement.
</p>
</div>
<p>In Figure <a href="advanced-designs.html#fig:ch4-8">4.2</a> we see some things more clearly. The general pattern over time appears to be pretty consistent for every experimental unit (visually, each “line” in the plot). There are two individuals in margarine B whose cholesterol level seems unusually higher than the others: this might warrant further investigation. Now we provide an summary profile of the two treatments in <a href="advanced-designs.html#fig:ch4-9">4.3</a>.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="advanced-designs.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we include a position_dodge elements to avoid overlap</span></span>
<span id="cb159-2"><a href="advanced-designs.html#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chol.summary, <span class="fu">aes</span>(<span class="at">x=</span>time.pt, <span class="at">y=</span>Mean, <span class="at">colour=</span>Margarine)) <span class="sc">+</span> </span>
<span id="cb159-3"><a href="advanced-designs.html#cb159-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>Mean<span class="sc">-</span>SE, <span class="at">ymax=</span>Mean<span class="sc">+</span>SE), <span class="at">width=</span>.<span class="dv">1</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb159-4"><a href="advanced-designs.html#cb159-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group=</span>Margarine), <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb159-5"><a href="advanced-designs.html#cb159-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb159-6"><a href="advanced-designs.html#cb159-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Time Point of Measurement&quot;</span>) <span class="sc">+</span></span>
<span id="cb159-7"><a href="advanced-designs.html#cb159-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cholesterol level (mmol/L)&quot;</span>) <span class="sc">+</span></span>
<span id="cb159-8"><a href="advanced-designs.html#cb159-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mean Cholesterol level (with Standard Error bars)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-9"></span>
<img src="introStatModeling_files/figure-html/ch4-9-1.png" alt="Average Profile of Cholesterol level by Treatment in Time." width="70%" />
<p class="caption">
Figure 4.3: Average Profile of Cholesterol level by Treatment in Time.
</p>
</div>
<p>In the summary version (<a href="advanced-designs.html#fig:ch4-9">4.3</a>) we see that margarine A Cholesterol levels appear lower than margarine B. It is worth noting that the group assigned to margarine level A had lower cholesterol “before” the study began.</p>
</div>
<div id="preliminary-inferential-analysis" class="section level4" number="4.2.2.2">
<h4><span class="header-section-number">4.2.2.2</span> Preliminary inferential analysis</h4>
<p>Of more concern to a fully correct analysis is addressing why there appears to be a difference between the margarine groups at the “Before” stage. At that point, no margarines had been administered, so if the subjects had been truly randomly assigned to the margarine groups (as they should be in a properly designed experiment!), we would have expected consistent cholesterol readings between the groups at that point. This can be formally tested as follows, with a simple independent samples <span class="math inline">\(t\)</span>-test comparing the mean cholesterol levels of the A and B groups at the “Before” stage:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="advanced-designs.html#cb160-1" aria-hidden="true" tabindex="-1"></a>BeforeDataOnly <span class="ot">&lt;-</span> chol_tall <span class="sc">%&gt;%</span></span>
<span id="cb160-2"><a href="advanced-designs.html#cb160-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(time.pt <span class="sc">==</span> <span class="st">&quot;Before&quot;</span>)</span>
<span id="cb160-3"><a href="advanced-designs.html#cb160-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chol.level <span class="sc">~</span> Margarine, <span class="at">data=</span>BeforeDataOnly, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  chol.level by Margarine
## t = -1.358, df = 16, p-value = 0.193
## alternative hypothesis: true difference in means between group A and group B is not equal to 0
## 95 percent confidence interval:
##  -1.906205  0.417316
## sample estimates:
## mean in group A mean in group B 
##         6.03556         6.78000</code></pre>
<p>The result is not statistically significant (<span class="math inline">\(p\)</span>-value = 0.1932). That is actually good news here! Although visually it appears different it is not statistically different.</p>
</div>
<div id="a-conditional-repeated-measures-analysis" class="section level4" number="4.2.2.3">
<h4><span class="header-section-number">4.2.2.3</span> A conditional repeated measures analysis</h4>
<p>To get started, lets do a within-subjects (repeated measures) ANOVA on the Margarine A data only. The goal here would be to see if there is an effective reduction in mean cholesterol over the eight-week trial by using margarine A. Here goes: follow the code!</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="advanced-designs.html#cb162-1" aria-hidden="true" tabindex="-1"></a>MargarineA <span class="ot">&lt;-</span> chol_tall <span class="sc">%&gt;%</span> </span>
<span id="cb162-2"><a href="advanced-designs.html#cb162-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Margarine <span class="sc">==</span> <span class="st">&quot;A&quot;</span>)</span>
<span id="cb162-3"><a href="advanced-designs.html#cb162-3" aria-hidden="true" tabindex="-1"></a>RMaov_MargA <span class="ot">&lt;-</span> <span class="fu">aov</span>(chol.level <span class="sc">~</span> time.pt <span class="sc">+</span> <span class="fu">Error</span>(<span class="fu">factor</span>(ID)<span class="sc">/</span>time.pt), <span class="at">data=</span>MargarineA)</span>
<span id="cb162-4"><a href="advanced-designs.html#cb162-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RMaov_MargA)</span></code></pre></div>
<pre><code>## 
## Error: factor(ID)
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals  8   42.4     5.3               
## 
## Error: factor(ID):time.pt
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## time.pt    2  1.615   0.808     106 5.8e-10 ***
## Residuals 16  0.122   0.008                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The test of interest is labeled time.pt. It is significant (<span class="math inline">\(F\)</span> = 106.3, <span class="math inline">\(\textrm{df}_1\)</span> = 2, <span class="math inline">\(\textrm{df}_2\)</span> = 16, <span class="math inline">\(p\)</span>-value = <span class="math inline">\(5.7 \times 10^{-10}\)</span>). What this means is that, using Margarine A, there is significant evidence to conclude that the <em>true mean cholesterol level differs between at least two of the time points</em>. Of course, that result does not mean that the margarine is effective at reducing cholesterol levels. All it means is that the mean cholesterol level is changing at some point over the experiment. Since there are three time points, a multiple comparison procedure is warranted with the output below and in Figure <a href="advanced-designs.html#fig:ch4-12">4.4</a>.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="advanced-designs.html#cb164-1" aria-hidden="true" tabindex="-1"></a>MargA.mc <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(RMaov_MargA, <span class="sc">~</span> time.pt)</span></code></pre></div>
<pre><code>## Note: re-fitting model with sum-to-zero contrasts</code></pre>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="advanced-designs.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(MargA.mc, <span class="st">&quot;pairwise&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast                      estimate     SE df t.ratio p.value
##  Before - After 4 weeks          0.4856 0.0411 16  11.817  &lt;.0001
##  Before - After 8 weeks          0.5467 0.0411 16  13.304  &lt;.0001
##  After 4 weeks - After 8 weeks   0.0611 0.0411 16   1.487  0.3229
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="advanced-designs.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(MargA.mc, <span class="st">&quot;pairwise&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-12"></span>
<img src="introStatModeling_files/figure-html/ch4-12-1.png" alt="Comparing the effects of time within the Margarine A treatment groupu. We see there is no statistical difference between 4 and 8 weeks after treatment begins." width="70%" />
<p class="caption">
Figure 4.4: Comparing the effects of time within the Margarine A treatment groupu. We see there is no statistical difference between 4 and 8 weeks after treatment begins.
</p>
</div>
<p>The significant reductions in mean cholesterol level under Margarine A occurs right after the start of the experiment. The mean cholesterol level is reduced by 0.485 (SE = 0.041) by week 4 (<span class="math inline">\(p\)</span>-value &lt; 0.0001); and by 0.546 (SE = 0.041) by week 8 (<span class="math inline">\(p\)</span>-value &lt; 0.0001). There is no appreciable change in mean cholesterol level between weeks 4 and 8 (<span class="math inline">\(p\)</span>-value = 0.3229).</p>
</div>
<div id="full-analysis-formal-comparison-of-margarines" class="section level4" number="4.2.2.4">
<h4><span class="header-section-number">4.2.2.4</span> Full analysis: Formal Comparison of Margarines</h4>
<p>It is always critically important to know the structure of the data, which here stems from the design of the experiment. In this case, we cannot just “compared the margarines” because there is a subject-level time profile under each margarine. Since the same time points are observed under each margarine group, the factors margarine and <code>time.pt</code> are crossed effects, which means we have a <em>factorial data structure</em> (see section 3.2). The “wrinkle” here is that one of the two factors is a between-subjects factor (Margarine) and the other is within-subjects (<code>time.pt</code>). But, we can handle this in <code>aov</code>:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="advanced-designs.html#cb169-1" aria-hidden="true" tabindex="-1"></a>RMaov_all <span class="ot">&lt;-</span> <span class="fu">aov</span>(chol.level <span class="sc">~</span> Margarine <span class="sc">+</span> time.pt <span class="sc">+</span> Margarine<span class="sc">:</span>time.pt <span class="sc">+</span> </span>
<span id="cb169-2"><a href="advanced-designs.html#cb169-2" aria-hidden="true" tabindex="-1"></a>                              <span class="fu">Error</span>(<span class="fu">factor</span>(ID)<span class="sc">/</span>time.pt), <span class="at">data=</span>chol_tall)</span>
<span id="cb169-3"><a href="advanced-designs.html#cb169-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(RMaov_all)</span></code></pre></div>
<pre><code>## 
## Error: factor(ID)
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Margarine  1    5.5    5.46    1.45   0.25
## Residuals 16   60.4    3.78               
## 
## Error: factor(ID):time.pt
##                   Df Sum Sq Mean Sq F value Pr(&gt;F)    
## time.pt            2   4.32   2.160  259.49 &lt;2e-16 ***
## Margarine:time.pt  2   0.08   0.040    4.78  0.015 *  
## Residuals         32   0.27   0.008                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As with the factorials models before, the first thing we must check is the significance of the interaction term. If this is significant, it means that the effect of time on the mean cholesterol is different between the two margarines. That is the case here (<span class="math inline">\(F\)</span> = 4.777, <span class="math inline">\(\textrm{df}_1\)</span> = 2, <span class="math inline">\(\textrm{df}_2\)</span> = 32, <span class="math inline">\(p\)</span>-value = 0.0153). As a result, we should do our multiple comparisons <strong>by conditioning on one of the two factors</strong>. Experimental context will dictate which of the two factors is the more reasonable to condition on. Here, I choose to condition on Margarine group, so I will get a time-based comparison of mean cholesterol level, but specific to each Margarine group:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="advanced-designs.html#cb171-1" aria-hidden="true" tabindex="-1"></a>RMall.mc <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(RMaov_all, <span class="sc">~</span> time.pt <span class="sc">|</span> Margarine)</span></code></pre></div>
<pre><code>## Note: re-fitting model with sum-to-zero contrasts</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="advanced-designs.html#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(RMall.mc, <span class="st">&quot;pairwise&quot;</span>)</span></code></pre></div>
<pre><code>## Margarine = A:
##  contrast                      estimate    SE df t.ratio p.value
##  Before - After 4 weeks          0.4856 0.043 32  11.290  &lt;.0001
##  Before - After 8 weeks          0.5467 0.043 32  12.711  &lt;.0001
##  After 4 weeks - After 8 weeks   0.0611 0.043 32   1.421  0.3424
## 
## Margarine = B:
##  contrast                      estimate    SE df t.ratio p.value
##  Before - After 4 weeks          0.6467 0.043 32  15.036  &lt;.0001
##  Before - After 8 weeks          0.7111 0.043 32  16.535  &lt;.0001
##  After 4 weeks - After 8 weeks   0.0644 0.043 32   1.498  0.3051
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="advanced-designs.html#cb175-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(RMall.mc, <span class="st">&quot;pairwise&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-14"></span>
<img src="introStatModeling_files/figure-html/ch4-14-1.png" alt="Graphical exploration of all treatments noting that there is no statistical difference between 4 and 8 weeks after the study has began regardless of Margarine treatment." width="70%" />
<p class="caption">
Figure 4.5: Graphical exploration of all treatments noting that there is no statistical difference between 4 and 8 weeks after the study has began regardless of Margarine treatment.
</p>
</div>
<p>Even though at first glance the time-based comparisons look about the same between the two margarines, the point estimates and plots reveal the story: the reductions in mean cholesterol following the initiation of the study are larger for margarine B (mean=0.7111 mmol/L, SE=0.043 by week 8) than for margarine A (mean=0.546 mmol/L, SE=0.043 by week 8).</p>
</div>
</div>
<div id="further-study" class="section level3" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Further study</h3>
<p>More thorough analysis of within-subjects and repeated measures designs are possible using advanced methods beyond the scope of this course. These methods include:</p>
<ul>
<li>processes that allow the analyst to estimate the degree of correlation between repeated measurements</li>
<li>processes that allow one to model different correlation structures based upon experimental realities in the data collection process</li>
</ul>
<p>For example, suppose we had a repeated measures experiment with subjects measured across four time points: Week 1, 2, 3 and 8. Because of the time spacing, we might expect that measurements between adjacent weeks to be more similar within a subject than weeks far removed in time. For example, it is reasonable to expect that results in week 2 are more strongly correlated to week 1 results than would be the correlation between weeks 3 and 1. Week 8’s results might be so far removed from the first few weeks that the results there might be safely presumed to be nearly independent of earlier results. We could even be more restrictive, using an approach that assumes only adjacent time point results are correlated, but beyond that, assume independence.</p>
<p>Subtleties like this can be modeled and checked using advanced modeling techniques.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multiple-factor-designed-experiments.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-multiple-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["introStatModeling.pdf", "introStatModeling.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
