<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Concepts of Advanced Designs | Introduction to Statistical Modeling</title>
  <meta name="description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Concepts of Advanced Designs | Introduction to Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  <meta name="github-repo" content="tjfisher19/introStatModeling" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Concepts of Advanced Designs | Introduction to Statistical Modeling" />
  
  <meta name="twitter:description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  

<meta name="author" content="Michael R. Hughes and Thomas J. Fisher" />


<meta name="date" content="2025-12-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-factor-designed-experiments.html"/>
<link rel="next" href="introduction-to-multiple-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css_files/mystyle.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Inroduction to Statistical Modeling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html"><i class="fa fa-check"></i>Important Preliminary Review</a>
<ul>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#statistics-background"><i class="fa fa-check"></i>Statistics background</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#software"><i class="fa fa-check"></i>Software</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#add-on-packages"><i class="fa fa-check"></i>Add-on packages</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#help-with-rmarkdown"><i class="fa fa-check"></i>Help with RMarkdown</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#managing-your-work-in-r"><i class="fa fa-check"></i>Managing your work in R</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#data-in-this-text"><i class="fa fa-check"></i>Data in this text</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html"><i class="fa fa-check"></i><b>1</b> Introductory Statistics in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#goals-of-a-statistical-analysis"><i class="fa fa-check"></i><b>1.1</b> Goals of a statistical analysis</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#conducting-a-statistical-analysis"><i class="fa fa-check"></i><b>1.1.1</b> Conducting a statistical analysis</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#introduction-to-r"><i class="fa fa-check"></i><b>1.2</b> Introduction to R</a></li>
<li class="chapter" data-level="1.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#data-frames"><i class="fa fa-check"></i><b>1.3</b> Data frames</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#built-in-data"><i class="fa fa-check"></i><b>1.3.1</b> Built-in data</a></li>
<li class="chapter" data-level="1.3.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#dataTypesSection"><i class="fa fa-check"></i><b>1.3.2</b> Types of Data</a></li>
<li class="chapter" data-level="1.3.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#importing-datasets-into-r"><i class="fa fa-check"></i><b>1.3.3</b> Importing datasets into R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#referencing-data-from-inside-a-data-frame"><i class="fa fa-check"></i><b>1.4</b> Referencing data from inside a data frame</a></li>
<li class="chapter" data-level="1.5" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#missing-values-and-computer-arithmetic-in-r"><i class="fa fa-check"></i><b>1.5</b> Missing values and computer arithmetic in R</a></li>
<li class="chapter" data-level="1.6" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#exploratory-data-analysis-eda"><i class="fa fa-check"></i><b>1.6</b> Exploratory Data Analysis (EDA)</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#numeric-summaries"><i class="fa fa-check"></i><b>1.6.1</b> Numeric Summaries</a></li>
<li class="chapter" data-level="1.6.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#numericSummaries"><i class="fa fa-check"></i><b>1.6.2</b> Numeric Summaries in R</a></li>
<li class="chapter" data-level="1.6.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#graphical-summaries"><i class="fa fa-check"></i><b>1.6.3</b> Graphical Summaries</a></li>
<li class="chapter" data-level="1.6.4" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#distribution-of-univariate-variables"><i class="fa fa-check"></i><b>1.6.4</b> Distribution of Univariate Variables</a></li>
<li class="chapter" data-level="1.6.5" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-by-levels-of-a-factor-variable"><i class="fa fa-check"></i><b>1.6.5</b> Descriptive statistics and visualizations by levels of a factor variable</a></li>
<li class="chapter" data-level="1.6.6" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-for-two-numeric-variables"><i class="fa fa-check"></i><b>1.6.6</b> Descriptive statistics and visualizations for two numeric variables</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#sampling-distributions-describing-how-a-statistic-varies"><i class="fa fa-check"></i><b>1.7</b> Sampling distributions: describing how a statistic varies</a></li>
<li class="chapter" data-level="1.8" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#twoSampleInference"><i class="fa fa-check"></i><b>1.8</b> Two-sample inference</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling and Designed Experiments</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#dataSources"><i class="fa fa-check"></i><b>2.1</b> Observational Studies versus designed experiments</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#observational-studies"><i class="fa fa-check"></i><b>2.1.1</b> Observational Studies</a></li>
<li class="chapter" data-level="2.1.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#designed-experiments"><i class="fa fa-check"></i><b>2.1.2</b> Designed experiments</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#designed-experiement-vocabulary"><i class="fa fa-check"></i><b>2.2</b> Designed experiement vocabulary</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#what-is-an-experiment"><i class="fa fa-check"></i><b>2.2.1</b> What is an experiment?</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#analysis-of-variance"><i class="fa fa-check"></i><b>2.2.2</b> Analysis of variance</a></li>
<li class="chapter" data-level="2.2.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#elements-of-a-designed-experiment"><i class="fa fa-check"></i><b>2.2.3</b> Elements of a designed experiment</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#statistical-analyses-is-modeling"><i class="fa fa-check"></i><b>2.3</b> Statistical Analyses is Modeling</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#twoSampletTest"><i class="fa fa-check"></i><b>2.3.1</b> Example of a two-sample <span class="math inline">\(t\)</span>-test as a model</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#one-way-anova"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#model-structure"><i class="fa fa-check"></i><b>2.4.1</b> Model Structure</a></li>
<li class="chapter" data-level="2.4.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#testing-procedure"><i class="fa fa-check"></i><b>2.4.2</b> Testing Procedure</a></li>
<li class="chapter" data-level="2.4.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#example-of-one-way-anova"><i class="fa fa-check"></i><b>2.4.3</b> Example of One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#assumptionCheck"><i class="fa fa-check"></i><b>2.5</b> Model Assumptions and Assessment</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#structural-assumptions"><i class="fa fa-check"></i><b>2.5.1</b> Structural Assumptions</a></li>
<li class="chapter" data-level="2.5.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#random-variation-assumptions"><i class="fa fa-check"></i><b>2.5.2</b> Random Variation Assumptions</a></li>
<li class="chapter" data-level="2.5.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#code-to-check-assumptions"><i class="fa fa-check"></i><b>2.5.3</b> Code to check assumptions</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#transforming-your-response"><i class="fa fa-check"></i><b>2.6</b> Transforming your response</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#a-note-on-logarithmic-transformations"><i class="fa fa-check"></i><b>2.6.1</b> A note on logarithmic transformations</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#anova-testing-in-r"><i class="fa fa-check"></i><b>2.7</b> ANOVA Testing in R</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#reading-an-anova-table"><i class="fa fa-check"></i><b>2.7.1</b> Reading an ANOVA table</a></li>
<li class="chapter" data-level="2.7.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#conclusions-and-limitation-of-anova"><i class="fa fa-check"></i><b>2.7.2</b> Conclusions and Limitation of ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#follow-up-procedures-multiple-comparisons"><i class="fa fa-check"></i><b>2.8</b> Follow-up procedures – Multiple Comparisons</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#multiple-testing-problem"><i class="fa fa-check"></i><b>2.8.1</b> Multiple testing problem</a></li>
<li class="chapter" data-level="2.8.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#tukeys-hsd-method"><i class="fa fa-check"></i><b>2.8.2</b> Tukey’s HSD method</a></li>
<li class="chapter" data-level="2.8.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#dunnett-multiple-comparisons"><i class="fa fa-check"></i><b>2.8.3</b> Dunnett multiple comparisons</a></li>
<li class="chapter" data-level="2.8.4" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#coding-notes-about-emmeans"><i class="fa fa-check"></i><b>2.8.4</b> Coding notes about <code>emmeans</code></a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#two-sample-t-test-as-anova"><i class="fa fa-check"></i><b>2.9</b> Two-sample <span class="math inline">\(t\)</span>-test as ANOVA</a></li>
<li class="chapter" data-level="2.10" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#completeOneWay"><i class="fa fa-check"></i><b>2.10</b> A Complete One-Way ANOVA Example</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html"><i class="fa fa-check"></i><b>3</b> Multiple Factor Designed Experiments</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#blockingSection"><i class="fa fa-check"></i><b>3.1</b> Blocking</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#model-form-of-a-randomized-block-design"><i class="fa fa-check"></i><b>3.1.1</b> Model form of a Randomized Block Design</a></li>
<li class="chapter" data-level="3.1.2" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#block-anova-example"><i class="fa fa-check"></i><b>3.1.2</b> Block ANOVA Example</a></li>
<li class="chapter" data-level="3.1.3" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#pairedTtest"><i class="fa fa-check"></i><b>3.1.3</b> Paired <span class="math inline">\(t\)</span>-test as a Block ANOVA</a></li>
<li class="chapter" data-level="3.1.4" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#another-block-anova-example"><i class="fa fa-check"></i><b>3.1.4</b> Another Block ANOVA Example</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#twoFactorDesigns"><i class="fa fa-check"></i><b>3.2</b> Two-factor Designs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#analysis-of-a-two-factor-design"><i class="fa fa-check"></i><b>3.2.1</b> Analysis of a two-factor design</a></li>
<li class="chapter" data-level="3.2.2" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#highwaySigns"><i class="fa fa-check"></i><b>3.2.2</b> Example with No Significant Interaction</a></li>
<li class="chapter" data-level="3.2.3" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#twoWayInteraction"><i class="fa fa-check"></i><b>3.2.3</b> Example with Significant Interaction</a></li>
<li class="chapter" data-level="3.2.4" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#twoFactorAsOneFactor"><i class="fa fa-check"></i><b>3.2.4</b> Two-factor reformulated as a One-Factor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html"><i class="fa fa-check"></i><b>4</b> Concepts of Advanced Designs</a>
<ul>
<li class="chapter" data-level="4.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#higher-order-factor-models"><i class="fa fa-check"></i><b>4.1</b> Higher order factor models</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#model-form-of-three-factor-design"><i class="fa fa-check"></i><b>4.1.1</b> Model Form of Three-factor design</a></li>
<li class="chapter" data-level="4.1.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#three-factor-anova-example"><i class="fa fa-check"></i><b>4.1.2</b> Three-factor ANOVA Example</a></li>
<li class="chapter" data-level="4.1.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#summarizing-higher-order-factors"><i class="fa fa-check"></i><b>4.1.3</b> Summarizing higher order factors</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#combining-blocks-and-factorial-models"><i class="fa fa-check"></i><b>4.2</b> Combining Blocks and Factorial Models</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#dentalPainExample"><i class="fa fa-check"></i><b>4.2.1</b> Two-factor with Block Example</a></li>
<li class="chapter" data-level="4.2.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#eda-for-two-factor-with-block"><i class="fa fa-check"></i><b>4.2.2</b> EDA for two-factor with block</a></li>
<li class="chapter" data-level="4.2.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#fitting-two-factor-with-block-model"><i class="fa fa-check"></i><b>4.2.3</b> Fitting two-factor with block model</a></li>
<li class="chapter" data-level="4.2.4" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#multiple-comparisons-3"><i class="fa fa-check"></i><b>4.2.4</b> Multiple comparisons</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#within-subject-designs"><i class="fa fa-check"></i><b>4.3</b> Within-subject designs</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#blocks-revisited-an-approach-to-handling-within-subjects-factors"><i class="fa fa-check"></i><b>4.3.1</b> Blocks revisited: an approach to handling within-subjects factors</a></li>
<li class="chapter" data-level="4.3.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#repeated-measures-case-study"><i class="fa fa-check"></i><b>4.3.2</b> Repeated Measures Case Study</a></li>
<li class="chapter" data-level="4.3.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#further-study"><i class="fa fa-check"></i><b>4.3.3</b> Further study</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html"><i class="fa fa-check"></i><b>5</b> Introduction to Multiple Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#regression-model"><i class="fa fa-check"></i><b>5.1</b> Regression Model</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>5.1.1</b> Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#fitting-a-regression-model"><i class="fa fa-check"></i><b>5.2</b> Fitting a regression model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#simple-linear-regression-example"><i class="fa fa-check"></i><b>5.2.1</b> Simple Linear Regression Example</a></li>
<li class="chapter" data-level="5.2.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#multiple-regression-example"><i class="fa fa-check"></i><b>5.2.2</b> Multiple Regression Example</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#interpreting-beta-parameter-estimates-in-mlr"><i class="fa fa-check"></i><b>5.3</b> Interpreting <span class="math inline">\(\beta\)</span>-parameter estimates in MLR</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#designed-experiments-1"><i class="fa fa-check"></i><b>5.3.1</b> Designed experiments</a></li>
<li class="chapter" data-level="5.3.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-orthogonal-design"><i class="fa fa-check"></i><b>5.3.2</b> Example of Orthogonal Design</a></li>
<li class="chapter" data-level="5.3.3" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#observational-studies-1"><i class="fa fa-check"></i><b>5.3.3</b> Observational studies</a></li>
<li class="chapter" data-level="5.3.4" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-observational-regression-interpretation"><i class="fa fa-check"></i><b>5.3.4</b> Example of observational regression interpretation</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#whymultiple"><i class="fa fa-check"></i><b>5.4</b> Why multiple regression?</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-spurious-correlation"><i class="fa fa-check"></i><b>5.4.1</b> Example of Spurious Correlation</a></li>
<li class="chapter" data-level="5.4.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-confounding-in-regression"><i class="fa fa-check"></i><b>5.4.2</b> Example of Confounding in Regression</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#concluding-the-multiple-regression-model"><i class="fa fa-check"></i><b>5.5</b> Concluding the Multiple Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regInferenceChp.html"><a href="regInferenceChp.html"><i class="fa fa-check"></i><b>6</b> Inference regarding Multiple Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#assumption-checking"><i class="fa fa-check"></i><b>6.1</b> Assumption checking</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-assumption-checking-in-slr"><i class="fa fa-check"></i><b>6.1.1</b> Example of Assumption Checking in SLR</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#overall-f-test-for-model-signifance"><i class="fa fa-check"></i><b>6.2</b> Overall <span class="math inline">\(F\)</span>-test for model signifance</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-model-overall-f-test"><i class="fa fa-check"></i><b>6.2.1</b> Example of model overall <span class="math inline">\(F\)</span>-test</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="regInferenceChp.html"><a href="regInferenceChp.html#individual-parameter-inference"><i class="fa fa-check"></i><b>6.3</b> Individual parameter inference</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#parameter-t-tests"><i class="fa fa-check"></i><b>6.3.1</b> Parameter <span class="math inline">\(t\)</span>-tests</a></li>
<li class="chapter" data-level="6.3.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-individual-parameter-t-test"><i class="fa fa-check"></i><b>6.3.2</b> Example of individual parameter <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="6.3.3" data-path="regInferenceChp.html"><a href="regInferenceChp.html#model-trimming"><i class="fa fa-check"></i><b>6.3.3</b> Model trimming</a></li>
<li class="chapter" data-level="6.3.4" data-path="regInferenceChp.html"><a href="regInferenceChp.html#confidence-intervals"><i class="fa fa-check"></i><b>6.3.4</b> Confidence Intervals</a></li>
<li class="chapter" data-level="6.3.5" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-individual-parameter-confidence-intervals"><i class="fa fa-check"></i><b>6.3.5</b> Example of individual parameter confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="regInferenceChp.html"><a href="regInferenceChp.html#confidence-and-prediction-bands"><i class="fa fa-check"></i><b>6.4</b> Confidence and prediction bands</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#simple-linear-regression-confident-and-prediction-bands"><i class="fa fa-check"></i><b>6.4.1</b> Simple Linear Regression Confident and Prediction bands</a></li>
<li class="chapter" data-level="6.4.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-confidence-and-prediction-intervals"><i class="fa fa-check"></i><b>6.4.2</b> Example of confidence and prediction intervals</a></li>
<li class="chapter" data-level="6.4.3" data-path="regInferenceChp.html"><a href="regInferenceChp.html#extrapolation-warning"><i class="fa fa-check"></i><b>6.4.3</b> Extrapolation warning!</a></li>
<li class="chapter" data-level="6.4.4" data-path="regInferenceChp.html"><a href="regInferenceChp.html#confidence-and-prediction-bands-in-multiple-regression"><i class="fa fa-check"></i><b>6.4.4</b> Confidence and Prediction Bands in Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="regInferenceChp.html"><a href="regInferenceChp.html#goodness-of-fit"><i class="fa fa-check"></i><b>6.5</b> Goodness-of-fit</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#coefficient-of-determination"><i class="fa fa-check"></i><b>6.5.1</b> Coefficient of determination</a></li>
<li class="chapter" data-level="6.5.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#akaikes-information-criterion"><i class="fa fa-check"></i><b>6.5.2</b> Akaike’s Information Criterion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html"><i class="fa fa-check"></i><b>7</b> More on multiple linear regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#model-comparision-reduced-f-tests"><i class="fa fa-check"></i><b>7.1</b> Model comparision – Reduced <span class="math inline">\(F\)</span>-tests</a></li>
<li class="chapter" data-level="7.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#categorical-predictor-variables"><i class="fa fa-check"></i><b>7.2</b> Categorical Predictor Variables</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#a-qualitative-predictor-with-two-levels"><i class="fa fa-check"></i><b>7.2.1</b> A qualitative predictor with two levels</a></li>
<li class="chapter" data-level="7.2.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#a-qualitative-predictor-with-more-than-two-levels"><i class="fa fa-check"></i><b>7.2.2</b> A qualitative predictor with more than two levels</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#bridging-regression-and-designed-experiments-ancova"><i class="fa fa-check"></i><b>7.3</b> Bridging Regression and Designed Experiments – ANCOVA</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#an-ancova-example-with-a-two-level-factor"><i class="fa fa-check"></i><b>7.3.1</b> An ANCOVA example with a two-level factor</a></li>
<li class="chapter" data-level="7.3.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#ancova-with-a-multi-level-factor"><i class="fa fa-check"></i><b>7.3.2</b> ANCOVA with a multi-level factor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="model-building-considerations.html"><a href="model-building-considerations.html"><i class="fa fa-check"></i><b>8</b> Model Building Considerations</a>
<ul>
<li class="chapter" data-level="8.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#regression-assumptions-revisited"><i class="fa fa-check"></i><b>8.1</b> Regression assumptions revisited</a></li>
<li class="chapter" data-level="8.2" data-path="model-building-considerations.html"><a href="model-building-considerations.html#violations-of-the-independence-assumption"><i class="fa fa-check"></i><b>8.2</b> Violations of the independence assumption</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#collecting-data-that-are-temporal-or-spatial-in-nature"><i class="fa fa-check"></i><b>8.2.1</b> Collecting data that are temporal or spatial in nature</a></li>
<li class="chapter" data-level="8.2.2" data-path="model-building-considerations.html"><a href="model-building-considerations.html#pseudoreplication"><i class="fa fa-check"></i><b>8.2.2</b> Pseudoreplication</a></li>
<li class="chapter" data-level="8.2.3" data-path="model-building-considerations.html"><a href="model-building-considerations.html#what-if-we-have-non-independent-errors"><i class="fa fa-check"></i><b>8.2.3</b> What if we have non-independent errors?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="model-building-considerations.html"><a href="model-building-considerations.html#constant-variance-violations"><i class="fa fa-check"></i><b>8.3</b> Constant Variance Violations</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#box-cox-power-tranformations"><i class="fa fa-check"></i><b>8.3.1</b> Box-Cox Power Tranformations</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="model-building-considerations.html"><a href="model-building-considerations.html#normality-violations"><i class="fa fa-check"></i><b>8.4</b> Normality violations</a></li>
<li class="chapter" data-level="8.5" data-path="model-building-considerations.html"><a href="model-building-considerations.html#violations-of-the-linearity-assumption"><i class="fa fa-check"></i><b>8.5</b> Violations of the linearity assumption</a></li>
<li class="chapter" data-level="8.6" data-path="model-building-considerations.html"><a href="model-building-considerations.html#detecting-and-dealing-with-unusual-observations"><i class="fa fa-check"></i><b>8.6</b> Detecting and dealing with unusual observations</a></li>
<li class="chapter" data-level="8.7" data-path="model-building-considerations.html"><a href="model-building-considerations.html#multicollinearity"><i class="fa fa-check"></i><b>8.7</b> Multicollinearity</a></li>
<li class="chapter" data-level="8.8" data-path="model-building-considerations.html"><a href="model-building-considerations.html#standardizingPredictors"><i class="fa fa-check"></i><b>8.8</b> Scale changes</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>9</b> Model Selection</a>
<ul>
<li class="chapter" data-level="9.1" data-path="model-selection.html"><a href="model-selection.html#stepwise-procedures"><i class="fa fa-check"></i><b>9.1</b> Stepwise Procedures</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="model-selection.html"><a href="model-selection.html#backward-selection"><i class="fa fa-check"></i><b>9.1.1</b> Backward Selection</a></li>
<li class="chapter" data-level="9.1.2" data-path="model-selection.html"><a href="model-selection.html#forward-selection"><i class="fa fa-check"></i><b>9.1.2</b> Forward selection</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="model-selection.html"><a href="model-selection.html#best-subsets"><i class="fa fa-check"></i><b>9.2</b> Best subsets</a></li>
<li class="chapter" data-level="9.3" data-path="model-selection.html"><a href="model-selection.html#shrinkage-methods"><i class="fa fa-check"></i><b>9.3</b> Shrinkage Methods</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="model-validation.html"><a href="model-validation.html"><i class="fa fa-check"></i><b>10</b> Model Validation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="model-validation.html"><a href="model-validation.html#underfitting-vs.-overfitting-models"><i class="fa fa-check"></i><b>10.1</b> Underfitting vs. Overfitting Models</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="model-validation.html"><a href="model-validation.html#the-bias-variance-trade-off"><i class="fa fa-check"></i><b>10.1.1</b> The Bias-Variance Trade-off</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="model-validation.html"><a href="model-validation.html#validation-techniques"><i class="fa fa-check"></i><b>10.2</b> Validation Techniques</a></li>
<li class="chapter" data-level="10.3" data-path="model-validation.html"><a href="model-validation.html#basic-validation-with-a-single-holdout-sample"><i class="fa fa-check"></i><b>10.3</b> Basic Validation with a single holdout sample</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="model-validation.html"><a href="model-validation.html#use-the-training-data-to-fit-and-select-models"><i class="fa fa-check"></i><b>10.3.1</b> Use the training data to fit and select models</a></li>
<li class="chapter" data-level="10.3.2" data-path="model-validation.html"><a href="model-validation.html#model-training"><i class="fa fa-check"></i><b>10.3.2</b> Model training:</a></li>
<li class="chapter" data-level="10.3.3" data-path="model-validation.html"><a href="model-validation.html#model-validation-step"><i class="fa fa-check"></i><b>10.3.3</b> Model validation step:</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="model-validation.html"><a href="model-validation.html#hold-out-sample-validation-using-caret"><i class="fa fa-check"></i><b>10.4</b> Hold-out sample validation using <code>caret</code></a></li>
<li class="chapter" data-level="10.5" data-path="model-validation.html"><a href="model-validation.html#leave-one-out-cross-validation-loocv"><i class="fa fa-check"></i><b>10.5</b> “Leave one out” Cross-Validation (LOOCV)</a></li>
<li class="chapter" data-level="10.6" data-path="model-validation.html"><a href="model-validation.html#k-fold-cross-validation"><i class="fa fa-check"></i><b>10.6</b> <span class="math inline">\(k\)</span>-fold Cross-Validation</a></li>
<li class="chapter" data-level="10.7" data-path="model-validation.html"><a href="model-validation.html#a-final-note"><i class="fa fa-check"></i><b>10.7</b> A final note</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="statistical-odds.html"><a href="statistical-odds.html"><i class="fa fa-check"></i><b>11</b> Statistical Odds</a>
<ul>
<li class="chapter" data-level="11.1" data-path="statistical-odds.html"><a href="statistical-odds.html#probability-versus-odds"><i class="fa fa-check"></i><b>11.1</b> Probability versus Odds</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="statistical-odds.html"><a href="statistical-odds.html#relationship-between-odds-and-probability"><i class="fa fa-check"></i><b>11.1.1</b> Relationship between Odds and Probability</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="statistical-odds.html"><a href="statistical-odds.html#odds-ratios"><i class="fa fa-check"></i><b>11.2</b> Odds ratios</a></li>
<li class="chapter" data-level="11.3" data-path="statistical-odds.html"><a href="statistical-odds.html#ideas-of-modeling-odds"><i class="fa fa-check"></i><b>11.3</b> Ideas of modeling odds</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-model"><i class="fa fa-check"></i><b>12.1</b> Logistic Model</a></li>
<li class="chapter" data-level="12.2" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-interpreting-and-assessing-a-logistic-model"><i class="fa fa-check"></i><b>12.2</b> Fitting, Interpreting and assessing a logistic model</a></li>
<li class="chapter" data-level="12.3" data-path="logistic-regression.html"><a href="logistic-regression.html#case-study---titanic-dataset"><i class="fa fa-check"></i><b>12.3</b> Case Study - Titanic Dataset</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>13</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="13.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>13.1</b> Poisson Regression</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-distribution"><i class="fa fa-check"></i><b>13.1.1</b> Poisson distribution</a></li>
<li class="chapter" data-level="13.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression-development"><i class="fa fa-check"></i><b>13.1.2</b> Poisson Regression Development</a></li>
<li class="chapter" data-level="13.1.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#example---tropical-cyclone-counts-in-the-north-atlantic"><i class="fa fa-check"></i><b>13.1.3</b> Example - Tropical Cyclone Counts in the North Atlantic</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#handling-overdispersion"><i class="fa fa-check"></i><b>13.2</b> Handling overdispersion</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#example-attendnace-records"><i class="fa fa-check"></i><b>13.2.1</b> Example – Attendnace Records</a></li>
<li class="chapter" data-level="13.2.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#incorrect-poisson-model"><i class="fa fa-check"></i><b>13.2.2</b> Incorrect Poisson Model</a></li>
<li class="chapter" data-level="13.2.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#a-quasi-poisson-approach"><i class="fa fa-check"></i><b>13.2.3</b> A quasi-Poisson approach</a></li>
<li class="chapter" data-level="13.2.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#fitting-a-negative-binomial-regression"><i class="fa fa-check"></i><b>13.2.4</b> Fitting a Negative Binomial regression</a></li>
<li class="chapter" data-level="13.2.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#picking-between-quasi-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>13.2.5</b> Picking between Quasi-Poisson and Negative Binomial</a></li>
<li class="chapter" data-level="13.2.6" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#infererence-on-predictor-variables"><i class="fa fa-check"></i><b>13.2.6</b> Infererence on predictor variables</a></li>
<li class="chapter" data-level="13.2.7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#plotting-fitted-model"><i class="fa fa-check"></i><b>13.2.7</b> Plotting fitted model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="concepts-of-advanced-designs" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Concepts of Advanced Designs<a href="concepts-of-advanced-designs.html#concepts-of-advanced-designs" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The previous chapters have established the groundwork of experimental design.
We discussed the key elements of experimental units, factors, response variables, treatments, confounding influences and the purpose of replication and randomization.
We saw blocking, multiple factors and interactions in various examples.
This former work just scratches the surface of the field of experimental design and the analyses associated with those designs.
This chapter attempts to open the door to more advanced designs and to build an appreciation for how complex designs can be.
The objective of this chapter includes:</p>
<ul>
<li>Understanding the basic structure of factorial designs.</li>
<li>Mixing blocking and factorial components in a design.</li>
<li>Understanding the basic structure of within-subject designs.</li>
<li><strong>Building an appreciation</strong> for the complexity of experimental design.</li>
</ul>
<div id="higher-order-factor-models" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Higher order factor models<a href="concepts-of-advanced-designs.html#higher-order-factor-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous two chapters we have seen a One-Way and Two-Way ANOVA designs.
In the former, a single factor consisted of <span class="math inline">\(k\)</span>-levels (and thus <span class="math inline">\(k\)</span>-treatments) while in the latter the first factor may consist of <span class="math inline">\(k\)</span> levels and the second factor <span class="math inline">\(j\)</span> levels (and therefore <span class="math inline">\(k\times j\)</span> treatments).
This idea can, of course, be expanded to even more terms.
Consider the following example.</p>
<div id="model-form-of-three-factor-design" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> Model Form of Three-factor design<a href="concepts-of-advanced-designs.html#model-form-of-three-factor-design" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To develop and appreciate a higher order factor model, we consider the following example of a three-factor design.</p>
<p><strong>Example.</strong> Marketing research contractors (<span class="citation">Kutner et al. (<a href="#ref-KutnerText">2004</a>)</span>).</p>
<p>A marketing research consultant evaluated the effects of fee schedule, scope of work and type of supervisory control on the quality of work performed under contracts by independent marketing research agencies.
The design of this experiment can be summarized as follows</p>
<p><span class="math display">\[\begin{array}{ll}
\textbf{Factor} &amp; \textbf{Factor Levels} \\
\hline
\textrm{Fee level} &amp; \textrm{High} \\
&amp; \textrm{Average} \\
&amp; \textrm{Low}\\
\hline
\textrm{Scope} &amp; \textrm{In house} \\
&amp; \textrm{Subcontracted} \\
\hline
\textrm{Supervision} &amp; \textrm{Local Supervisors}\\
&amp; \textrm{Traveling Supervisors} \\
\end{array}\]</span></p>
<p>The quality of work performed was measured by an index taking into account several characteristics of quality.</p>
<p>There are <strong>three factors</strong> in this experiment, with 3, 2 and 2 levels for each factor.
So the number of treatments is <span class="math inline">\(3\times 2\times 2 = 12\)</span> and can be summarized in the following table.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="4">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Supervision
</div>
</th>
</tr>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Local Supervisers
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Traveling Supervisors
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Fee Level
</th>
<th style="text-align:left;">
In house
</th>
<th style="text-align:left;">
Subcontracted
</th>
<th style="text-align:left;">
In house
</th>
<th style="text-align:left;">
Subcontracted
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
High
</td>
<td style="text-align:left;">
Treatment 1
</td>
<td style="text-align:left;">
Treatment 2
</td>
<td style="text-align:left;">
Treatment 3
</td>
<td style="text-align:left;">
Treatment 4
</td>
</tr>
<tr>
<td style="text-align:left;">
Average
</td>
<td style="text-align:left;">
Treatment 5
</td>
<td style="text-align:left;">
Treatment 6
</td>
<td style="text-align:left;">
Treatment 7
</td>
<td style="text-align:left;">
Treatment 8
</td>
</tr>
<tr>
<td style="text-align:left;">
Low
</td>
<td style="text-align:left;">
Treatment 9
</td>
<td style="text-align:left;">
Treatment 10
</td>
<td style="text-align:left;">
Treatment 11
</td>
<td style="text-align:left;">
Treatment 12
</td>
</tr>
</tbody>
</table>
<p>Recall a main idea from two-factor experiments – the interaction terms are typically very important.
In this three factor design we have the three main effects (Fee level, Scope and Supervision) but also have pairwise interactions between these variables (<em>e.g.</em>, the interaction of fee level and scope) and an interaction among all three.
From a statistical modeling perspective, we are now fitting the model</p>
<p><span class="math display" id="eq:threeFactorModel">\[\begin{equation}
Y_{ijkm} = \mu + \alpha_i + \beta_j + \gamma_k + (\alpha\beta)_{ij} + (\alpha\gamma)_{ik} + (\beta\gamma)_{jk} + (\alpha\beta\gamma)_{ijk} + \varepsilon_{ijkm}
\tag{4.1}
\end{equation}\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(Y_{ijkm}\)</span> is the <span class="math inline">\(m^\mathrm{th}\)</span> observation in the <span class="math inline">\(i^\mathrm{th}\)</span> level of the first factor, the <span class="math inline">\(j^\mathrm{th}\)</span> level of the second factor and the <span class="math inline">\(k^\mathrm{th}\)</span> level of the third factor.</li>
<li><span class="math inline">\(\mu\)</span> is an overall mean.</li>
<li>Fee level main effect <span class="math inline">\(\alpha_i\)</span> for <span class="math inline">\(i=1,2,3\)</span> corresponding to the three fee levels.</li>
<li>Scope main effect <span class="math inline">\(\beta_j\)</span> for <span class="math inline">\(j=1,2\)</span> corresponding to the two sope levels.</li>
<li>Supervision main effect <span class="math inline">\(\gamma_k\)</span> for <span class="math inline">\(k=1,2\)</span> for the two supervision levels.</li>
<li>Fee level and Scope interaction effect <span class="math inline">\((\alpha\beta)_{ij}\)</span>.</li>
<li>Fee level and Supervision interaction effect <span class="math inline">\((\alpha\gamma)_{ik}\)</span>.</li>
<li>Scope and Supervision interaction effect <span class="math inline">\((\beta\gamma)_{jk}\)</span>.</li>
<li>Fee level, Scope and Supervision interaction effect <span class="math inline">\((\alpha\beta\gamma)_{ijk}\)</span>.</li>
<li><span class="math inline">\(\varepsilon_{ijkm}\)</span> is the random error term.</li>
</ul>
<p>As you can see this model has grown greatly compared to to the two-way ANOVA examples from before.</p>
<p><strong>What will happen if there are four factors?</strong></p>
<p>In general, if an experiment consisted of <span class="math inline">\(m\)</span> different factors, we would potentially have <span class="math inline">\(2^m - 1\)</span> terms in our model.
Thus with four factors you are looking at <span class="math inline">\(2^4 - 1 = 16-1=15\)</span> terms in your ANOVA decomposition.
With five factors, 31 terms.
This will quickly grow out of control.
We will run out of Greek letters before long!</p>
<p>Fortunately, for higher order factor problems there are statisticians available to help formulate a better design and potentially <em>optimize</em> some of the variables of study.
We leave out the details of these topics in this text but want to provide insight into these designs and the analyses that can be done.
Please consult a statistician before your experiment if you are planning a complex design!!</p>
</div>
<div id="three-factor-anova-example" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Three-factor ANOVA Example<a href="concepts-of-advanced-designs.html#three-factor-anova-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Example continued.</strong> Below we complete the analysis involving the marketing research contractors with the data available in the <code>marketingResearch.txt</code> file on the book data repository.</p>
<p>First we read in the data and make sure R properly treats the factor variables.
From (<span class="citation">Kutner et al. (<a href="#ref-KutnerText">2004</a>)</span>) we have three fee levels corresponding as 1=High, 2=Average, 3=Low.
The two scope levels are 1=all work in-house, 2=subcontracted, and the two supervision levels are 1=local supervisors, 2=traveling supervisors.</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="concepts-of-advanced-designs.html#cb225-1" tabindex="-1"></a>data_site <span class="ot">&lt;-</span> <span class="st">&quot;https://tjfisher19.github.io/introStatModeling/data/marketingResearch.txt&quot;</span></span>
<span id="cb225-2"><a href="concepts-of-advanced-designs.html#cb225-2" tabindex="-1"></a>marketing <span class="ot">&lt;-</span> <span class="fu">read_table</span>(data_site)</span>
<span id="cb225-3"><a href="concepts-of-advanced-designs.html#cb225-3" tabindex="-1"></a><span class="fu">glimpse</span>(marketing)</span></code></pre></div>
<pre><code>## Rows: 48
## Columns: 5
## $ Quality     &lt;dbl&gt; 124.3, 120.6, 120.7, 122.6, 112.7, 110.2, 113.5, 108.6, 11…
## $ Fee         &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2…
## $ Scope       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1…
## $ Supervision &lt;dbl&gt; 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1…
## $ Replicate   &lt;dbl&gt; 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4…</code></pre>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="concepts-of-advanced-designs.html#cb227-1" tabindex="-1"></a>marketing <span class="ot">&lt;-</span> marketing <span class="sc">|&gt;</span></span>
<span id="cb227-2"><a href="concepts-of-advanced-designs.html#cb227-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Fee =</span> <span class="fu">factor</span>(Fee, <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,</span>
<span id="cb227-3"><a href="concepts-of-advanced-designs.html#cb227-3" tabindex="-1"></a>                      <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;High&quot;</span>, <span class="st">&quot;Average&quot;</span>, <span class="st">&quot;Low&quot;</span>)),</span>
<span id="cb227-4"><a href="concepts-of-advanced-designs.html#cb227-4" tabindex="-1"></a>         <span class="at">Scope =</span> <span class="fu">factor</span>(Scope, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,</span>
<span id="cb227-5"><a href="concepts-of-advanced-designs.html#cb227-5" tabindex="-1"></a>                        <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;In-house&quot;</span>, <span class="st">&quot;Subcontracted&quot;</span>)),</span>
<span id="cb227-6"><a href="concepts-of-advanced-designs.html#cb227-6" tabindex="-1"></a>         <span class="at">Supervision =</span> <span class="fu">factor</span>(Supervision, <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,</span>
<span id="cb227-7"><a href="concepts-of-advanced-designs.html#cb227-7" tabindex="-1"></a>                              <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Local&quot;</span>, <span class="st">&quot;Traveling&quot;</span>) ) )</span></code></pre></div>
<div id="eda-for-three-factors" class="section level4 hasAnchor" number="4.1.2.1">
<h4><span class="header-section-number">4.1.2.1</span> EDA for three-factors<a href="concepts-of-advanced-designs.html#eda-for-three-factors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We have replication within each treatment – in the context of (<a href="concepts-of-advanced-designs.html#eq:threeFactorModel">(4.1)</a>, <span class="math inline">\(m=4\)</span> replicates for each of the <span class="math inline">\(3\times 2\times 2 = 12\)</span> unique treatments for <span class="math inline">\(n=48\)</span> total observations.
Any EDA needs to account for the 12 unique treatments over the 3 different factor variables.
Below we make a visual summarizing the mean response for each unique treatment, linking all profiles together for both supervision and scope – these two variables were chosen as each factor has only two unique values and this limits the number of colors and linetypes needed in the plot (generally fewer visual attributes is preferred).</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="concepts-of-advanced-designs.html#cb228-1" tabindex="-1"></a><span class="fu">ggplot</span>(marketing, <span class="fu">aes</span>(<span class="at">x=</span>Fee, <span class="at">y=</span>Quality, <span class="at">color=</span>Scope, <span class="at">linetype=</span>Supervision,</span>
<span id="cb228-2"><a href="concepts-of-advanced-designs.html#cb228-2" tabindex="-1"></a>                      <span class="at">group=</span><span class="fu">interaction</span>(Scope, Supervision)) ) <span class="sc">+</span> </span>
<span id="cb228-3"><a href="concepts-of-advanced-designs.html#cb228-3" tabindex="-1"></a>    <span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;point&quot;</span>) <span class="sc">+</span> </span>
<span id="cb228-4"><a href="concepts-of-advanced-designs.html#cb228-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;line&quot;</span>) <span class="sc">+</span></span>
<span id="cb228-5"><a href="concepts-of-advanced-designs.html#cb228-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4marketingEDA"></span>
<img src="introStatModeling_files/figure-html/ch4marketingEDA-1.png" alt="Interaction plot for the 3-factor experiment looking at consulting quality as a function of fee, scope and supervision." width="60%" />
<p class="caption">
Figure 4.1: Interaction plot for the 3-factor experiment looking at consulting quality as a function of fee, scope and supervision.
</p>
</div>
<p>From Figure <a href="concepts-of-advanced-designs.html#fig:ch4marketingEDA">4.1</a> it appears the High and Average fee types have the highest quality regardless of scope &amp; supervision.
We also see that the Fee type may not interact with the Scope and Supervision variables as all four lines look reasonably parallel.
The connection between Scope and Supervision is more complex; note the alternating colors when looking at the lines while the linetypes do not alternate in the same way.
This may be an indication of some sort of interaction between these two variables.</p>
</div>
<div id="fitting-a-three-factor-model" class="section level4 hasAnchor" number="4.1.2.2">
<h4><span class="header-section-number">4.1.2.2</span> Fitting a three-factor model<a href="concepts-of-advanced-designs.html#fitting-a-three-factor-model" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We fit the three-way ANOVA model.
Here we used the notation <code>Fee*Scope*Supervision</code> so R will fit a full factorial model (<em>that is</em>, all main effects and interaction terms).</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="concepts-of-advanced-designs.html#cb229-1" tabindex="-1"></a>marketing.anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Quality <span class="sc">~</span> Fee<span class="sc">*</span>Scope<span class="sc">*</span>Supervision, <span class="at">data=</span>marketing)</span>
<span id="cb229-2"><a href="concepts-of-advanced-designs.html#cb229-2" tabindex="-1"></a><span class="fu">autoplot</span>(marketing.anova)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4marketingANOVA"></span>
<img src="introStatModeling_files/figure-html/ch4marketingANOVA-1.png" alt="Residual plots for the Three-Way ANOVA studying the twelve unique treatments on the quality of consultants - Top-left a Residuals vs Fitted Plot; Top-right a Normal Q-Q plot of the residuals; Bottom-left the Scale-Location plot; and Bottom-right a Residuals vs Leverage plot." width="70%" />
<p class="caption">
Figure 4.2: Residual plots for the Three-Way ANOVA studying the twelve unique treatments on the quality of consultants - Top-left a Residuals vs Fitted Plot; Top-right a Normal Q-Q plot of the residuals; Bottom-left the Scale-Location plot; and Bottom-right a Residuals vs Leverage plot.
</p>
</div>
<p>The residual plot in <a href="concepts-of-advanced-designs.html#fig:ch4marketingANOVA">4.2</a> shows that the constant variance assumption is generally met (no concerning patterns in either the Residuals vs Fitted or Scale-Location plot).
The Normal Q-Q plot does show some deviation from the 45-degree line but here we must make note of how it deviates.</p>
<ul>
<li>We see deviation in both tails</li>
<li>The <em>observed</em> or <em>sample</em> residuals generally have smaller <span class="math inline">\(Z\)</span>-scores than is expected (all in the <span class="math inline">\((-2,2)\)</span> range), this indicates the data is <em>light tailed</em> (less data in the extremes of the distribution).</li>
<li>The two points above tells us the deviations are light tailed and symmetric (that is, roughly equally distributed in both tails).</li>
</ul>
<p>Given we have no skewness and the data is light tailed, the central limit theorem can justify the use of ANOVA in this setting.
That is, even if the residuals are not exactly normally distributed, the sample size is adequate to provide some justification to the result.</p>
<p>Now look at the ANOVA output.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="concepts-of-advanced-designs.html#cb230-1" tabindex="-1"></a><span class="fu">summary</span>(marketing.anova)</span></code></pre></div>
<pre><code>##                       Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## Fee                    2  10044    5022  679.34 &lt; 2e-16 ***
## Scope                  1   1834    1834  248.08 &lt; 2e-16 ***
## Supervision            1   3832    3832  518.40 &lt; 2e-16 ***
## Fee:Scope              2      2       1    0.11    0.90    
## Fee:Supervision        2      1       0    0.05    0.95    
## Scope:Supervision      1    575     575   77.75 1.6e-10 ***
## Fee:Scope:Supervision  2      4       2    0.27    0.77    
## Residuals             36    266       7                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Similar to the two-factor analysis, <strong>always look at the most complex interaction term first.</strong>
Here the most complex term is the <code>Fee:Scope:Superversion</code> term.
That three factor interaction term is not significant (<span class="math inline">\(F\)</span>-statistic of 0.267 on 2 and 36 degrees of freedom, <span class="math inline">\(p\)</span>-value=0.767), thus we can proceed to the pairwise interactions.</p>
<ul>
<li>The interaction between Scope and Supervision is significant (<span class="math inline">\(F\)</span>-stat of 77.749 on 1 and 36 degrees of freedom, <span class="math inline">\(p\)</span>-value<span class="math inline">\(\approx 10^{-10}\)</span>).
<ul>
<li>Thus, we cannot make meaningful inference on the main effects of scope and supervision.</li>
</ul></li>
<li>Both interaction terms involving the Fee level factor are not significant
<ul>
<li>The <code>Fee:Scope</code> term is not significant (<span class="math inline">\(F\)</span>-stat of 0.108 on 2 and 36 degrees of freedom, <span class="math inline">\(p\)</span>-value=0.898)</li>
<li>The <code>Fee:Supervision</code> term is not significant (<span class="math inline">\(F\)</span>-stat of 0.053 on 2 and 36 degrees of freedom, <span class="math inline">\(p\)</span>-value=0.948),</li>
</ul></li>
</ul>
<p>Since the interaction of the Fee variable with any other factor variable does not appear to significantly influence the response, we can analyze the main effect of the Fee variable.
The Fee main effect influences the quality (<span class="math inline">\(F\)</span>-stat of 679.336 on 2 and 36 degrees of freedom, <span class="math inline">\(p\)</span>-value<span class="math inline">\(\approx10^{-16}\)</span>).</p>
<p>Overall, we can conclude that some combination of Scope and Supervision influence quality.
We also conclude that the different Fee types appear to influence Quality.</p>
</div>
<div id="multiple-comparisons-2" class="section level4 hasAnchor" number="4.1.2.3">
<h4><span class="header-section-number">4.1.2.3</span> Multiple comparisons<a href="concepts-of-advanced-designs.html#multiple-comparisons-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In general, multiple comparisons analysis can get very complicated when three or more factors are involved.
In this case, we get lucky</p>
<ul>
<li><code>Fee</code> is significant, but <em>only</em> as a main effect.</li>
<li>The <code>Scope</code> &amp; <code>Supervision</code> interaction term is significant, but that interaction term only involves 2 variables and we covered that analysis in section <a href="multiple-factor-designed-experiments.html#twoWayInteraction">3.2.3</a>.
<ul>
<li>Further, there are only <span class="math inline">\(2\times 2=4\)</span> unique combinations of those four.</li>
</ul></li>
</ul>
<p>First we consider the effects of Fee on the quality index</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="concepts-of-advanced-designs.html#cb232-1" tabindex="-1"></a>marketing.mc.fee <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(marketing.anova, <span class="sc">~</span>Fee)</span></code></pre></div>
<pre><code>## NOTE: Results may be misleading due to involvement in interactions</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="concepts-of-advanced-designs.html#cb234-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(marketing.mc.fee, <span class="st">&quot;tukey&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4markingFeeMC"></span>
<img src="introStatModeling_files/figure-html/ch4markingFeeMC-1.png" alt="Tukey HSD comparison of three levels of the Fee variable on consultant quality. The Low fee option results in a lower quality than High or Average, which statistically are equivalent." width="60%" />
<p class="caption">
Figure 4.3: Tukey HSD comparison of three levels of the Fee variable on consultant quality. The Low fee option results in a lower quality than High or Average, which statistically are equivalent.
</p>
</div>
<p>Figure <a href="concepts-of-advanced-designs.html#fig:ch4markingFeeMC">4.3</a> provides intervals for pairwise comparisons of the fee levels, so we look for the inclusion or exclusion of the value zero. We see that the “Low” fee level is statistically different than both “High” and “Average”, while the later two are not statistically different.</p>
<p>To analyze the Scope &amp; Supervision influence on Quality we must do so conditionally.
This can be achieved by using the conditional comparisons we saw in Chapter 2, section <a href="multiple-factor-designed-experiments.html#twoWayInteraction">3.2.3</a>.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="concepts-of-advanced-designs.html#cb235-1" tabindex="-1"></a>marketing.mc.scope <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(marketing.anova, <span class="sc">~</span>Scope<span class="sc">|</span>Supervision)</span></code></pre></div>
<pre><code>## NOTE: Results may be misleading due to involvement in interactions</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="concepts-of-advanced-designs.html#cb237-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(marketing.mc.scope, <span class="st">&quot;tukey&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4markingScopeSupervsionMC"></span>
<img src="introStatModeling_files/figure-html/ch4markingScopeSupervsionMC-1.png" alt="Tukey HSD comparison of two levels of the Scope variable on consultant quality conditioned on Supervision. In both settings of supervision, the In-house scope results in a higher quality than subcontracted. It also appears this difference is greater when Traveling Supervision is used." width="60%" />
<p class="caption">
Figure 4.4: Tukey HSD comparison of two levels of the Scope variable on consultant quality conditioned on Supervision. In both settings of supervision, the In-house scope results in a higher quality than subcontracted. It also appears this difference is greater when Traveling Supervision is used.
</p>
</div>
<p>Figure <a href="concepts-of-advanced-designs.html#fig:ch4markingScopeSupervsionMC">4.4</a> provides interval comparisons for the scope variable within each supervision level. Note that since there are only 2 levels within scope, a single comparison is made within each supervision level (also only two).
Since neither interval contains the value zero it is clear that the is a difference between the in-house and subcontracted scope values.
Furthermore, we see that the supervision term influences these results as the difference is greater for Traveling supervision.</p>
</div>
<div id="reformulated-for-multiple-comparisons" class="section level4 hasAnchor" number="4.1.2.4">
<h4><span class="header-section-number">4.1.2.4</span> Reformulated for multiple comparisons<a href="concepts-of-advanced-designs.html#reformulated-for-multiple-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Figure <a href="concepts-of-advanced-designs.html#fig:ch4markingScopeSupervsionMC">4.4</a> provides the comparison of the Scope variable conditioned on the Supervisor variable.
Each of those factor variables has 2 levels and there are <span class="math inline">\(2\times 2=4\)</span> total treatments.
If you wished to compare all 4 of those treatments levels, you can use can use the ideas of Section <a href="multiple-factor-designed-experiments.html#twoFactorAsOneFactor">3.2.4</a> and reformulate the model by combining some factor variables.
We start by creating a new variable that combines the Scope and Supervision variables</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="concepts-of-advanced-designs.html#cb238-1" tabindex="-1"></a>marketing <span class="ot">&lt;-</span> marketing <span class="sc">|&gt;</span> </span>
<span id="cb238-2"><a href="concepts-of-advanced-designs.html#cb238-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ScopeSupervision =</span> <span class="fu">paste</span>(Scope, Supervision))</span>
<span id="cb238-3"><a href="concepts-of-advanced-designs.html#cb238-3" tabindex="-1"></a><span class="fu">unique</span>(marketing<span class="sc">$</span>ScopeSupervision)</span></code></pre></div>
<pre><code>## [1] &quot;In-house Local&quot;          &quot;In-house Traveling&quot;     
## [3] &quot;Subcontracted Local&quot;     &quot;Subcontracted Traveling&quot;</code></pre>
<p>Similar to the methods in section <a href="multiple-factor-designed-experiments.html#twoFactorAsOneFactor">3.2.4</a>, the code above creates a new variable called <code>ScopeSupervision</code> that is the two factor variables, <code>Scope</code> and <code>Supervision</code> pasted together resulting in the four unique treatments of those variables.</p>
<p>We can then refit the model using this alternative formulation.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="concepts-of-advanced-designs.html#cb240-1" tabindex="-1"></a>marketing.anova.alt <span class="ot">&lt;-</span> <span class="fu">aov</span>(Quality <span class="sc">~</span> Fee<span class="sc">*</span>ScopeSupervision, <span class="at">data=</span>marketing)</span></code></pre></div>
<p>We take a moment to highlight that this ANOVA table encompasses the previous results.
All values on the <code>Residuals</code> row matches, the main effects on <code>Fee</code> match the previous result.
Now, the <code>ScopeSupervision</code> row is the <em>main effect</em> of the two conjoined variables - note that the degrees of freedom for <code>Scope</code>, <code>Supervsion</code> and <code>Scope:Supervision</code> in the previous result were each 1, and sum to 3; the <code>Sum Sq</code> for each of those three terms sums to new value <span class="math inline">\(6241\)</span>.
The interaction term is not significant which matches our previous result that the effects of <code>Fee</code> on quality did not interact with either the <code>Scope</code> or <code>Supervision</code> variables.</p>
<p>We can proceed with a multiple comparison all 4 unique treatments involving Scope and Supervision in Figure <a href="concepts-of-advanced-designs.html#fig:ch4markingAltScopeSupervsionMC">4.5</a>.
We tell <code>emmeans()</code> to conduct a Tukey test on all pairwise comparisons.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="concepts-of-advanced-designs.html#cb241-1" tabindex="-1"></a>marketing.mc.scope <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(marketing.anova.alt, <span class="sc">~</span>ScopeSupervision)</span></code></pre></div>
<pre><code>## NOTE: Results may be misleading due to involvement in interactions</code></pre>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="concepts-of-advanced-designs.html#cb243-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(marketing.mc.scope, <span class="st">&quot;tukey&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4markingAltScopeSupervsionMC"></span>
<img src="introStatModeling_files/figure-html/ch4markingAltScopeSupervsionMC-1.png" alt="Tukey HSD comparison of four unique treatments corresponding to the two levels of the Scope variable and two levels of the Supervision variable. Here we see that all unique treatments result in a different quality level. This is consistent with the findings above." width="60%" />
<p class="caption">
Figure 4.5: Tukey HSD comparison of four unique treatments corresponding to the two levels of the Scope variable and two levels of the Supervision variable. Here we see that all unique treatments result in a different quality level. This is consistent with the findings above.
</p>
</div>
<p>Figure <a href="concepts-of-advanced-designs.html#fig:ch4markingAltScopeSupervsionMC">4.5</a> shows that all four treatments for Scope and Supervision result in different quality values.
The greatest difference is the In-house scope with Local Supervision compared to the Subcontracted Traveling Supervision.
This is consistent with the conditional results which showed the difference between in-house and subcontracted depended on the supervision variable.
With this formulation of the model, we can gain some further insight into these differences.</p>
</div>
</div>
<div id="summarizing-higher-order-factors" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Summarizing higher order factors<a href="concepts-of-advanced-designs.html#summarizing-higher-order-factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The example above provides a illustration of a higher order factorial model and the complexities involved in its analysis.
If you come across a design this complex, it is recommended you work with a statistician as most have been trained in the analysis of designed experiments.
But if you must, a few key things to remember:</p>
<ul>
<li>Always start with the most complex interaction term in the model.</li>
<li>When interaction terms are not significant, you can work down to lower order interactions and the main effects.</li>
<li>Multiple comparisons involving interactions must be done conditionally or with a reformulated model.</li>
</ul>
</div>
</div>
<div id="combining-blocks-and-factorial-models" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Combining Blocks and Factorial Models<a href="concepts-of-advanced-designs.html#combining-blocks-and-factorial-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the previous chapter we introduced multiple inputs into a model, one of which could be a <em>block</em> term.
Coupled with the three factor example above, it should seem fairly straightforward to combine the ideas of blocking and factorial design into a single model.
Below we provide an example of a two-factor design that also includes a block term.</p>
<div id="dentalPainExample" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Two-factor with Block Example<a href="concepts-of-advanced-designs.html#dentalPainExample" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Example.</strong> Dental Pain treatments (<span class="citation">Kutner et al. (<a href="#ref-KutnerText">2004</a>)</span>).</p>
<p>An anesthesiologist conducted a comparative study of the effects of acupuncture and codeine on postoperative dental pain in male subjects.
For acupuncture, patients were provide two <em>inactive</em> acupuncture points or two active acupuncture points.
For the codeine treatments, patients were provided with a sugar pill or a codeine capsule.
Thirty-two patients were grouped into eight groups according to an initial evaluation of their level of pain tolerance as part of this study.
Subjects in each group were then randomly assigned to one of the four unique treatments and a pain relief score was recorded for all subjects two hours after the initial treatment where the higher the value the more effective the treatment.</p>
<p>Original Data Source: <span class="citation">Sung et al. (<a href="#ref-Sung1977">1977</a>)</span></p>
<p>Before we conduct the analysis we take a moment to recap some of the design features in this study.
Here, we have two factor variables, each with two levels, so there are <span class="math inline">\(2\times 2=4\)</span> treatments.
Furthermore, the level of pain tolerance can be considered a confounding effect to the study, but the the experimenter has put patients into groups, or <em>blocks</em>, with similar pain tolerances.
Thus, we have a <span class="math inline">\(2\times 2\)</span> with a block term experiment.</p>
<p>The data are provided in the file <code>dentalPain.csv</code> in the textbook repository.
In that file, everything is coded numerically:</p>
<ul>
<li>The acupuncture variable is recorded as 1 and 2 in the data file for <em>inactive</em> and <em>active</em> acupuncture points, respectively.</li>
<li>The codeine variable is recorded as 1 and 2 for sugar pill and codeine capsule, respectively.</li>
<li>The block term, level of pain tolerance, is recorded numerically <span class="math inline">\(1,\ldots,8\)</span>.</li>
</ul>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="concepts-of-advanced-designs.html#cb244-1" tabindex="-1"></a>dentalPain <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://tjfisher19.github.io/introStatModeling/data/dentalPain.csv&quot;</span>)</span>
<span id="cb244-2"><a href="concepts-of-advanced-designs.html#cb244-2" tabindex="-1"></a><span class="fu">glimpse</span>(dentalPain)</span></code></pre></div>
<pre><code>## Rows: 32
## Columns: 4
## $ PainLevel   &lt;dbl&gt; 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5…
## $ Codeine     &lt;dbl&gt; 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2…
## $ Acupuncture &lt;dbl&gt; 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2…
## $ Relief      &lt;dbl&gt; 0.0, 0.5, 0.6, 1.2, 0.3, 0.6, 0.7, 1.3, 0.4, 0.8, 0.8, 1.6…</code></pre>
<p>Before proceeding with an analysis, we perform some data handling to clean up the factor variables and add appropriate labels.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="concepts-of-advanced-designs.html#cb246-1" tabindex="-1"></a>dentalPain <span class="ot">&lt;-</span> dentalPain <span class="sc">|&gt;</span></span>
<span id="cb246-2"><a href="concepts-of-advanced-designs.html#cb246-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">PainLevel =</span> <span class="fu">factor</span>(PainLevel),</span>
<span id="cb246-3"><a href="concepts-of-advanced-designs.html#cb246-3" tabindex="-1"></a>         <span class="at">Codeine =</span> <span class="fu">factor</span>(Codeine, <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,</span>
<span id="cb246-4"><a href="concepts-of-advanced-designs.html#cb246-4" tabindex="-1"></a>                          <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Sugar Pill&quot;</span>,</span>
<span id="cb246-5"><a href="concepts-of-advanced-designs.html#cb246-5" tabindex="-1"></a>                                   <span class="st">&quot;Codeine Capsule&quot;</span>)),</span>
<span id="cb246-6"><a href="concepts-of-advanced-designs.html#cb246-6" tabindex="-1"></a>         <span class="at">Acupuncture =</span> <span class="fu">factor</span>(Acupuncture, <span class="at">levels=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,</span>
<span id="cb246-7"><a href="concepts-of-advanced-designs.html#cb246-7" tabindex="-1"></a>                              <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Inactive Acupuncture&quot;</span>,</span>
<span id="cb246-8"><a href="concepts-of-advanced-designs.html#cb246-8" tabindex="-1"></a>                                       <span class="st">&quot;Active Acupuncture&quot;</span>)))</span></code></pre></div>
</div>
<div id="eda-for-two-factor-with-block" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> EDA for two-factor with block<a href="concepts-of-advanced-designs.html#eda-for-two-factor-with-block" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As described above, there are two factor levels and we are interested in the <span class="math inline">\(2\times 2=4\)</span> unique treatments in this study, but there is also a block term.
Unlike the previous example, we are not interested in the interaction of all the variables since the level of pain tolerance is a block term.
An exploratory data analysis can be tricky here – in a <span class="math inline">\(2\times 2\)</span> design we can make a simple interactions plot, but here we also have 8 block terms.
Fortunately, since we only have 4 unique treatments, we can reformulate the data into a One-way model with a block term and treat it as in section @ref{blockingSection} of the text.
Below we create a new <code>Treatment</code> variable as we did in Section <a href="multiple-factor-designed-experiments.html#twoFactorAsOneFactor">3.2.4</a>. Here we specify the <code>\n</code> variable to <strong>sep</strong>arate the two character strings that are being pasted together.
The <code>\n</code> is a special <em>escape character</em> that will print a new line in some of our output.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="concepts-of-advanced-designs.html#cb247-1" tabindex="-1"></a>dentalPain <span class="ot">&lt;-</span> dentalPain <span class="sc">|&gt;</span></span>
<span id="cb247-2"><a href="concepts-of-advanced-designs.html#cb247-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">paste</span>(Codeine, Acupuncture, <span class="at">sep=</span><span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>),</span>
<span id="cb247-3"><a href="concepts-of-advanced-designs.html#cb247-3" tabindex="-1"></a>         <span class="at">Treatment =</span> <span class="fu">factor</span>(Treatment, </span>
<span id="cb247-4"><a href="concepts-of-advanced-designs.html#cb247-4" tabindex="-1"></a>                            <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;Sugar Pill</span><span class="sc">\n</span><span class="st">Inactive Acupuncture&quot;</span>,</span>
<span id="cb247-5"><a href="concepts-of-advanced-designs.html#cb247-5" tabindex="-1"></a>                                     <span class="st">&quot;Sugar Pill</span><span class="sc">\n</span><span class="st">Active Acupuncture&quot;</span>,</span>
<span id="cb247-6"><a href="concepts-of-advanced-designs.html#cb247-6" tabindex="-1"></a>                                     <span class="st">&quot;Codeine Capsule</span><span class="sc">\n</span><span class="st">Inactive Acupuncture&quot;</span>,</span>
<span id="cb247-7"><a href="concepts-of-advanced-designs.html#cb247-7" tabindex="-1"></a>                                     <span class="st">&quot;Codeine Capsule</span><span class="sc">\n</span><span class="st">Active Acupuncture&quot;</span>) ) )</span></code></pre></div>
<p>Now, we can make a profile plot as we have seen before.
In Figure <a href="concepts-of-advanced-designs.html#fig:dentalPainProfile">4.6</a> we have a profile plot of pain relief scores across 4 unique treatments for each of the 8 groups.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="concepts-of-advanced-designs.html#cb248-1" tabindex="-1"></a><span class="fu">ggplot</span>(dentalPain,</span>
<span id="cb248-2"><a href="concepts-of-advanced-designs.html#cb248-2" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>Treatment, <span class="at">y=</span>Relief, </span>
<span id="cb248-3"><a href="concepts-of-advanced-designs.html#cb248-3" tabindex="-1"></a>                <span class="at">group=</span>PainLevel)) <span class="sc">+</span> </span>
<span id="cb248-4"><a href="concepts-of-advanced-designs.html#cb248-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color=</span><span class="st">&quot;gray30&quot;</span> ) <span class="sc">+</span></span>
<span id="cb248-5"><a href="concepts-of-advanced-designs.html#cb248-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span><span class="st">&quot;mean&quot;</span>, <span class="at">geom=</span><span class="st">&quot;line&quot;</span>, <span class="at">group=</span><span class="dv">0</span>,</span>
<span id="cb248-6"><a href="concepts-of-advanced-designs.html#cb248-6" tabindex="-1"></a>               <span class="at">color=</span><span class="st">&quot;navy&quot;</span>, <span class="at">linewidth=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb248-7"><a href="concepts-of-advanced-designs.html#cb248-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Treatment Plan&quot;</span>, <span class="at">y=</span><span class="st">&quot;Pain Relief Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb248-8"><a href="concepts-of-advanced-designs.html#cb248-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dentalPainProfile"></span>
<img src="introStatModeling_files/figure-html/dentalPainProfile-1.png" alt="Profiles of pain relif scores for each unique combination of acupuncture and codeine treatments across each of the 8 level of pain tolerance.." width="60%" />
<p class="caption">
Figure 4.6: Profiles of pain relif scores for each unique combination of acupuncture and codeine treatments across each of the 8 level of pain tolerance..
</p>
</div>
<p>From Figure <a href="concepts-of-advanced-designs.html#fig:dentalPainProfile">4.6</a>, it visually appears that the group receiving both active acupuncture and codeine report the highest pain relief scores.
We can formally check this with ANOVA.</p>
</div>
<div id="fitting-two-factor-with-block-model" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Fitting two-factor with block model<a href="concepts-of-advanced-designs.html#fitting-two-factor-with-block-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall, we have two factor variables and a block term, we use a formula of the form: <code>response ~ block + factor1*factor2</code>.</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="concepts-of-advanced-designs.html#cb249-1" tabindex="-1"></a>dentalpain.anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Relief <span class="sc">~</span> PainLevel <span class="sc">+</span> Codeine<span class="sc">*</span>Acupuncture,</span>
<span id="cb249-2"><a href="concepts-of-advanced-designs.html#cb249-2" tabindex="-1"></a>                        <span class="at">data=</span>dentalPain)</span></code></pre></div>
<p>We check the model diagnostic plots to look for violations in our underlying assumptions as seen in Figure <a href="concepts-of-advanced-designs.html#fig:dentalPainResiduals">4.7</a>.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="concepts-of-advanced-designs.html#cb250-1" tabindex="-1"></a><span class="fu">autoplot</span>(dentalpain.anova)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dentalPainResiduals"></span>
<img src="introStatModeling_files/figure-html/dentalPainResiduals-1.png" alt="Residual diagnostic plots when the response variable is pain relief scores a function of pain tolerance and the treatments of acupuncture and codeine. Here, the Residuals vs Fitted and Scale-Location plots may suggest unequal variance. The Normal Q-Q plot may suggest that the residuals are slightly skewed to the right." width="70%" />
<p class="caption">
Figure 4.7: Residual diagnostic plots when the response variable is pain relief scores a function of pain tolerance and the treatments of acupuncture and codeine. Here, the Residuals vs Fitted and Scale-Location plots may suggest unequal variance. The Normal Q-Q plot may suggest that the residuals are slightly skewed to the right.
</p>
</div>
<p>The results in Figure <a href="concepts-of-advanced-designs.html#fig:dentalPainResiduals">4.7</a> are far from <em>textbook</em>. In the Residuals vs Fitted plot and Scale-Location, there does appear to be some evidence that the variability is increasing with the fitted value.
The Q-Q plot shows some deviation (albeit with not very large <span class="math inline">\(Z\)</span>-scores) from Normality and it would suggest some minor skewness.</p>
<p>In situations like this, there is no clear step to take. We can try a transformation such a logarithm, but first note that the very first observation in the data has a zero response.</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="concepts-of-advanced-designs.html#cb251-1" tabindex="-1"></a><span class="fu">head</span>(dentalPain, <span class="at">n=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   PainLevel Codeine    Acupuncture          Relief Treatment                    
##   &lt;fct&gt;     &lt;fct&gt;      &lt;fct&gt;                 &lt;dbl&gt; &lt;fct&gt;                        
## 1 1         Sugar Pill Inactive Acupuncture      0 &quot;Sugar Pill\nInactive Acupun…</code></pre>
<p>The value <span class="math inline">\(\log_{10}(0)\)</span> is undefined.
When this happens, we can essentially <em>trick</em> a transformation to occur by adding some value to force the data to be strictly positive.
It is customary to add 1 to the value of response which guarantees all response values are greater than or equal to 1.
Also <span class="math inline">\(\log_{10}(1) = 0\)</span> so any zero values in the original units are zero on the log-scale.
We perform a log-base 10 of the response plus one.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="concepts-of-advanced-designs.html#cb253-1" tabindex="-1"></a>logDentalpain.anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">log10</span>(Relief<span class="sc">+</span><span class="dv">1</span>) <span class="sc">~</span> PainLevel <span class="sc">+</span> Codeine<span class="sc">*</span>Acupuncture,</span>
<span id="cb253-2"><a href="concepts-of-advanced-designs.html#cb253-2" tabindex="-1"></a>                           <span class="at">data=</span>dentalPain)</span>
<span id="cb253-3"><a href="concepts-of-advanced-designs.html#cb253-3" tabindex="-1"></a><span class="fu">autoplot</span>(logDentalpain.anova)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dentalPainResiduals2"></span>
<img src="introStatModeling_files/figure-html/dentalPainResiduals2-1.png" alt="Residual diagnostic plots when the response variable is pain relief scores a function of pain tolerance and the treatments of acupuncture and codeine. Here, the residuals appear fairly homoskedastic based on the Residuals vs Fitted and Scale-Location plots. The residuals may not be Normally distributed as there is deviation in both tails." width="70%" />
<p class="caption">
Figure 4.8: Residual diagnostic plots when the response variable is pain relief scores a function of pain tolerance and the treatments of acupuncture and codeine. Here, the residuals appear fairly homoskedastic based on the Residuals vs Fitted and Scale-Location plots. The residuals may not be Normally distributed as there is deviation in both tails.
</p>
</div>
<p>Figure @(fig:dentalPainResiduals2) shows <em>maybe</em> some improvement in the variability assumption.
Specifically, the Scale-Location plot no longer shows a slight increase in variability with respect to the fitted values.
However, the Q-Q plot may suggest more deviation from the Normality assumption after the transformation.
<strong>So it is not entirely clear if a transformation is helpful.</strong></p>
<p>In situations such as these, it is likely best to use the original data.
Transforming a response comes with some cost – we lose some contextual interpretation.
So we should always asks ourselves if that cost is worth any improvement we see in the model assumptions.
Here, it is not clear transforming the response helps with our model assumption, so we will use the model fit on the original response.</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="concepts-of-advanced-designs.html#cb254-1" tabindex="-1"></a><span class="fu">summary</span>(dentalpain.anova)</span></code></pre></div>
<pre><code>##                     Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## PainLevel            7   5.60    0.80   55.30 4.1e-12 ***
## Codeine              1   2.31    2.31  159.79 2.8e-11 ***
## Acupuncture          1   3.38    3.38  233.68 7.5e-13 ***
## Codeine:Acupuncture  1   0.05    0.05    3.11   0.092 .  
## Residuals           21   0.30    0.01                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Recall, we look at the most <em>complex</em> interaction term first; here <code>Codeine:Acupuncture</code>.
With an <span class="math inline">\(F\)</span>-stat of 3.11 on 1 and 21 degrees of freedom (<span class="math inline">\(p\)</span>-value = 0.0923), we do not have evidence that the effects of codeine on pain relief depends on the acupuncture treatment.</p>
<p>That first result allows us to look at the main effects:</p>
<ul>
<li>With an <span class="math inline">\(F\)</span>-stat of 160 on 1 and 21 degrees of freedom (<span class="math inline">\(p\)</span>-value<span class="math inline">\(\approx 10^{-11}\)</span>), we have conclusive evidence that a codeine capsule influences the pain relief score.</li>
<li>With an <span class="math inline">\(F\)</span>-stat of 234 on 1 and 21 degrees of freedom (<span class="math inline">\(p\)</span>-value<span class="math inline">\(\approx 10^{-13}\)</span>), we have conclusive evidence that the acupuncture treatment influences the pain relief score.</li>
</ul>
</div>
<div id="multiple-comparisons-3" class="section level3 hasAnchor" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Multiple comparisons<a href="concepts-of-advanced-designs.html#multiple-comparisons-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>So we have concluded that both Acupunture and Codeine appear to influence pain relief, and that they do not necessarily interact (that is, the influence of one on the response does not necessarily depend on the other).
What remains to be see, is <strong>how these treatments influence the response?</strong>
You should also note that this experiment includes a natural <em>control</em> group (Sugar pill and inactive acupuncture).
So a Dunnett’s multiple comparison method is appropriate.</p>
<p>Following the example in Section <a href="multiple-factor-designed-experiments.html#twoFactorAsOneFactor">3.2.4</a> we refit the model as a One-Way block model with the <span class="math inline">\(2\times 2=4\)</span> unique treatments.
Note that residual analysis are not needed here because this is the same underlying model as above, just formulated a little differently.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="concepts-of-advanced-designs.html#cb256-1" tabindex="-1"></a>dentalPain.anova2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(Relief <span class="sc">~</span> PainLevel <span class="sc">+</span> Treatment,</span>
<span id="cb256-2"><a href="concepts-of-advanced-designs.html#cb256-2" tabindex="-1"></a>                         <span class="at">data=</span>dentalPain)</span>
<span id="cb256-3"><a href="concepts-of-advanced-designs.html#cb256-3" tabindex="-1"></a><span class="fu">summary</span>(dentalPain.anova2)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## PainLevel    7   5.60   0.800    55.3 4.1e-12 ***
## Treatment    3   5.74   1.912   132.2 8.6e-14 ***
## Residuals   21   0.30   0.014                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Not surprisingly, with an <span class="math inline">\(F\)</span>-stat of 132.2 on 3 and 21 degrees of freedom (<span class="math inline">\(p\)</span>-value<span class="math inline">\(\approx 10^{-14}\)</span>) we have evidence that the different treatment influence pain relief scores.
Note that the <code>PainLevel</code> and <code>Residuals</code> lines match the previous table.
Here, the effects of Codeine, Acupuncture and their interaction have been combined into the new variable <code>Treatment</code>.</p>
<p>In a previous code chunk (for building the profile plot in Figure <a href="concepts-of-advanced-designs.html#fig:dentalPainProfile">4.6</a>) we already re-ordered the treatment levels so the control group is the first factor level.
Below we provide code to perform the multiple comparisons.</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="concepts-of-advanced-designs.html#cb258-1" tabindex="-1"></a>dental.em <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(dentalPain.anova2, <span class="sc">~</span>Treatment)</span>
<span id="cb258-2"><a href="concepts-of-advanced-designs.html#cb258-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(dental.em, <span class="st">&quot;dunnett&quot;</span>, <span class="at">ref=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb258-3"><a href="concepts-of-advanced-designs.html#cb258-3" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb258-4"><a href="concepts-of-advanced-designs.html#cb258-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Difference in Pain Relief Scores&quot;</span>,</span>
<span id="cb258-5"><a href="concepts-of-advanced-designs.html#cb258-5" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dentalPainMultComp"></span>
<img src="introStatModeling_files/figure-html/dentalPainMultComp-1.png" alt="Dunnett adjusted confidence interval plots comparing the three treatments against the control. Here, all three treatments are significantly different than the control. Both a Codeine Capsule and Acupunture treatments alone improve pain relief scores by about 0.5 units, while when both are utilize pain relief scores improve by about 1.2 units. Self-induced treatment is not statistically different than the control (zero is in the interval) while the Therapist based treatment results in significantly more weight loss than the control." width="60%" />
<p class="caption">
Figure 4.9: Dunnett adjusted confidence interval plots comparing the three treatments against the control. Here, all three treatments are significantly different than the control. Both a Codeine Capsule and Acupunture treatments alone improve pain relief scores by about 0.5 units, while when both are utilize pain relief scores improve by about 1.2 units. Self-induced treatment is not statistically different than the control (zero is in the interval) while the Therapist based treatment results in significantly more weight loss than the control.
</p>
</div>
<p>The results in Figure <a href="concepts-of-advanced-designs.html#fig:dentalPainMultComp">4.9</a> show that all three treatment are statistically different than the control.
This is not too surprising given the results of the ANOVA results above – the interaction term was not significant but both main effects were.
That implies that the introduction of Codeine compared to a sugar pill will have an effect and that active acupuncture will also have an effect compared to inactive acupuncture.
When both Codeine and Active acupuncture are used, we see a greater effect as compared to each (in fact, you’ll note in Figure <a href="concepts-of-advanced-designs.html#fig:dentalPainMultComp">4.9</a> that the difference with of both Codeine and Acupuncture is about the summation of differences for each treatment on its own).</p>
</div>
</div>
<div id="within-subject-designs" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Within-subject designs<a href="concepts-of-advanced-designs.html#within-subject-designs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In these chapters covering experimental design, we have seen different designs where factor(s) levels are manipulated by the researcher in order to measure a response.
In simpler design settings, the factors that are manipulated are of the “between-subjects” type.
For example, Section <a href="concepts-of-advanced-designs.html#dentalPainExample">4.2.1</a> provides a two-factor example on pain relief where each participant (experimental unit) had exactly one treatment randomly assigned to them.
As such, there is only one observation per experimental unit in that design.
The different treatments are a <strong>between-subjects factor</strong>.</p>
<p><strong>Why is that important to note?</strong></p>
<p>One of the key underlying assumptions in statistical methods is the <strong>independence</strong> assumption.
When the treatments are between-subject factors, this essentially assures that the observations in the data are all independent.
In Section <a href="statistical-modeling-and-designed-experiments.html#assumptionCheck">2.5</a> we highlighted that independence is the most important assumption for statistical analysis.
In fact, independence is more important to inference validity than either normality or constant variance assumptions.</p>
<p>Now, contrast this with the <strong>paired <span class="math inline">\(t\)</span>-test</strong> (see Section <a href="multiple-factor-designed-experiments.html#pairedTtest">3.1.3</a> for an example).
A hypothetical example was discussed that involved giving a sample of 20 people a drug treatment in order to study its effect on the Cholesterol of the patients.
Think of that problem from a design of experiments point of view: what is the factor(s) that is manipulated by the researcher?</p>
<ul>
<li>It is not the drug treatment! In the experiment only one drug was studied: there was no “comparison” drug or placebo used to form a basis for comparison. As such, the drug treatment in that problem was not a variable at all: it was a constant. All patients received it.</li>
<li>So what did the experimenter determine? The answer is TIME. The researcher measured Cholesterol at two time points on each patient (experimental unit): [1] just before the start of the drug treatment, and [2] 45 days later. The factor here is time, and it has two levels. Here, we say Time is a <strong>within-subject factor</strong>.</li>
</ul>
<p>The important thing to recognize here is that each patient provided two observations, not one.
It stands to reason that <em>what a particular subject’s Cholesterol is after 45 days will be related to their starting Cholesterol before the drug treatment</em>.
That is the layman’s way of saying that the measurements within a subject are <strong>not independent</strong> (<em>i.e.</em>, a patient is not independent of themselves – the two observations are correlated).
If in any analysis we ignored this basic truth, that analysis would be seriously flawed.</p>
<p>So how did we handle this before?
A simple strategy which is common with paired data comparisons is to calculate each subject’s difference score (yielding a single difference measurement per subject) and then performing a one-sample <span class="math inline">\(t\)</span>-test on the differences.
Each difference score is independent because each came from a different person (or subject).
This is what is done in the paired <span class="math inline">\(t\)</span>-test analysis in section <a href="multiple-factor-designed-experiments.html#pairedTtest">3.1.3</a>.</p>
<p>In general, calculating differences is not always feasible – what would you calculate if an experimenter used three timed measurements on each subject?
In a designed experiment that involves several measurements made on the same experimental unit over time, the design is called a <strong>repeated measures design</strong> and we will build up to it.</p>
<div id="blocks-revisited-an-approach-to-handling-within-subjects-factors" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Blocks revisited: an approach to handling within-subjects factors<a href="concepts-of-advanced-designs.html#blocks-revisited-an-approach-to-handling-within-subjects-factors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The notion and purpose of blocking in an experimental design was introduced in section <a href="multiple-factor-designed-experiments.html#blockingSection">3.1</a>.
Recall the definition of block terms as a relatively homogeneously set of experimental material.
We saw multiple examples where subjects serve as blocks.
This informs us that using a block design approach in analysis is ‘a way’ to handle correlated (non-independent) observations.
We illustrate that here by revisiting the data example from Section <a href="multiple-factor-designed-experiments.html#pairedTtest">3.1.3</a>.</p>
<p><strong>Example.</strong> Carbon Emissions (originally in <span class="citation">Weiss (<a href="#ref-WeissText">2012</a>)</span>).</p>
<p>The makers of the MAGNETIZER Engine Energizer System (EES) claim that it improves the gas mileage and reduces emissions in automobiles by using magnetic free energy to increase the amount of oxygen in the fuel for greater combustion efficiency.
Test results for 14 vehicles that underwent testing is available in the file <code>carCOemissions.csv</code>.
The data includes the emitted carbon monoxide (CO) levels, in parts per million, of each of the 14 vehicles tested before and after installation of the EES.</p>
<p>This is a classic before-after (Paired design) study. Below is some code to implement the test.</p>
<p>First, we quickly recap the Paired <span class="math inline">\(t\)</span>-test result from Section <a href="multiple-factor-designed-experiments.html#pairedTtest">3.1.3</a>.</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="concepts-of-advanced-designs.html#cb259-1" tabindex="-1"></a>www <span class="ot">&lt;-</span> <span class="st">&quot;https://tjfisher19.github.io/introStatModeling/data/carCOemissions.csv&quot;</span></span>
<span id="cb259-2"><a href="concepts-of-advanced-designs.html#cb259-2" tabindex="-1"></a>vehicleCO <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(www, <span class="at">col_types =</span> <span class="fu">cols</span>())</span>
<span id="cb259-3"><a href="concepts-of-advanced-designs.html#cb259-3" tabindex="-1"></a>vehicleCO</span></code></pre></div>
<pre><code>## # A tibble: 14 × 3
##       id before after
##    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1     1   1.6   0.15
##  2     2   0.3   0.2 
##  3     3   3.8   2.8 
##  4     4   6.2   3.6 
##  5     5   3.6   1   
##  6     6   1.5   0.5 
##  7     7   2     1.6 
##  8     8   2.6   1.6 
##  9     9   0.15  0.06
## 10    10   0.06  0.16
## 11    11   0.6   0.35
## 12    12   0.03  0.01
## 13    13   0.1   0   
## 14    14   0.19  0</code></pre>
<p>and the paired <span class="math inline">\(t\)</span>-test</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="concepts-of-advanced-designs.html#cb261-1" tabindex="-1"></a><span class="fu">t.test</span>(vehicleCO<span class="sc">$</span>before, vehicleCO<span class="sc">$</span>after, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  vehicleCO$before and vehicleCO$after
## t = 3.146, df = 13, p-value = 0.00773
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.239443 1.289129
## sample estimates:
## mean difference 
##        0.764286</code></pre>
<p>Now, we will perform this same analysis using a Block ANOVA.
The data is structure that 2 observations (the before and after) are on each row of the data frame.
We reshape this data into a tall, or long, format.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="concepts-of-advanced-designs.html#cb263-1" tabindex="-1"></a>vehicleCO_tall <span class="ot">&lt;-</span> vehicleCO <span class="sc">|&gt;</span></span>
<span id="cb263-2"><a href="concepts-of-advanced-designs.html#cb263-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols=</span><span class="fu">c</span>(before, after),</span>
<span id="cb263-3"><a href="concepts-of-advanced-designs.html#cb263-3" tabindex="-1"></a>               <span class="at">names_to=</span><span class="st">&quot;Time&quot;</span>,</span>
<span id="cb263-4"><a href="concepts-of-advanced-designs.html#cb263-4" tabindex="-1"></a>               <span class="at">values_to=</span><span class="st">&quot;Emitted_CO&quot;</span>)</span>
<span id="cb263-5"><a href="concepts-of-advanced-designs.html#cb263-5" tabindex="-1"></a><span class="fu">head</span>(vehicleCO_tall)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##      id Time   Emitted_CO
##   &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;
## 1     1 before       1.6 
## 2     1 after        0.15
## 3     2 before       0.3 
## 4     2 after        0.2 
## 5     3 before       3.8 
## 6     3 after        2.8</code></pre>
<p>Note the difference in the layout of the data here as compared to the original <code>vehicleCO</code> used in the paired <span class="math inline">\(t\)</span>-test: each observation occupies a single row of the data file now.
There is an identifier variable (<code>id</code>) that identifies which subject every observation belongs to.
The variable Time <code>refers</code> to the time factor and <code>Emitted_CO</code> records the emitted Carbon Monoxide levels (ppm).</p>
<p>We will analyze this same data (addressing the same research question) by using a <strong>block design approach</strong>:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="concepts-of-advanced-designs.html#cb265-1" tabindex="-1"></a>vehicleco.block.aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Emitted_CO <span class="sc">~</span> <span class="fu">factor</span>(id) <span class="sc">+</span> Time, <span class="at">data=</span>vehicleCO_tall)</span>
<span id="cb265-2"><a href="concepts-of-advanced-designs.html#cb265-2" tabindex="-1"></a><span class="fu">summary</span>(vehicleco.block.aov)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## factor(id)  13   56.7    4.36    10.6 7.2e-05 ***
## Time         1    4.1    4.09     9.9  0.0077 ** 
## Residuals   13    5.4    0.41                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Look at the <span class="math inline">\(F\)</span>-test for the time factor (labeled <code>Time</code> here).
This result is identical to the result of the paired t-test above (<span class="math inline">\(F\)</span> = 9.897, <span class="math inline">\(\textrm{df}_1\)</span> = 1, <span class="math inline">\(\textrm{df}_2\)</span> = 13, <span class="math inline">\(p\)</span>-value <span class="math inline">\(= 0.00773\)</span>).
Note, <span class="math inline">\(\sqrt{9.897} =\)</span> 3.146, the value of the paired <span class="math inline">\(t\)</span>-test statistic.</p>
<p><em>How does the block approach work here?</em> Note that the test of Time (the within subjects effect) uses the residual effect as the error term.
Because the blocks are included in the model (and here, the blocks constitutes the overall between-subjects, or between-vehicles, variability source), the only variation left over for the “residuals” is the variability due to the within-vehicle differences.
In essence, there are <strong>two components</strong> to the random error now:</p>
<ul>
<li>Aggregated variability between vehicles (block effect)</li>
<li>Remaining unexplained (random) variability after accounting for aggregate vehicle-to-vehicle differences and aggregated time-to-time differences. We will call this leftover stuff “pure” error.</li>
</ul>
<p>For a correct analysis, it is important that each factor of interest in the study be tested against the proper component of the error. Here, <strong>we test a within-subjects effect against the random error component dealing with “pure” random error</strong>.</p>
<p><strong>A more general approach</strong> to within-subjects analysis is to specify to R that there are layers of random variability in the data introduced by the fact that we have more than one measurement per experimental unit.
This can be done using a model specification that explicitly cites these layers with an <code>Error</code>.
The model specification in R is generally</p>
<pre><code>`response ~ between-subjects factor structure + Error(EU variable/within-subjects factor)`</code></pre>
<p>In the working example, our model formulation will look like this:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="concepts-of-advanced-designs.html#cb268-1" tabindex="-1"></a>WS_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Emitted_CO <span class="sc">~</span> Time <span class="sc">+</span> <span class="fu">Error</span>(<span class="fu">factor</span>(id)<span class="sc">/</span>Time), <span class="at">data=</span>vehicleCO_tall)</span>
<span id="cb268-2"><a href="concepts-of-advanced-designs.html#cb268-2" tabindex="-1"></a><span class="fu">summary</span>(WS_aov)</span></code></pre></div>
<pre><code>## 
## Error: factor(id)
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals 13   56.7    4.36               
## 
## Error: factor(id):Time
##           Df Sum Sq Mean Sq F value Pr(&gt;F)   
## Time       1   4.09    4.09     9.9 0.0077 **
## Residuals 13   5.37    0.41                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The overall output looks a little different but in the end, we get the same result (<span class="math inline">\(F\)</span>-stat of 4.089 on 1 and 13 degrees of freedom, <span class="math inline">\(p\)</span>-value=0.00773).
In more complex studies this general approach is preferred.</p>
</div>
<div id="repeated-measures-case-study" class="section level3 hasAnchor" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Repeated Measures Case Study<a href="concepts-of-advanced-designs.html#repeated-measures-case-study" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we can handle within-subjects factors using blocks, why not just stick with that all the time?<br />
Well, the reason is that repeated measures designs can get complicated: multiple time measurement points (more than just two), the addition of between-subjects factors, perhaps other block terms, etc…
The following case study example illustrates this.</p>
<p><strong>Example.</strong> Cholesterol study (from the University of Sheffield <span class="citation">(<a href="#ref-sheffield2021">Sheffield, 2021</a>)</span>).</p>
<p>A study tested whether cholesterol was reduced after using a certain brand of margarine as part of a low fat, low cholesterol diet. The subjects consumed on average 2.31g of the active ingredient, <em>stanol ester</em>, a day. This data set <code>cholesterolreduction.csv</code> contains information on 18 people using margarine to reduce cholesterol over three time points.
The variables in the data can be summarized as follows:</p>
<table>
<thead>
<tr class="header">
<th align="left">Variable Name</th>
<th align="left">Variable</th>
<th align="left">Data type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ID</td>
<td align="left">Participant Number</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Before</td>
<td align="left">Cholesterol before the diet (mmol/L)</td>
<td align="left">Scale</td>
</tr>
<tr class="odd">
<td align="left">After4weeks</td>
<td align="left">Cholesterol after 4 weeks on diet (mmol/L)</td>
<td align="left">Scale</td>
</tr>
<tr class="even">
<td align="left">After8weeks</td>
<td align="left">Cholesterol after 8 weeks on diet (mmol/L)</td>
<td align="left">Scale</td>
</tr>
<tr class="odd">
<td align="left">Margarine</td>
<td align="left">Margarine type A or B</td>
<td align="left">Binary</td>
</tr>
</tbody>
</table>
<p>We input the data from the book repository.</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="concepts-of-advanced-designs.html#cb270-1" tabindex="-1"></a><span class="st">&quot;carCOemissions.csv&quot;</span></span>
<span id="cb270-2"><a href="concepts-of-advanced-designs.html#cb270-2" tabindex="-1"></a>chol <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;https://tjfisher19.github.io/introStatModeling/data/cholesterolreduction.csv&quot;</span>, <span class="at">col_types=</span><span class="fu">cols</span>())</span>
<span id="cb270-3"><a href="concepts-of-advanced-designs.html#cb270-3" tabindex="-1"></a><span class="fu">glimpse</span>(chol)</span></code></pre></div>
<pre><code>## Rows: 18
## Columns: 5
## $ ID          &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
## $ Before      &lt;dbl&gt; 6.42, 6.76, 6.56, 4.80, 8.43, 7.49, 8.05, 5.05, 5.77, 3.91…
## $ After4weeks &lt;dbl&gt; 5.83, 6.20, 5.83, 4.27, 7.71, 7.12, 7.25, 4.63, 5.31, 3.70…
## $ After8weeks &lt;dbl&gt; 5.75, 6.13, 5.71, 4.15, 7.67, 7.05, 7.10, 4.67, 5.33, 3.66…
## $ Margarine   &lt;chr&gt; &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;A&quot;, &quot;B&quot;, &quot;B&quot;…</code></pre>
<p>Note that in this experiment there are two factors of interest:</p>
<ul>
<li>Time (3 levels within-subjects): before, after4weeks, after8weeks)</li>
<li>Margarine type (2 level between-subjects): A or B</li>
</ul>
<p>The data is provided in wide format that may be easy for humans to read but we need to convert it to tall form:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="concepts-of-advanced-designs.html#cb272-1" tabindex="-1"></a>chol_tall <span class="ot">&lt;-</span> chol <span class="sc">|&gt;</span> </span>
<span id="cb272-2"><a href="concepts-of-advanced-designs.html#cb272-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols=</span>Before<span class="sc">:</span>After8weeks, </span>
<span id="cb272-3"><a href="concepts-of-advanced-designs.html#cb272-3" tabindex="-1"></a>               <span class="at">names_to=</span><span class="st">&quot;time.pt&quot;</span>, </span>
<span id="cb272-4"><a href="concepts-of-advanced-designs.html#cb272-4" tabindex="-1"></a>               <span class="at">values_to=</span><span class="st">&quot;chol.level&quot;</span>)</span>
<span id="cb272-5"><a href="concepts-of-advanced-designs.html#cb272-5" tabindex="-1"></a><span class="fu">head</span>(chol_tall)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##      ID Margarine time.pt     chol.level
##   &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;            &lt;dbl&gt;
## 1     1 B         Before            6.42
## 2     1 B         After4weeks       5.83
## 3     1 B         After8weeks       5.75
## 4     2 A         Before            6.76
## 5     2 A         After4weeks       6.2 
## 6     2 A         After8weeks       6.13</code></pre>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="concepts-of-advanced-designs.html#cb274-1" tabindex="-1"></a>chol_tall <span class="ot">&lt;-</span> chol_tall <span class="sc">|&gt;</span></span>
<span id="cb274-2"><a href="concepts-of-advanced-designs.html#cb274-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time.pt =</span> <span class="fu">factor</span>(time.pt, </span>
<span id="cb274-3"><a href="concepts-of-advanced-designs.html#cb274-3" tabindex="-1"></a>                          <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;Before&quot;</span>, <span class="st">&quot;After4weeks&quot;</span>, <span class="st">&quot;After8weeks&quot;</span>),</span>
<span id="cb274-4"><a href="concepts-of-advanced-designs.html#cb274-4" tabindex="-1"></a>                          <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;Before&quot;</span>, <span class="st">&quot;After 4 weeks&quot;</span>, <span class="st">&quot;After 8 weeks&quot;</span>)))</span></code></pre></div>
<p>We have changed the variable <code>time.pt</code> to be a factor variable and we order the levels so they are contextually sequential (rather than alphabetical order).</p>
<div id="exploratory-data-analysis" class="section level4 hasAnchor" number="4.3.2.1">
<h4><span class="header-section-number">4.3.2.1</span> Exploratory Data Analysis<a href="concepts-of-advanced-designs.html#exploratory-data-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We can now perform an EDA. A table of descriptive statistics by combinations of time and margarine group is our first cut:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="concepts-of-advanced-designs.html#cb275-1" tabindex="-1"></a>chol.summary <span class="ot">&lt;-</span> chol_tall <span class="sc">|&gt;</span></span>
<span id="cb275-2"><a href="concepts-of-advanced-designs.html#cb275-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Margarine, time.pt) <span class="sc">|&gt;</span></span>
<span id="cb275-3"><a href="concepts-of-advanced-designs.html#cb275-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Mean =</span> <span class="fu">mean</span>(chol.level),</span>
<span id="cb275-4"><a href="concepts-of-advanced-designs.html#cb275-4" tabindex="-1"></a>            <span class="at">SD =</span> <span class="fu">sd</span>(chol.level),</span>
<span id="cb275-5"><a href="concepts-of-advanced-designs.html#cb275-5" tabindex="-1"></a>            <span class="at">SE =</span> <span class="fu">sd</span>(chol.level)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(chol.level)),</span>
<span id="cb275-6"><a href="concepts-of-advanced-designs.html#cb275-6" tabindex="-1"></a>            <span class="at">n =</span> <span class="fu">length</span>(chol.level))</span>
<span id="cb275-7"><a href="concepts-of-advanced-designs.html#cb275-7" tabindex="-1"></a><span class="fu">kable</span>(chol.summary)</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Margarine</th>
<th align="left">time.pt</th>
<th align="right">Mean</th>
<th align="right">SD</th>
<th align="right">SE</th>
<th align="right">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">A</td>
<td align="left">Before</td>
<td align="right">6.03556</td>
<td align="right">1.363232</td>
<td align="right">0.454411</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">A</td>
<td align="left">After 4 weeks</td>
<td align="right">5.55000</td>
<td align="right">1.320672</td>
<td align="right">0.440224</td>
<td align="right">9</td>
</tr>
<tr class="odd">
<td align="left">A</td>
<td align="left">After 8 weeks</td>
<td align="right">5.48889</td>
<td align="right">1.307282</td>
<td align="right">0.435761</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="left">Before</td>
<td align="right">6.78000</td>
<td align="right">0.919008</td>
<td align="right">0.306336</td>
<td align="right">9</td>
</tr>
<tr class="odd">
<td align="left">B</td>
<td align="left">After 4 weeks</td>
<td align="right">6.13333</td>
<td align="right">0.863713</td>
<td align="right">0.287904</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">B</td>
<td align="left">After 8 weeks</td>
<td align="right">6.06889</td>
<td align="right">0.825825</td>
<td align="right">0.275275</td>
<td align="right">9</td>
</tr>
</tbody>
</table>
<p>We generally observe that cholesterol levels with margarine A appear lower than with margarine B.
Also, there does appear to be some reduction in cholesterol level using both products: however, there also appears to be more unexplained variability (“noise”) in the cholesterol measurements under margarine A.
We can further check this using some data visualizations.</p>
<p>First let us try boxplots (not appropriate given the design) as seen in Figure <a href="concepts-of-advanced-designs.html#fig:ch4-7">4.10</a>.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="concepts-of-advanced-designs.html#cb276-1" tabindex="-1"></a><span class="fu">ggplot</span>(chol_tall) <span class="sc">+</span></span>
<span id="cb276-2"><a href="concepts-of-advanced-designs.html#cb276-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>time.pt, <span class="at">y=</span>chol.level)) <span class="sc">+</span></span>
<span id="cb276-3"><a href="concepts-of-advanced-designs.html#cb276-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Margarine) <span class="sc">+</span></span>
<span id="cb276-4"><a href="concepts-of-advanced-designs.html#cb276-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Time Point of Measurement&quot;</span>) <span class="sc">+</span></span>
<span id="cb276-5"><a href="concepts-of-advanced-designs.html#cb276-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cholesterol level (mmol/L)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-7"></span>
<img src="introStatModeling_files/figure-html/ch4-7-1.png" alt="Boxplot distribution of the Cholesterol level as a function of Treatment and Time of measurement." width="80%" />
<p class="caption">
Figure 4.10: Boxplot distribution of the Cholesterol level as a function of Treatment and Time of measurement.
</p>
</div>
<p>We see in Figure <a href="concepts-of-advanced-designs.html#fig:ch4-7">4.10</a> that perhaps cholesterol levels are generally more consistent under margarine B, and that it is just some outlier(s) that are the issue.
However, this plot does not reveal a crucial piece of information: <strong>the responses are correlated over time</strong>.
A better depiction would allow us to see how each individual subject’s cholesterol changed over the span of the experiment as seen in Figure <a href="concepts-of-advanced-designs.html#fig:ch4-8">4.11</a>.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="concepts-of-advanced-designs.html#cb277-1" tabindex="-1"></a><span class="co"># Plot the individual-level cholesterol profiles</span></span>
<span id="cb277-2"><a href="concepts-of-advanced-designs.html#cb277-2" tabindex="-1"></a><span class="fu">ggplot</span>(chol_tall, <span class="fu">aes</span>(<span class="at">x=</span>time.pt, <span class="at">y=</span>chol.level, <span class="at">colour=</span>Margarine, <span class="at">group=</span>ID)) <span class="sc">+</span></span>
<span id="cb277-3"><a href="concepts-of-advanced-designs.html#cb277-3" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb277-4"><a href="concepts-of-advanced-designs.html#cb277-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">21</span>, <span class="at">fill=</span><span class="st">&quot;white&quot;</span>) <span class="sc">+</span> </span>
<span id="cb277-5"><a href="concepts-of-advanced-designs.html#cb277-5" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Margarine) <span class="sc">+</span></span>
<span id="cb277-6"><a href="concepts-of-advanced-designs.html#cb277-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Time Point of Measurement&quot;</span>) <span class="sc">+</span></span>
<span id="cb277-7"><a href="concepts-of-advanced-designs.html#cb277-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cholesterol level (mmol/L)&quot;</span>) <span class="sc">+</span></span>
<span id="cb277-8"><a href="concepts-of-advanced-designs.html#cb277-8" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Subject-level cholesterol profiles by Margarine group&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-8"></span>
<img src="introStatModeling_files/figure-html/ch4-8-1.png" alt="Profile plots of the Cholesterol level as a function of Treatment and Time of measurement." width="80%" />
<p class="caption">
Figure 4.11: Profile plots of the Cholesterol level as a function of Treatment and Time of measurement.
</p>
</div>
<p>In Figure <a href="concepts-of-advanced-designs.html#fig:ch4-8">4.11</a> we see some elements more clearly.
The general decreasing pattern over time appears to be pretty consistent for every experimental unit (visually, each “line” in the plot).
There are two individuals in margarine B whose cholesterol level seems unusually higher than the others: this might warrant further investigation.
Now we provide an summary profile of the two treatments in <a href="concepts-of-advanced-designs.html#fig:ch4-9">4.12</a>.</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="concepts-of-advanced-designs.html#cb278-1" tabindex="-1"></a><span class="co"># we include a position_dodge elements to avoid overlap</span></span>
<span id="cb278-2"><a href="concepts-of-advanced-designs.html#cb278-2" tabindex="-1"></a><span class="fu">ggplot</span>(chol.summary, <span class="fu">aes</span>(<span class="at">x=</span>time.pt, <span class="at">y=</span>Mean, <span class="at">colour=</span>Margarine)) <span class="sc">+</span> </span>
<span id="cb278-3"><a href="concepts-of-advanced-designs.html#cb278-3" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin=</span>Mean<span class="sc">-</span>SE, <span class="at">ymax=</span>Mean<span class="sc">+</span>SE), <span class="at">width=</span>.<span class="dv">1</span>, <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb278-4"><a href="concepts-of-advanced-designs.html#cb278-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group=</span>Margarine), <span class="at">position=</span><span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb278-5"><a href="concepts-of-advanced-designs.html#cb278-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="fu">position_dodge</span>(<span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb278-6"><a href="concepts-of-advanced-designs.html#cb278-6" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Time Point of Measurement&quot;</span>) <span class="sc">+</span></span>
<span id="cb278-7"><a href="concepts-of-advanced-designs.html#cb278-7" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Cholesterol level (mmol/L)&quot;</span>) <span class="sc">+</span></span>
<span id="cb278-8"><a href="concepts-of-advanced-designs.html#cb278-8" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mean Cholesterol level (with Standard Error bars)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-9"></span>
<img src="introStatModeling_files/figure-html/ch4-9-1.png" alt="Average Profile of Cholesterol level by Treatment in Time." width="70%" />
<p class="caption">
Figure 4.12: Average Profile of Cholesterol level by Treatment in Time.
</p>
</div>
<p>Note some of the <em>bells and whistles</em> added to Figure <a href="concepts-of-advanced-designs.html#fig:ch4-9">4.12</a> – error bars are added to each point to provide a measure of variation and <em>dodging</em> was used to separate overlapping lines.
Contextually, Figure <a href="concepts-of-advanced-designs.html#fig:ch4-9">4.12</a> visually shows that margarine A Cholesterol levels appear lower than margarine B.
It is worth noting that the group assigned to margarine level A had lower cholesterol “before” the study began.</p>
</div>
<div id="preliminary-inferential-analysis" class="section level4 hasAnchor" number="4.3.2.2">
<h4><span class="header-section-number">4.3.2.2</span> Preliminary inferential analysis<a href="concepts-of-advanced-designs.html#preliminary-inferential-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Of more concern to a fully correct analysis is addressing why there appears to be a difference between the margarine groups at the “Before” stage. At that point, no margarine treatments had been administered, so if the subjects had been truly randomly assigned to the margarine groups (as they should be in a properly designed experiment!), we would have expected consistent cholesterol readings between the groups at that point. This can be formally tested as follows, with a simple independent samples <span class="math inline">\(t\)</span>-test comparing the mean cholesterol levels of the A and B groups at the “Before” stage:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="concepts-of-advanced-designs.html#cb279-1" tabindex="-1"></a>BeforeDataOnly <span class="ot">&lt;-</span> chol_tall <span class="sc">|&gt;</span></span>
<span id="cb279-2"><a href="concepts-of-advanced-designs.html#cb279-2" tabindex="-1"></a>  <span class="fu">filter</span>(time.pt <span class="sc">==</span> <span class="st">&quot;Before&quot;</span>)</span>
<span id="cb279-3"><a href="concepts-of-advanced-designs.html#cb279-3" tabindex="-1"></a><span class="fu">t.test</span>(chol.level <span class="sc">~</span> Margarine, <span class="at">data=</span>BeforeDataOnly, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  chol.level by Margarine
## t = -1.358, df = 16, p-value = 0.193
## alternative hypothesis: true difference in means between group A and group B is not equal to 0
## 95 percent confidence interval:
##  -1.906205  0.417316
## sample estimates:
## mean in group A mean in group B 
##         6.03556         6.78000</code></pre>
<p>The result is not statistically significant (<span class="math inline">\(p\)</span>-value = 0.1932).
This is actually good news here! Although visually it appears the two treatment groups had different initial cholesterol levels, they were not statistically different.</p>
</div>
<div id="a-conditional-repeated-measures-analysis" class="section level4 hasAnchor" number="4.3.2.3">
<h4><span class="header-section-number">4.3.2.3</span> A conditional repeated measures analysis<a href="concepts-of-advanced-designs.html#a-conditional-repeated-measures-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To better understand the idea of repeated measures, lets consider a simpler within-subjects (repeated measures) ANOVA.
We look at the effects of only Margarine A on cholesterol levels in time.
The goal here would be to see if there is an effective reduction in mean cholesterol over the eight-week trial by using margarine A.
Essentially, this is an extension of the classic Before and After study, but here we have two “after” measurements, for a total of 3 measurements per subject.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="concepts-of-advanced-designs.html#cb281-1" tabindex="-1"></a>MargarineA <span class="ot">&lt;-</span> chol_tall <span class="sc">|&gt;</span> </span>
<span id="cb281-2"><a href="concepts-of-advanced-designs.html#cb281-2" tabindex="-1"></a>  <span class="fu">filter</span>(Margarine <span class="sc">==</span> <span class="st">&quot;A&quot;</span>)</span>
<span id="cb281-3"><a href="concepts-of-advanced-designs.html#cb281-3" tabindex="-1"></a>RMaov_MargA <span class="ot">&lt;-</span> <span class="fu">aov</span>(chol.level <span class="sc">~</span> time.pt <span class="sc">+</span> <span class="fu">Error</span>(<span class="fu">factor</span>(ID)<span class="sc">/</span>time.pt), <span class="at">data=</span>MargarineA)</span>
<span id="cb281-4"><a href="concepts-of-advanced-designs.html#cb281-4" tabindex="-1"></a><span class="fu">summary</span>(RMaov_MargA)</span></code></pre></div>
<pre><code>## 
## Error: factor(ID)
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals  8   42.4     5.3               
## 
## Error: factor(ID):time.pt
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## time.pt    2  1.615   0.808     106 5.8e-10 ***
## Residuals 16  0.122   0.008                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The test of interest is labeled <code>time.pt</code>. It is significant (<span class="math inline">\(F\)</span> = 106.3, <span class="math inline">\(\textrm{df}_1\)</span> = 2, <span class="math inline">\(\textrm{df}_2\)</span> = 16, <span class="math inline">\(p\)</span>-value = <span class="math inline">\(5.7 \times 10^{-10}\)</span>). This tells us that when using Margarine A there is significant evidence to conclude that the <em>true mean cholesterol level differs between at least two of the time points</em>. Of course, that result on its own does not mean that the margarine is effective at reducing cholesterol levels.
All it says is that the mean cholesterol level is changing at some point over the experiment.
Since there are three time points, a multiple comparison procedure is warranted with the output below and in Figure <a href="concepts-of-advanced-designs.html#fig:ch4-12">4.13</a>.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="concepts-of-advanced-designs.html#cb283-1" tabindex="-1"></a>MargA.mc <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(RMaov_MargA, <span class="sc">~</span> time.pt)</span></code></pre></div>
<pre><code>## Note: re-fitting model with sum-to-zero contrasts</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="concepts-of-advanced-designs.html#cb285-1" tabindex="-1"></a><span class="fu">contrast</span>(MargA.mc, <span class="st">&quot;tukey&quot;</span>)</span></code></pre></div>
<pre><code>##  contrast                      estimate     SE df t.ratio p.value
##  Before - After 4 weeks          0.4856 0.0411 16  11.817  &lt;.0001
##  Before - After 8 weeks          0.5467 0.0411 16  13.304  &lt;.0001
##  After 4 weeks - After 8 weeks   0.0611 0.0411 16   1.487  0.3229
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="concepts-of-advanced-designs.html#cb287-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(MargA.mc, <span class="st">&quot;tukey&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-12"></span>
&lt;img src=“introStatModeling_files/figure-html/ch4-12-1.png” alt=“Comparing the effects of time within the Margarine A treatment groups. We see there is no statistical difference between 4 and 8 weeks after treatment begins but both differ comparied to the initial”before” measure of Cholestorol.” width=“70%” /&gt;
<p class="caption">
Figure 4.13: Comparing the effects of time within the Margarine A treatment groups. We see there is no statistical difference between 4 and 8 weeks after treatment begins but both differ comparied to the initial “before” measure of Cholestorol.
</p>
</div>
<p>The significant reductions in mean cholesterol level under Margarine A occurs right after the start of the experiment. The mean cholesterol level is reduced by 0.485 (SE = 0.041) by week 4 (<span class="math inline">\(p\)</span>-value &lt; 0.0001); and by 0.546 (SE = 0.041) by week 8 (<span class="math inline">\(p\)</span>-value &lt; 0.0001). There is no appreciable change in mean cholesterol level between weeks 4 and 8 (<span class="math inline">\(p\)</span>-value = 0.3229).</p>
</div>
<div id="full-analysis-formal-comparison-of-margarines" class="section level4 hasAnchor" number="4.3.2.4">
<h4><span class="header-section-number">4.3.2.4</span> Full analysis: Formal Comparison of Margarines<a href="concepts-of-advanced-designs.html#full-analysis-formal-comparison-of-margarines" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>It is critically important to know the structure of the data, which here stems from the design of the experiment.
In this case, we cannot just “compared the margarines” because there is a subject-level time profile under each margarine.
Since the same time points are observed under each margarine group, the factors margarine and <code>time.pt</code> are crossed effects, which means we have a <em>factorial data structure</em> (see section <a href="multiple-factor-designed-experiments.html#twoFactorDesigns">3.2</a>).
The <em>added wrinkle</em> here is that one of the two factors is a between-subjects factor (<code>Margarine</code>) and the other is within-subjects (<code>time.pt</code>).
This can be handled with a proper formula statement in <code>aov</code>:</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="concepts-of-advanced-designs.html#cb288-1" tabindex="-1"></a>RMaov_all <span class="ot">&lt;-</span> <span class="fu">aov</span>(chol.level <span class="sc">~</span> Margarine <span class="sc">+</span> time.pt <span class="sc">+</span> Margarine<span class="sc">:</span>time.pt <span class="sc">+</span> </span>
<span id="cb288-2"><a href="concepts-of-advanced-designs.html#cb288-2" tabindex="-1"></a>                              <span class="fu">Error</span>(<span class="fu">factor</span>(ID)<span class="sc">/</span>time.pt), <span class="at">data=</span>chol_tall)</span>
<span id="cb288-3"><a href="concepts-of-advanced-designs.html#cb288-3" tabindex="-1"></a><span class="fu">summary</span>(RMaov_all)</span></code></pre></div>
<pre><code>## 
## Error: factor(ID)
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Margarine  1    5.5    5.46    1.45   0.25
## Residuals 16   60.4    3.78               
## 
## Error: factor(ID):time.pt
##                   Df Sum Sq Mean Sq F value Pr(&gt;F)    
## time.pt            2   4.32   2.160  259.49 &lt;2e-16 ***
## Margarine:time.pt  2   0.08   0.040    4.78  0.015 *  
## Residuals         32   0.27   0.008                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As with the factorial models before, the first thing we must check is the significance of the most complext interaction term.
If this is significant, it means that the effect of time on the mean cholesterol is different between the two margarine types.
That is the case here (<span class="math inline">\(F\)</span> = 4.777, <span class="math inline">\(\textrm{df}_1\)</span> = 2, <span class="math inline">\(\textrm{df}_2\)</span> = 32, <span class="math inline">\(p\)</span>-value = 0.0153).
As a result, we should must complete multiple comparisons <strong>by conditioning on one of the two factors</strong>.
Experimental context will dictate which of the two factors is the more reasonable to condition on.
Here, we choose to condition on Margarine group, so we get a time-based comparison of mean cholesterol levels, but specific to each Margarine group, as seen in Figure <a href="concepts-of-advanced-designs.html#fig:ch4-14">4.14</a></p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="concepts-of-advanced-designs.html#cb290-1" tabindex="-1"></a>RMall.mc <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(RMaov_all, <span class="sc">~</span> time.pt <span class="sc">|</span> Margarine)</span></code></pre></div>
<pre><code>## Note: re-fitting model with sum-to-zero contrasts</code></pre>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="concepts-of-advanced-designs.html#cb292-1" tabindex="-1"></a><span class="fu">contrast</span>(RMall.mc, <span class="st">&quot;tukey&quot;</span>)</span></code></pre></div>
<pre><code>## Margarine = A:
##  contrast                      estimate    SE df t.ratio p.value
##  Before - After 4 weeks          0.4856 0.043 32  11.290  &lt;.0001
##  Before - After 8 weeks          0.5467 0.043 32  12.711  &lt;.0001
##  After 4 weeks - After 8 weeks   0.0611 0.043 32   1.421  0.3424
## 
## Margarine = B:
##  contrast                      estimate    SE df t.ratio p.value
##  Before - After 4 weeks          0.6467 0.043 32  15.036  &lt;.0001
##  Before - After 8 weeks          0.7111 0.043 32  16.535  &lt;.0001
##  After 4 weeks - After 8 weeks   0.0644 0.043 32   1.498  0.3051
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="concepts-of-advanced-designs.html#cb294-1" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">contrast</span>(RMall.mc, <span class="st">&quot;tukey&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch4-14"></span>
<img src="introStatModeling_files/figure-html/ch4-14-1.png" alt="Graphical exploration of all treatments noting that there is no statistical difference between 4 and 8 weeks after the study has began regardless of Margarine treatment." width="70%" />
<p class="caption">
Figure 4.14: Graphical exploration of all treatments noting that there is no statistical difference between 4 and 8 weeks after the study has began regardless of Margarine treatment.
</p>
</div>
<p>Even though at first glance the time-based comparisons look about the same between the two margarine types (Figure <a href="concepts-of-advanced-designs.html#fig:ch4-9">4.12</a>), the interval estimates and plots reveal the true story: the reductions in mean cholesterol following the initiation of the study are larger for margarine B (mean=0.7111 mmol/L, SE=0.043 by week 8) than for margarine A (mean=0.546 mmol/L, SE=0.043 by week 8).</p>
</div>
</div>
<div id="further-study" class="section level3 hasAnchor" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Further study<a href="concepts-of-advanced-designs.html#further-study" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>More thorough analysis of within-subjects and repeated measures designs are possible using advanced methods beyond the scope of this course.
These methods include:</p>
<ul>
<li>processes that allow the analyst to estimate the degree of correlation between repeated measurements</li>
<li>processes that allow one to model different correlation structures based upon experimental realities in the data collection process</li>
</ul>
<p>For example, suppose we had a repeated measures experiment with subjects measured across four time points: Week 1, 2, 3 and 8. Because of the time spacing, we might expect that measurements between adjacent weeks to be more similar within a subject than weeks far removed in time. That is, it is reasonable to expect that results in week 2 are more strongly correlated to week 1 results than would be the correlation between weeks 3 and 1.
Week 8 results might be so far removed from the first few weeks that the results there might be safely presumed to be nearly independent of earlier results. We could even be more restrictive, using an approach that assumes only adjacent time point results are correlated, but beyond that, assume independence.</p>
<p>Subtleties like these can be modeled and checked using advanced modeling techniques.</p>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-KutnerText" class="csl-entry">
Kutner, M. H., Nachtsheim, C., Neter, J. and Li, W., <em>Applied Linear Statistical Models</em>, New York, NY: McGraw-Hill Irwin, 2004.
</div>
<div id="ref-sheffield2021" class="csl-entry">
Sheffield, U. of, <a href="https://www.sheffield.ac.uk/mash/statistics/datasets">Mathematics and Statistics Help (MASH)</a>, <em>Datasets for Teaching - Statistics - MASH - The University of Sheffield</em>, January 2021.
</div>
<div id="ref-Sung1977" class="csl-entry">
Sung, Y. F., Kutner, M. H., Cerine, F. C. and Frederickson, E. L., Comparison of the Effects of Acupuncture and Codeine on Postoperative Dental Pain, <em>Anesth Analg</em>, vol. <strong>56</strong>, no. 4, pp. 473–78, July 1977.
</div>
<div id="ref-WeissText" class="csl-entry">
Weiss, N. A., <em>Introductory Statistics</em>, Pearson Education, 2012.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multiple-factor-designed-experiments.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-multiple-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["introStatModeling.pdf", "introStatModeling.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
