<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Introductory Statistics in R | Introduction to Statistical Modeling</title>
  <meta name="description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Introductory Statistics in R | Introduction to Statistical Modeling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  <meta name="github-repo" content="tjfisher19/introStatModeling" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Introductory Statistics in R | Introduction to Statistical Modeling" />
  
  <meta name="twitter:description" content="Covers Regression and elements of Design of Experiments in R using the tidyverse." />
  

<meta name="author" content="Michael R. Hughes and Thomas J. Fisher" />


<meta name="date" content="2025-12-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="important-preliminary-review.html"/>
<link rel="next" href="statistical-modeling-and-designed-experiments.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css_files/mystyle.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Inroduction to Statistical Modeling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html"><i class="fa fa-check"></i>Important Preliminary Review</a>
<ul>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#statistics-background"><i class="fa fa-check"></i>Statistics background</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#software"><i class="fa fa-check"></i>Software</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#add-on-packages"><i class="fa fa-check"></i>Add-on packages</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#help-with-rmarkdown"><i class="fa fa-check"></i>Help with RMarkdown</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#managing-your-work-in-r"><i class="fa fa-check"></i>Managing your work in R</a></li>
<li class="chapter" data-level="" data-path="important-preliminary-review.html"><a href="important-preliminary-review.html#data-in-this-text"><i class="fa fa-check"></i>Data in this text</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html"><i class="fa fa-check"></i><b>1</b> Introductory Statistics in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#goals-of-a-statistical-analysis"><i class="fa fa-check"></i><b>1.1</b> Goals of a statistical analysis</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#conducting-a-statistical-analysis"><i class="fa fa-check"></i><b>1.1.1</b> Conducting a statistical analysis</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#introduction-to-r"><i class="fa fa-check"></i><b>1.2</b> Introduction to R</a></li>
<li class="chapter" data-level="1.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#data-frames"><i class="fa fa-check"></i><b>1.3</b> Data frames</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#built-in-data"><i class="fa fa-check"></i><b>1.3.1</b> Built-in data</a></li>
<li class="chapter" data-level="1.3.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#dataTypesSection"><i class="fa fa-check"></i><b>1.3.2</b> Types of Data</a></li>
<li class="chapter" data-level="1.3.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#importing-datasets-into-r"><i class="fa fa-check"></i><b>1.3.3</b> Importing datasets into R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#referencing-data-from-inside-a-data-frame"><i class="fa fa-check"></i><b>1.4</b> Referencing data from inside a data frame</a></li>
<li class="chapter" data-level="1.5" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#missing-values-and-computer-arithmetic-in-r"><i class="fa fa-check"></i><b>1.5</b> Missing values and computer arithmetic in R</a></li>
<li class="chapter" data-level="1.6" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#exploratory-data-analysis-eda"><i class="fa fa-check"></i><b>1.6</b> Exploratory Data Analysis (EDA)</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#numeric-summaries"><i class="fa fa-check"></i><b>1.6.1</b> Numeric Summaries</a></li>
<li class="chapter" data-level="1.6.2" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#numericSummaries"><i class="fa fa-check"></i><b>1.6.2</b> Numeric Summaries in R</a></li>
<li class="chapter" data-level="1.6.3" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#graphical-summaries"><i class="fa fa-check"></i><b>1.6.3</b> Graphical Summaries</a></li>
<li class="chapter" data-level="1.6.4" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#distribution-of-univariate-variables"><i class="fa fa-check"></i><b>1.6.4</b> Distribution of Univariate Variables</a></li>
<li class="chapter" data-level="1.6.5" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-by-levels-of-a-factor-variable"><i class="fa fa-check"></i><b>1.6.5</b> Descriptive statistics and visualizations by levels of a factor variable</a></li>
<li class="chapter" data-level="1.6.6" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-for-two-numeric-variables"><i class="fa fa-check"></i><b>1.6.6</b> Descriptive statistics and visualizations for two numeric variables</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#sampling-distributions-describing-how-a-statistic-varies"><i class="fa fa-check"></i><b>1.7</b> Sampling distributions: describing how a statistic varies</a></li>
<li class="chapter" data-level="1.8" data-path="introductory-statistics-in-r.html"><a href="introductory-statistics-in-r.html#twoSampleInference"><i class="fa fa-check"></i><b>1.8</b> Two-sample inference</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html"><i class="fa fa-check"></i><b>2</b> Statistical Modeling and Designed Experiments</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#dataSources"><i class="fa fa-check"></i><b>2.1</b> Observational Studies versus designed experiments</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#observational-studies"><i class="fa fa-check"></i><b>2.1.1</b> Observational Studies</a></li>
<li class="chapter" data-level="2.1.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#designed-experiments"><i class="fa fa-check"></i><b>2.1.2</b> Designed experiments</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#designed-experiement-vocabulary"><i class="fa fa-check"></i><b>2.2</b> Designed experiement vocabulary</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#what-is-an-experiment"><i class="fa fa-check"></i><b>2.2.1</b> What is an experiment?</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#analysis-of-variance"><i class="fa fa-check"></i><b>2.2.2</b> Analysis of variance</a></li>
<li class="chapter" data-level="2.2.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#elements-of-a-designed-experiment"><i class="fa fa-check"></i><b>2.2.3</b> Elements of a designed experiment</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#statistical-analyses-is-modeling"><i class="fa fa-check"></i><b>2.3</b> Statistical Analyses is Modeling</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#example-of-a-two-sample-t-test-as-a-model"><i class="fa fa-check"></i><b>2.3.1</b> Example of a two-sample <span class="math inline">\(t\)</span>-test as a model</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#one-way-anova"><i class="fa fa-check"></i><b>2.4</b> One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#model-structure"><i class="fa fa-check"></i><b>2.4.1</b> Model Structure</a></li>
<li class="chapter" data-level="2.4.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#testing-procedure"><i class="fa fa-check"></i><b>2.4.2</b> Testing Procedure</a></li>
<li class="chapter" data-level="2.4.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#example-of-one-way-anova"><i class="fa fa-check"></i><b>2.4.3</b> Example of One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#assumptionCheck"><i class="fa fa-check"></i><b>2.5</b> Model Assumptions and Assessment</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#structural-assumptions"><i class="fa fa-check"></i><b>2.5.1</b> Structural Assumptions</a></li>
<li class="chapter" data-level="2.5.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#random-variation-assumptions"><i class="fa fa-check"></i><b>2.5.2</b> Random Variation Assumptions</a></li>
<li class="chapter" data-level="2.5.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#code-to-check-assumptions"><i class="fa fa-check"></i><b>2.5.3</b> Code to check assumptions</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#transforming-your-response"><i class="fa fa-check"></i><b>2.6</b> Transforming your response</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#a-note-on-logarithmic-transformations"><i class="fa fa-check"></i><b>2.6.1</b> A note on logarithmic transformations</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#anova-testing-in-r"><i class="fa fa-check"></i><b>2.7</b> ANOVA Testing in R</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#reading-an-anova-table"><i class="fa fa-check"></i><b>2.7.1</b> Reading an ANOVA table</a></li>
<li class="chapter" data-level="2.7.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#conclusions-and-limitation-of-anova"><i class="fa fa-check"></i><b>2.7.2</b> Conclusions and Limitation of ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#follow-up-procedures-multiple-comparisons"><i class="fa fa-check"></i><b>2.8</b> Follow-up procedures – Multiple Comparisons</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#multiple-testing-problem"><i class="fa fa-check"></i><b>2.8.1</b> Multiple testing problem</a></li>
<li class="chapter" data-level="2.8.2" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#tukeys-hsd-method"><i class="fa fa-check"></i><b>2.8.2</b> Tukey’s HSD method</a></li>
<li class="chapter" data-level="2.8.3" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#dunnett-multiple-comparisons"><i class="fa fa-check"></i><b>2.8.3</b> Dunnett multiple comparisons</a></li>
<li class="chapter" data-level="2.8.4" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#coding-notes-about-emmeans"><i class="fa fa-check"></i><b>2.8.4</b> Coding notes about <code>emmeans</code></a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#two-sample-t-test-as-anova"><i class="fa fa-check"></i><b>2.9</b> Two-sample <span class="math inline">\(t\)</span>-test as ANOVA</a></li>
<li class="chapter" data-level="2.10" data-path="statistical-modeling-and-designed-experiments.html"><a href="statistical-modeling-and-designed-experiments.html#completeOneWay"><i class="fa fa-check"></i><b>2.10</b> A Complete One-Way ANOVA Example</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html"><i class="fa fa-check"></i><b>3</b> Multiple Factor Designed Experiments</a>
<ul>
<li class="chapter" data-level="3.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#blockingSection"><i class="fa fa-check"></i><b>3.1</b> Blocking</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#model-form-of-a-randomized-block-design"><i class="fa fa-check"></i><b>3.1.1</b> Model form of a Randomized Block Design</a></li>
<li class="chapter" data-level="3.1.2" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#block-anova-example"><i class="fa fa-check"></i><b>3.1.2</b> Block ANOVA Example</a></li>
<li class="chapter" data-level="3.1.3" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#pairedTtest"><i class="fa fa-check"></i><b>3.1.3</b> Paired <span class="math inline">\(t\)</span>-test as a Block ANOVA</a></li>
<li class="chapter" data-level="3.1.4" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#another-block-anova-example"><i class="fa fa-check"></i><b>3.1.4</b> Another Block ANOVA Example</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#twoFactorDesigns"><i class="fa fa-check"></i><b>3.2</b> Two-factor Designs</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#analysis-of-a-two-factor-design"><i class="fa fa-check"></i><b>3.2.1</b> Analysis of a two-factor design</a></li>
<li class="chapter" data-level="3.2.2" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#highwaySigns"><i class="fa fa-check"></i><b>3.2.2</b> Example with No Significant Interaction</a></li>
<li class="chapter" data-level="3.2.3" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#twoWayInteraction"><i class="fa fa-check"></i><b>3.2.3</b> Example with Significant Interaction</a></li>
<li class="chapter" data-level="3.2.4" data-path="multiple-factor-designed-experiments.html"><a href="multiple-factor-designed-experiments.html#twoFactorAsOneFactor"><i class="fa fa-check"></i><b>3.2.4</b> Two-factor reformulated as a One-Factor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html"><i class="fa fa-check"></i><b>4</b> Concepts of Advanced Designs</a>
<ul>
<li class="chapter" data-level="4.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#higher-order-factor-models"><i class="fa fa-check"></i><b>4.1</b> Higher order factor models</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#model-form-of-three-factor-design"><i class="fa fa-check"></i><b>4.1.1</b> Model Form of Three-factor design</a></li>
<li class="chapter" data-level="4.1.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#three-factor-anova-example"><i class="fa fa-check"></i><b>4.1.2</b> Three-factor ANOVA Example</a></li>
<li class="chapter" data-level="4.1.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#summarizing-higher-order-factors"><i class="fa fa-check"></i><b>4.1.3</b> Summarizing higher order factors</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#combining-blocks-and-factorial-models"><i class="fa fa-check"></i><b>4.2</b> Combining Blocks and Factorial Models</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#dentalPainExample"><i class="fa fa-check"></i><b>4.2.1</b> Two-factor with Block Example</a></li>
<li class="chapter" data-level="4.2.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#eda-for-two-factor-with-block"><i class="fa fa-check"></i><b>4.2.2</b> EDA for two-factor with block</a></li>
<li class="chapter" data-level="4.2.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#fitting-two-factor-with-block-model"><i class="fa fa-check"></i><b>4.2.3</b> Fitting two-factor with block model</a></li>
<li class="chapter" data-level="4.2.4" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#multiple-comparisons-3"><i class="fa fa-check"></i><b>4.2.4</b> Multiple comparisons</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#within-subject-designs"><i class="fa fa-check"></i><b>4.3</b> Within-subject designs</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#blocks-revisited-an-approach-to-handling-within-subjects-factors"><i class="fa fa-check"></i><b>4.3.1</b> Blocks revisited: an approach to handling within-subjects factors</a></li>
<li class="chapter" data-level="4.3.2" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#repeated-measures-case-study"><i class="fa fa-check"></i><b>4.3.2</b> Repeated Measures Case Study</a></li>
<li class="chapter" data-level="4.3.3" data-path="concepts-of-advanced-designs.html"><a href="concepts-of-advanced-designs.html#further-study"><i class="fa fa-check"></i><b>4.3.3</b> Further study</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html"><i class="fa fa-check"></i><b>5</b> Introduction to Multiple Regression</a>
<ul>
<li class="chapter" data-level="5.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#regression-model"><i class="fa fa-check"></i><b>5.1</b> Regression Model</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>5.1.1</b> Simple Linear Regression</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#fitting-a-regression-model"><i class="fa fa-check"></i><b>5.2</b> Fitting a regression model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#simple-linear-regression-example"><i class="fa fa-check"></i><b>5.2.1</b> Simple Linear Regression Example</a></li>
<li class="chapter" data-level="5.2.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#multiple-regression-example"><i class="fa fa-check"></i><b>5.2.2</b> Multiple Regression Example</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#interpreting-beta-parameter-estimates-in-mlr"><i class="fa fa-check"></i><b>5.3</b> Interpreting <span class="math inline">\(\beta\)</span>-parameter estimates in MLR</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#designed-experiments-1"><i class="fa fa-check"></i><b>5.3.1</b> Designed experiments</a></li>
<li class="chapter" data-level="5.3.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-orthogonal-design"><i class="fa fa-check"></i><b>5.3.2</b> Example of Orthogonal Design</a></li>
<li class="chapter" data-level="5.3.3" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#observational-studies-1"><i class="fa fa-check"></i><b>5.3.3</b> Observational studies</a></li>
<li class="chapter" data-level="5.3.4" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-observational-regression-interpretation"><i class="fa fa-check"></i><b>5.3.4</b> Example of observational regression interpretation</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#whymultiple"><i class="fa fa-check"></i><b>5.4</b> Why multiple regression?</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-spurious-correlation"><i class="fa fa-check"></i><b>5.4.1</b> Example of Spurious Correlation</a></li>
<li class="chapter" data-level="5.4.2" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#example-of-confounding-in-regression"><i class="fa fa-check"></i><b>5.4.2</b> Example of Confounding in Regression</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="introduction-to-multiple-regression.html"><a href="introduction-to-multiple-regression.html#concluding-the-multiple-regression-model"><i class="fa fa-check"></i><b>5.5</b> Concluding the Multiple Regression Model</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regInferenceChp.html"><a href="regInferenceChp.html"><i class="fa fa-check"></i><b>6</b> Inference regarding Multiple Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#assumption-checking"><i class="fa fa-check"></i><b>6.1</b> Assumption checking</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-assumption-checking-in-slr"><i class="fa fa-check"></i><b>6.1.1</b> Example of Assumption Checking in SLR</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#overall-f-test-for-model-signifance"><i class="fa fa-check"></i><b>6.2</b> Overall <span class="math inline">\(F\)</span>-test for model signifance</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-model-overall-f-test"><i class="fa fa-check"></i><b>6.2.1</b> Example of model overall <span class="math inline">\(F\)</span>-test</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="regInferenceChp.html"><a href="regInferenceChp.html#individual-parameter-inference"><i class="fa fa-check"></i><b>6.3</b> Individual parameter inference</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#parameter-t-tests"><i class="fa fa-check"></i><b>6.3.1</b> Parameter <span class="math inline">\(t\)</span>-tests</a></li>
<li class="chapter" data-level="6.3.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-individual-parameter-t-test"><i class="fa fa-check"></i><b>6.3.2</b> Example of individual parameter <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="6.3.3" data-path="regInferenceChp.html"><a href="regInferenceChp.html#model-trimming"><i class="fa fa-check"></i><b>6.3.3</b> Model trimming</a></li>
<li class="chapter" data-level="6.3.4" data-path="regInferenceChp.html"><a href="regInferenceChp.html#confidence-intervals"><i class="fa fa-check"></i><b>6.3.4</b> Confidence Intervals</a></li>
<li class="chapter" data-level="6.3.5" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-individual-parameter-confidence-intervals"><i class="fa fa-check"></i><b>6.3.5</b> Example of individual parameter confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="regInferenceChp.html"><a href="regInferenceChp.html#confidence-and-prediction-bands"><i class="fa fa-check"></i><b>6.4</b> Confidence and prediction bands</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#simple-linear-regression-confident-and-prediction-bands"><i class="fa fa-check"></i><b>6.4.1</b> Simple Linear Regression Confident and Prediction bands</a></li>
<li class="chapter" data-level="6.4.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#example-of-confidence-and-prediction-intervals"><i class="fa fa-check"></i><b>6.4.2</b> Example of confidence and prediction intervals</a></li>
<li class="chapter" data-level="6.4.3" data-path="regInferenceChp.html"><a href="regInferenceChp.html#extrapolation-warning"><i class="fa fa-check"></i><b>6.4.3</b> Extrapolation warning!</a></li>
<li class="chapter" data-level="6.4.4" data-path="regInferenceChp.html"><a href="regInferenceChp.html#confidence-and-prediction-bands-in-multiple-regression"><i class="fa fa-check"></i><b>6.4.4</b> Confidence and Prediction Bands in Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="regInferenceChp.html"><a href="regInferenceChp.html#goodness-of-fit"><i class="fa fa-check"></i><b>6.5</b> Goodness-of-fit</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="regInferenceChp.html"><a href="regInferenceChp.html#coefficient-of-determination"><i class="fa fa-check"></i><b>6.5.1</b> Coefficient of determination</a></li>
<li class="chapter" data-level="6.5.2" data-path="regInferenceChp.html"><a href="regInferenceChp.html#akaikes-information-criterion"><i class="fa fa-check"></i><b>6.5.2</b> Akaike’s Information Criterion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html"><i class="fa fa-check"></i><b>7</b> More on multiple linear regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#model-comparision-reduced-f-tests"><i class="fa fa-check"></i><b>7.1</b> Model comparision – Reduced <span class="math inline">\(F\)</span>-tests</a></li>
<li class="chapter" data-level="7.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#categorical-predictor-variables"><i class="fa fa-check"></i><b>7.2</b> Categorical Predictor Variables</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#a-qualitative-predictor-with-two-levels"><i class="fa fa-check"></i><b>7.2.1</b> A qualitative predictor with two levels</a></li>
<li class="chapter" data-level="7.2.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#a-qualitative-predictor-with-more-than-two-levels"><i class="fa fa-check"></i><b>7.2.2</b> A qualitative predictor with more than two levels</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#bridging-regression-and-designed-experiments-ancova"><i class="fa fa-check"></i><b>7.3</b> Bridging Regression and Designed Experiments – ANCOVA</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#an-ancova-example-with-a-two-level-factor"><i class="fa fa-check"></i><b>7.3.1</b> An ANCOVA example with a two-level factor</a></li>
<li class="chapter" data-level="7.3.2" data-path="more-on-multiple-linear-regression.html"><a href="more-on-multiple-linear-regression.html#ancova-with-a-multi-level-factor"><i class="fa fa-check"></i><b>7.3.2</b> ANCOVA with a multi-level factor</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="model-building-considerations.html"><a href="model-building-considerations.html"><i class="fa fa-check"></i><b>8</b> Model Building Considerations</a>
<ul>
<li class="chapter" data-level="8.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#regression-assumptions-revisited"><i class="fa fa-check"></i><b>8.1</b> Regression assumptions revisited</a></li>
<li class="chapter" data-level="8.2" data-path="model-building-considerations.html"><a href="model-building-considerations.html#violations-of-the-independence-assumption"><i class="fa fa-check"></i><b>8.2</b> Violations of the independence assumption</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#collecting-data-that-are-temporal-or-spatial-in-nature"><i class="fa fa-check"></i><b>8.2.1</b> Collecting data that are temporal or spatial in nature</a></li>
<li class="chapter" data-level="8.2.2" data-path="model-building-considerations.html"><a href="model-building-considerations.html#pseudoreplication"><i class="fa fa-check"></i><b>8.2.2</b> Pseudoreplication</a></li>
<li class="chapter" data-level="8.2.3" data-path="model-building-considerations.html"><a href="model-building-considerations.html#what-if-we-have-non-independent-errors"><i class="fa fa-check"></i><b>8.2.3</b> What if we have non-independent errors?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="model-building-considerations.html"><a href="model-building-considerations.html#constant-variance-violations"><i class="fa fa-check"></i><b>8.3</b> Constant Variance Violations</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="model-building-considerations.html"><a href="model-building-considerations.html#box-cox-power-tranformations"><i class="fa fa-check"></i><b>8.3.1</b> Box-Cox Power Tranformations</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="model-building-considerations.html"><a href="model-building-considerations.html#normality-violations"><i class="fa fa-check"></i><b>8.4</b> Normality violations</a></li>
<li class="chapter" data-level="8.5" data-path="model-building-considerations.html"><a href="model-building-considerations.html#violations-of-the-linearity-assumption"><i class="fa fa-check"></i><b>8.5</b> Violations of the linearity assumption</a></li>
<li class="chapter" data-level="8.6" data-path="model-building-considerations.html"><a href="model-building-considerations.html#detecting-and-dealing-with-unusual-observations"><i class="fa fa-check"></i><b>8.6</b> Detecting and dealing with unusual observations</a></li>
<li class="chapter" data-level="8.7" data-path="model-building-considerations.html"><a href="model-building-considerations.html#multicollinearity"><i class="fa fa-check"></i><b>8.7</b> Multicollinearity</a></li>
<li class="chapter" data-level="8.8" data-path="model-building-considerations.html"><a href="model-building-considerations.html#standardizingPredictors"><i class="fa fa-check"></i><b>8.8</b> Scale changes</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>9</b> Model Selection</a>
<ul>
<li class="chapter" data-level="9.1" data-path="model-selection.html"><a href="model-selection.html#stepwise-procedures"><i class="fa fa-check"></i><b>9.1</b> Stepwise Procedures</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="model-selection.html"><a href="model-selection.html#backward-selection"><i class="fa fa-check"></i><b>9.1.1</b> Backward Selection</a></li>
<li class="chapter" data-level="9.1.2" data-path="model-selection.html"><a href="model-selection.html#forward-selection"><i class="fa fa-check"></i><b>9.1.2</b> Forward selection</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="model-selection.html"><a href="model-selection.html#best-subsets"><i class="fa fa-check"></i><b>9.2</b> Best subsets</a></li>
<li class="chapter" data-level="9.3" data-path="model-selection.html"><a href="model-selection.html#shrinkage-methods"><i class="fa fa-check"></i><b>9.3</b> Shrinkage Methods</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="model-validation.html"><a href="model-validation.html"><i class="fa fa-check"></i><b>10</b> Model Validation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="model-validation.html"><a href="model-validation.html#underfitting-vs.-overfitting-models"><i class="fa fa-check"></i><b>10.1</b> Underfitting vs. Overfitting Models</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="model-validation.html"><a href="model-validation.html#the-bias-variance-trade-off"><i class="fa fa-check"></i><b>10.1.1</b> The Bias-Variance Trade-off</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="model-validation.html"><a href="model-validation.html#validation-techniques"><i class="fa fa-check"></i><b>10.2</b> Validation Techniques</a></li>
<li class="chapter" data-level="10.3" data-path="model-validation.html"><a href="model-validation.html#basic-validation-with-a-single-holdout-sample"><i class="fa fa-check"></i><b>10.3</b> Basic Validation with a single holdout sample</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="model-validation.html"><a href="model-validation.html#use-the-training-data-to-fit-and-select-models"><i class="fa fa-check"></i><b>10.3.1</b> Use the training data to fit and select models</a></li>
<li class="chapter" data-level="10.3.2" data-path="model-validation.html"><a href="model-validation.html#model-training"><i class="fa fa-check"></i><b>10.3.2</b> Model training:</a></li>
<li class="chapter" data-level="10.3.3" data-path="model-validation.html"><a href="model-validation.html#model-validation-step"><i class="fa fa-check"></i><b>10.3.3</b> Model validation step:</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="model-validation.html"><a href="model-validation.html#hold-out-sample-validation-using-caret"><i class="fa fa-check"></i><b>10.4</b> Hold-out sample validation using <code>caret</code></a></li>
<li class="chapter" data-level="10.5" data-path="model-validation.html"><a href="model-validation.html#leave-one-out-cross-validation-loocv"><i class="fa fa-check"></i><b>10.5</b> “Leave one out” Cross-Validation (LOOCV)</a></li>
<li class="chapter" data-level="10.6" data-path="model-validation.html"><a href="model-validation.html#k-fold-cross-validation"><i class="fa fa-check"></i><b>10.6</b> <span class="math inline">\(k\)</span>-fold Cross-Validation</a></li>
<li class="chapter" data-level="10.7" data-path="model-validation.html"><a href="model-validation.html#a-final-note"><i class="fa fa-check"></i><b>10.7</b> A final note</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="statistical-odds.html"><a href="statistical-odds.html"><i class="fa fa-check"></i><b>11</b> Statistical Odds</a>
<ul>
<li class="chapter" data-level="11.1" data-path="statistical-odds.html"><a href="statistical-odds.html#probability-versus-odds"><i class="fa fa-check"></i><b>11.1</b> Probability versus Odds</a></li>
<li class="chapter" data-level="11.2" data-path="statistical-odds.html"><a href="statistical-odds.html#odds-ratios"><i class="fa fa-check"></i><b>11.2</b> Odds ratios</a></li>
<li class="chapter" data-level="11.3" data-path="statistical-odds.html"><a href="statistical-odds.html#ideas-of-modeling-odds"><i class="fa fa-check"></i><b>11.3</b> Ideas of modeling odds</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-model"><i class="fa fa-check"></i><b>12.1</b> Logistic Model</a></li>
<li class="chapter" data-level="12.2" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-interpreting-and-assessing-a-logistic-model"><i class="fa fa-check"></i><b>12.2</b> Fitting, Interpreting and assessing a logistic model</a></li>
<li class="chapter" data-level="12.3" data-path="logistic-regression.html"><a href="logistic-regression.html#case-study---titanic-dataset"><i class="fa fa-check"></i><b>12.3</b> Case Study - Titanic Dataset</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>13</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="13.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression"><i class="fa fa-check"></i><b>13.1</b> Poisson Regression</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-distribution"><i class="fa fa-check"></i><b>13.1.1</b> Poisson distribution</a></li>
<li class="chapter" data-level="13.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression-development"><i class="fa fa-check"></i><b>13.1.2</b> Poisson Regression Development</a></li>
<li class="chapter" data-level="13.1.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#example---tropical-cyclone-counts-in-the-north-atlantic"><i class="fa fa-check"></i><b>13.1.3</b> Example - Tropical Cyclone Counts in the North Atlantic</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#handling-overdispersion"><i class="fa fa-check"></i><b>13.2</b> Handling overdispersion</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#example-attendnace-records"><i class="fa fa-check"></i><b>13.2.1</b> Example – Attendnace Records</a></li>
<li class="chapter" data-level="13.2.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#incorrect-poisson-model"><i class="fa fa-check"></i><b>13.2.2</b> Incorrect Poisson Model</a></li>
<li class="chapter" data-level="13.2.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#a-quasi-poisson-approach"><i class="fa fa-check"></i><b>13.2.3</b> A quasi-Poisson approach</a></li>
<li class="chapter" data-level="13.2.4" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#fitting-a-negative-binomial-regression"><i class="fa fa-check"></i><b>13.2.4</b> Fitting a Negative Binomial regression</a></li>
<li class="chapter" data-level="13.2.5" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#picking-between-quasi-poisson-and-negative-binomial"><i class="fa fa-check"></i><b>13.2.5</b> Picking between Quasi-Poisson and Negative Binomial</a></li>
<li class="chapter" data-level="13.2.6" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#infererence-on-predictor-variables"><i class="fa fa-check"></i><b>13.2.6</b> Infererence on predictor variables</a></li>
<li class="chapter" data-level="13.2.7" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#plotting-fitted-model"><i class="fa fa-check"></i><b>13.2.7</b> Plotting fitted model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Modeling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introductory-statistics-in-r" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Introductory Statistics in R<a href="introductory-statistics-in-r.html#introductory-statistics-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>We begin our dive into Statistical Modeling by first reviewing content from introductory statistics and introduce fundamental elements of the R programming language <span class="citation">(<a href="#ref-R-base">R Core Team, 2019</a>)</span>. The learning objective of this chapter include:</p>
<ul>
<li>Review of the fundamental concepts of <em>populations</em>, <em>samples</em>, <em>parameters</em> and <em>statistics</em>.</li>
<li>Review of exploratory and descriptive statistics: numerical quantities and graphs.</li>
<li>An introduction and overview of the R software for statistical computing.</li>
<li>Basic statistical inference through a two-sample <span class="math inline">\(t\)</span>-test and confidence intervals.</li>
</ul>
<div id="goals-of-a-statistical-analysis" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Goals of a statistical analysis<a href="introductory-statistics-in-r.html#goals-of-a-statistical-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The field of <strong>Statistics</strong> can broadly be defined as the study of variation.</p>
<p>We collect <strong>sample</strong> data from a parent <strong>population</strong> of interest. Ultimately, we are interested in characteristics or <strong>parameters</strong> about the <strong>population</strong>. We use a <strong>sample</strong> because it is unfeasible or overly costly to collect data from every member of a <strong>population</strong> (that process is known as a <em>census</em>).</p>
<p>Good statistical practice demands that we collect the <strong>sample</strong> data from the <strong>population</strong> in such a manner so as to ensure that the <strong>sample</strong> is representative; <em>i.e.</em>, it is not presenting a systematic bias in its representation. With a <em>good</em> sample, we can make decisions about the population using that sample.</p>
<p>There are two main sources of variation that arise in statistical analysis:</p>
<ol style="list-style-type: decimal">
<li><p>Measurements of the same attribute will vary from observation to observation. This is natural and is to be expected. Consider how your height may vary compared to your parents and siblings. This <em>random</em> (or <em>stochastic</em>) component is typically modeled through probabilistic assumptions (think the <em>Normal</em> distribution from your Intro Stat course). This component is often called <em>noise</em> or <em>error</em>, although the later is a misnomer.</p></li>
<li><p>We are interested in some <strong>parameter</strong> that helps describes characteristics of the population. Any characteristic computed from the sample is known as a sample <strong>statistic</strong>. Ideally, this <strong>statistic</strong> will reasonably approximate the <strong>parameter</strong> of interest. Since only a subset of the population is used in the calculation of a <strong>statistic</strong>, it will <em>vary</em> from their corresponding population <strong>parameter</strong>. In fact, different samples from the same population will produce different estimates of the same parameter, so sample statistics also vary from sample to sample.</p></li>
</ol>
<p>This variation gives rise to the concept of uncertainty in any findings we make about a population based on sample data. A meaningful statistical analysis helps quantify this uncertainty.</p>
<p>The <strong>goals</strong> of a statistical analysis typically are</p>
<ul>
<li>to make sense of data in the face of uncertainty,</li>
<li>to meaningfully describe the patterns of variation in collected sample data,
<ul>
<li>and use this information to make reliable inferences/generalizations about the parent population.</li>
</ul></li>
</ul>
<div id="conducting-a-statistical-analysis" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Conducting a statistical analysis<a href="introductory-statistics-in-r.html#conducting-a-statistical-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The practice of statistics starts with an underlying problem or contextual question. Prior to performing an analysis, we must that original question. Some examples may include:</p>
<ul>
<li>Are fish sensitive to Ultraviolet light?</li>
<li>What socio-economic variables and demographics predict college graduation rates?</li>
<li>Can we determine if there truly is a <em>home field</em> advantage in sports?</li>
<li>Does a new experimental drug improve over an existing drug?</li>
</ul>
<p>From there, data is collected through an experiment, by observation or via a survey. You then proceed with a data analysis, and then finish with statistical and contextual conclusions.</p>
<p>Unfortunately, it is common for inexperienced statisticians to start with a complex analysis without ever considering the objectives of the study. It is also common for inexperienced statisticians to not consider whether the data are appropriate for the chosen analysis and whether the underlying question can be answered.</p>
<p>We recommend you follow the guidance (outlined below) provided in Chapter 1 of the text by <span class="citation">Faraway (<a href="#ref-Faraway2004linear">2004</a>)</span> – Look before you leap!</p>
<p><strong>Problem formulation</strong> - To perform statistical analysis correctly, you should:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Understand the context</strong>. Statisticians often work in collaboration with researchers in other disciplines and need to understand something about the subject area. You should regard this as an opportunity to learn something new. In essence, a Statistician must be a renaissance person – some level of <em>elementary</em> expertise is needed in the subject area.</p></li>
<li><p><strong>Understand the objectives</strong>. Again, often you will be working with a collaborator who may not be clear about their objectives. Ideally they approach a statistician before data collection. This helps alleviate several potential issues. The statistician can grain an understanding of the contextual problem, and assess the appropriateness of data collection procedure to answer the underlying contextual questions.</p></li>
</ol>
<p>Beware of contextual problems that are “fishing expeditions”: if you look hard enough, you’ll almost always find something. But… that something may just be a coincidence of no meaningful consequence. Also, sometimes collaborators request a more complicated analysis is performed than is necessary. You may find that simple descriptive statistics are all that are really required. Even if a more complex analysis is necessary, simple descriptive statistics can provide a valuable supplement.</p>
<ol start="3" style="list-style-type: decimal">
<li><strong>Translate the problem into statistical terms</strong>. This can be a challenging step and oftentimes requires creativity on the part of the statistician (in other words, not every problem fits into a neat little box like in an intro stats course!). Care must be taken at this step.</li>
</ol>
<p>Connected to the above guidance is a good understanding of the <strong>Data Collection</strong> - It is vitally important to understand how the data was collected. Consider:</p>
<ul>
<li>Are the data observational or experimental? Are the data a “sample of convenience”, or were they obtained via random sampling? Did the experiment include randomization? How the data were collected has a crucial impact on what conclusions can be meaningfully made. We discuss this topic more in Section <a href="statistical-modeling-and-designed-experiments.html#dataSources">2.1</a>.</li>
<li>Is there “non-response”? The data you don’t see may be just as important as the data you do see! This aligns with the concern of whether a sample is representative of the intended target population.</li>
<li>Are there missing values? This is a common problem that can be troublesome in some applications but not a concern in others. Data that are “missing” according to some pattern or systematic procedure are particularly troublesome.</li>
<li>How are the data coded? In particular, how are the qualitative or categorical variables represented? This is important on the implementation of statistical methods in R (and other languages).</li>
<li>What are the units of measurement? Sometimes data are collected or represented using far more digits than are necessary. Consider rounding if this will help with the interpretation.</li>
<li>Beware of data entry errors. This problem is all too common, and is almost a certainty in any real dataset of at least moderate size. Perform some data sanity checks.</li>
</ul>
</div>
</div>
<div id="introduction-to-r" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Introduction to R<a href="introductory-statistics-in-r.html#introduction-to-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Much like a chemist using test tubes &amp; beakers, or a microbiologist using a microscope, the <em>laboratory instrument</em> for modern statistics is the computer. Many software packages exist to aid a modern statistician in the conducting of an analysis. This text uses the <strong>R Language and Environment for Statistical Computing</strong> <span class="citation">(<a href="#ref-R-base">R Core Team, 2019</a>)</span>. Many other tools exist and they can generally be lumped into two categories: <em>point and click</em> interfaces, and <em>coding</em> languages. The <em>point and click</em> tools tend to be easier to use but may have limited features &amp; methods available. The <em>coding</em> languages are substantially more versatile, powerful and provide solutions that are reproducible, but may have a steeper learning curve. We recap a few of the common tools below.</p>
<ul>
<li><strong>Excel</strong> - Microsoft Excel is a common <em>point and click</em> spreadsheet tool that includes many statistical methods. In fact, it is possible you used Excel in your Introductory Statistics course.</li>
<li><strong>SPSS</strong> - Also known as the Statistical Package for the Social Sciences, SPSS looks similar to Excel but has many more statistical tools included. SPSS includes the ability to code in Python.</li>
<li><strong>Minitab</strong> - Another <em>point and click</em> statistical tool. It’s appearance is similar to Excel but, similar to SPSS, includes most common statistical methods.</li>
<li><strong>JMP</strong> - Pronounced as “jump”. This tool includes a graphical interface (much like Excel) but also provides the user the ability to code. It is commonly used in the design of experiments and some intro stat courses.</li>
<li><strong>SAS</strong> - arguable the first statistical software that was widely used. SAS is a coding language that has powerful data handling abilities and includes implementations for many statistical methods. There is a graphical version known as Enterprise Miner.</li>
<li><strong>Python</strong> - A high-level general-purpose programming language, Python has become very popular in the Data Science industry due to its ease of use, the large community of support and add-ons (called modules) that implement data analysis methods.</li>
</ul>
<p><strong>So why R??</strong> - With so many tools available, you may ask, “why do we use R?” Simply put, R incorporates many of the features available in these other languages. Specifically,</p>
<ul>
<li>Similar to the other coding languages, R provides reproducible results!</li>
<li>R is free!</li>
<li>Installing a working version of R tends to be easier than Python.</li>
<li>Similar to Python, R is fairly easy to learn.
<ul>
<li>But unlike in Python, performing statistical analysis in R is a bit more straightforward.</li>
<li>With Python, many Interactive Development Environments are popular, but RStudio is the standard for coding in R - this makes implementation in the classroom a bit easier since everyone uses the same tools.</li>
</ul></li>
<li>Similar to Python, R includes add-ons. In R we call them <em>packages</em> and we will make use of several.
<ul>
<li>Users can create their own packages to share with others!</li>
</ul></li>
<li>Similar to SAS, R has powerful data handling features and implementations for many statistical methods.</li>
</ul>
</div>
<div id="data-frames" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Data frames<a href="introductory-statistics-in-r.html#data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A statistical dataset in R is known as a data frame, or <code>data.frame</code>.
It is a rectangular array of information (essentially a table or matrix or or spreadsheet). Rows of a data frame constitute different <em>observations</em> and the columns constitute different <em>variables</em> measured.</p>
<p>For example, imagine we record the name, class standing, height and age of all the students in a class: the first column will record each students’ name, with the second column recording their standing (<em>e.g.</em>, junior, senior, etc…), the third column records the students’ height and fourth column their age. Each row corresponds to a particular student (an observation) and each column a different property of that student (a variable).</p>
<div id="built-in-data" class="section level3 hasAnchor" number="1.3.1">
<h3><span class="header-section-number">1.3.1</span> Built-in data<a href="introductory-statistics-in-r.html#built-in-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>R packages come bundled with many pre-entered datasets for exploration purposes. For example, here is the data frame <code>stackloss</code> from the <code>datasets</code> package (which loads automatically upon starting R):</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="introductory-statistics-in-r.html#cb2-1" tabindex="-1"></a>stackloss</span></code></pre></div>
<pre><code>##    Air.Flow Water.Temp Acid.Conc. stack.loss
## 1        80         27         89         42
## 2        80         27         88         37
## 3        75         25         90         37
## 4        62         24         87         28
## 5        62         22         87         18
## 6        62         23         87         18
## 7        62         24         93         19
## 8        62         24         93         20
## 9        58         23         87         15
## 10       58         18         80         14
## 11       58         18         89         14
## 12       58         17         88         13
## 13       58         18         82         11
## 14       58         19         93         12
## 15       50         18         89          8
## 16       50         18         86          7
## 17       50         19         72          8
## 18       50         19         79          8
## 19       50         20         80          9
## 20       56         20         82         15
## 21       70         20         91         15</code></pre>
<p>This data frame contains 21 observations on 4 different variables. Note the listing of the variable names, this is known as the <em>header</em>.</p>
<p>Another famous dataset is the Edgar Anderson’s Iris data and is included in R:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="introductory-statistics-in-r.html#cb4-1" tabindex="-1"></a><span class="fu">head</span>(iris, <span class="at">n=</span><span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1           5.1         3.5          1.4         0.2  setosa
## 2           4.9         3.0          1.4         0.2  setosa
## 3           4.7         3.2          1.3         0.2  setosa
## 4           4.6         3.1          1.5         0.2  setosa
## 5           5.0         3.6          1.4         0.2  setosa
## 6           5.4         3.9          1.7         0.4  setosa
## 7           4.6         3.4          1.4         0.3  setosa
## 8           5.0         3.4          1.5         0.2  setosa
## 9           4.4         2.9          1.4         0.2  setosa
## 10          4.9         3.1          1.5         0.1  setosa</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="introductory-statistics-in-r.html#cb6-1" tabindex="-1"></a><span class="fu">tail</span>(iris, <span class="at">n=</span><span class="dv">7</span>)</span></code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 144          6.8         3.2          5.9         2.3 virginica
## 145          6.7         3.3          5.7         2.5 virginica
## 146          6.7         3.0          5.2         2.3 virginica
## 147          6.3         2.5          5.0         1.9 virginica
## 148          6.5         3.0          5.2         2.0 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9         3.0          5.1         1.8 virginica</code></pre>
<p>Here the <code>head()</code> function prints the first few observations of the dataset, we specified the first 10 rows. The <code>tail()</code> functions prints out the last <code>n</code> rows (here specified to be 7). The size of the dataset is actually bigger and can be determined with the <code>dim</code> function,</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="introductory-statistics-in-r.html#cb8-1" tabindex="-1"></a><span class="fu">dim</span>(iris)</span></code></pre></div>
<pre><code>## [1] 150   5</code></pre>
<p>There are 150 observations on 5 variables (<code>Sepal.Length</code>, <code>Sepal.Width</code>, <code>Petal.Length</code>, <code>Petal.Width</code>, and <code>Species</code>).</p>
<p>Another useful function to quickly look at data is the <code>glimpse()</code> function in the R package <code>dplyr</code>, part of the <code>tidyverse</code> collection of packages <span class="citation">(<a href="#ref-R-tidyverse">Wickham, 2017</a>)</span>. Here we apply the function to the built in dataset <code>esoph</code>, which is from a case-control study on esophageal cancer.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="introductory-statistics-in-r.html#cb10-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb10-2"><a href="introductory-statistics-in-r.html#cb10-2" tabindex="-1"></a><span class="fu">glimpse</span>(esoph)</span></code></pre></div>
<pre><code>## Rows: 88
## Columns: 5
## $ agegp     &lt;ord&gt; 25-34, 25-34, 25-34, 25-34, 25-34, 25-34, 25-34, 25-34, 25-3…
## $ alcgp     &lt;ord&gt; 0-39g/day, 0-39g/day, 0-39g/day, 0-39g/day, 40-79, 40-79, 40…
## $ tobgp     &lt;ord&gt; 0-9g/day, 10-19, 20-29, 30+, 0-9g/day, 10-19, 20-29, 30+, 0-…
## $ ncases    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, …
## $ ncontrols &lt;dbl&gt; 40, 10, 6, 5, 27, 7, 4, 7, 2, 1, 2, 1, 0, 1, 2, 60, 13, 7, 8…</code></pre>
<p>There are 88 observations in this study with 5 recorded variables.</p>
</div>
<div id="dataTypesSection" class="section level3 hasAnchor" number="1.3.2">
<h3><span class="header-section-number">1.3.2</span> Types of Data<a href="introductory-statistics-in-r.html#dataTypesSection" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>You’ll notice in the above examples we see a mix of numeric and character values in the data frames. In R, every object has a type or <em>class</em>. To discover the type for a specific variable use the <code>class</code> function,</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="introductory-statistics-in-r.html#cb12-1" tabindex="-1"></a><span class="fu">class</span>(iris)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>We see that the class of the object <code>iris</code> is a <code>data.frame</code> consisting of 150 rows and 5 columns. You should also note from above that the first four columns are numeric while the last column appears to be characters. We can explore the class of each variable by specifying the name of the column of the dataset using the <code>$</code> notation. First, let’s get the list of variables in the dataset using the <code>names()</code> function.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="introductory-statistics-in-r.html#cb14-1" tabindex="-1"></a><span class="fu">names</span>(iris)</span></code></pre></div>
<pre><code>## [1] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot;  &quot;Petal.Length&quot; &quot;Petal.Width&quot;  &quot;Species&quot;</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="introductory-statistics-in-r.html#cb16-1" tabindex="-1"></a><span class="fu">class</span>(iris<span class="sc">$</span>Sepal.Length)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="introductory-statistics-in-r.html#cb18-1" tabindex="-1"></a><span class="fu">class</span>(iris<span class="sc">$</span>Species)</span></code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>The <code>class</code> of <code>Sepal.Length</code> is numeric, which should not be too surprising given the values are numbers. The <code>class</code> of <code>Species</code> on the other hand is a <code>factor</code>. In R, a <code>factor</code> is <strong>a categorical variable!</strong> Here it happens to be labeled with the scientific species name, but R treats it as a <strong>category</strong>.</p>
<p><strong>Note</strong>: The <code>factor</code> class can be quite important when performing Statistics. Specifically, when categories are coded as numbers it can be problematic. Depending if a variable is a <code>factor</code> or <code>numeric</code>, it can cause statistical methods to perform differently.</p>
</div>
<div id="importing-datasets-into-r" class="section level3 hasAnchor" number="1.3.3">
<h3><span class="header-section-number">1.3.3</span> Importing datasets into R<a href="introductory-statistics-in-r.html#importing-datasets-into-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In practice you will often encounter datasets from other external sources. These are most commonly created or provided in formats that can be read in Excel. The best formats for importing dataset files into R is space-delimited (typically with the file extension <code>.txt</code>), tab-delimited text (either the file extension <code>.txt</code> or <code>.tsv</code>) or comma-separated values (file extension <code>.csv</code>). R can handle other formats, but these are the easiest with which to work.</p>
<p>There are multiple functions to import a data file in R. The tools we will outline here include many functions in the <code>readr</code> package <span class="citation">(<a href="#ref-R-readr">Wickham and Hester, 2021</a>)</span>, part of the <code>tidyverse</code>. We recommend reading through the Vignette by running the command <code>vignette("readr")</code> in the console.</p>
<div id="read_table-for-space-delimited-files" class="section level4 hasAnchor" number="1.3.3.1">
<h4><span class="header-section-number">1.3.3.1</span> <code>read_table()</code> – for Space delimited files<a href="introductory-statistics-in-r.html#read_table-for-space-delimited-files" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>One common tool is the <code>read_table()</code> command. Below are two examples:</p>
<ol style="list-style-type: decimal">
<li>Read a file directly from the web. The below code imports the file <code>univadmissions.txt</code> (details about the data are below) from the textbook data repository into the current R session, and assigns the name <code>uadata</code> to the data frame object:</li>
</ol>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="introductory-statistics-in-r.html#cb20-1" tabindex="-1"></a>site <span class="ot">&lt;-</span> <span class="st">&quot;https://tjfisher19.github.io/introStatModeling/data/univadmissions.txt&quot;</span></span>
<span id="cb20-2"><a href="introductory-statistics-in-r.html#cb20-2" tabindex="-1"></a><span class="fu">class</span>(site)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="introductory-statistics-in-r.html#cb22-1" tabindex="-1"></a><span class="fu">options</span>(<span class="at">readr.show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb22-2"><a href="introductory-statistics-in-r.html#cb22-2" tabindex="-1"></a>uadata <span class="ot">&lt;-</span> <span class="fu">read_table</span>(site)</span>
<span id="cb22-3"><a href="introductory-statistics-in-r.html#cb22-3" tabindex="-1"></a><span class="fu">head</span>(uadata)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##      id gpa.endyr1 hs.pct   act  year
##   &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1       0.98     61    20  1996
## 2     2       1.13     84    20  1996
## 3     3       1.25     74    19  1996
## 4     4       1.32     95    23  1996
## 5     5       1.48     77    28  1996
## 6     6       1.57     47    23  1996</code></pre>
<p>A few notes on the above code. In the first line, we are creating a string of characters (that happens to be a web address) and <em>assigning</em> it to the R object <code>site</code> using the <code>&lt;-</code> notation. You should note the <code>class</code> of the object <code>site</code> is <code>character</code>. The third line, <code>options(readr.show_col_types = FALSE)</code>, is <em>entirely optional</em> and tells the <code>readr</code> package to suppress some extra output from display. The key is we are applying the function <code>read_table()</code> with the file specified in the <code>site</code> variable. Lastly, the output of the function is being assigned to <code>uadata</code>, again using the <code>&lt;-</code> notation. We will be using this same data again below.</p>
<ol start="2" style="list-style-type: decimal">
<li>Another option is to download the file to your computer, then read it. You could go to the URL above and save the data file to your default working directory on your computer. After saving it into a folder (or directory), you can read the file with code similar to:</li>
</ol>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="introductory-statistics-in-r.html#cb24-1" tabindex="-1"></a>uadata <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">&quot;univadmissions.txt&quot;</span>)</span></code></pre></div>
<p>If you save the file to a directory on your computer other than the local directory (where your R code is stored), you must provide the path in the <code>read_table()</code> command:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="introductory-statistics-in-r.html#cb25-1" tabindex="-1"></a>uadata <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">&quot;C:/My Documents/My STA363 Files/univadmissions.txt&quot;</span>)</span></code></pre></div>
<p>The function <code>read_table()</code> automatically converts a space delimited text file to a data frame in R.</p>
</div>
<div id="read_csv-for-comma-separated-value-files" class="section level4 hasAnchor" number="1.3.3.2">
<h4><span class="header-section-number">1.3.3.2</span> <code>read_csv()</code> – for Comma Separated Value files<a href="introductory-statistics-in-r.html#read_csv-for-comma-separated-value-files" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Similar to the above examples, reading in a Comma Separated Value (CSV) file is very similar. This is becoming the standard format for transferring files. An example of some <strong>non-executed code</strong> is provided below:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="introductory-statistics-in-r.html#cb26-1" tabindex="-1"></a>uadata_csv <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;c:/My Documents/My STA363 Files/univadmissions.csv&quot;</span>)</span></code></pre></div>
<p><strong>Note:</strong> the file <code>univadmissions.csv</code> does not exist but this code has been included for example purposes.</p>
</div>
<div id="load-loading-an-existing-r-data.frame" class="section level4 hasAnchor" number="1.3.3.3">
<h4><span class="header-section-number">1.3.3.3</span> <code>load()</code> – Loading an existing R <code>data.frame</code><a href="introductory-statistics-in-r.html#load-loading-an-existing-r-data.frame" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If data has already been input and processed into R as a <code>data.frame</code>, it can be saved in a format designed for R using the <code>save()</code> function and then can be reloaded using <code>load()</code>. For example, first we may save the University Admidssion data</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="introductory-statistics-in-r.html#cb27-1" tabindex="-1"></a><span class="fu">save</span>(uadata, <span class="at">file=</span><span class="st">&quot;uaDataInRformat.RData&quot;</span>)</span></code></pre></div>
<p>Then, sometime later, we may “load” that data into R</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="introductory-statistics-in-r.html#cb28-1" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;uaDataInRformat.RData&quot;</span>)</span></code></pre></div>
</div>
</div>
</div>
<div id="referencing-data-from-inside-a-data-frame" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Referencing data from inside a data frame<a href="introductory-statistics-in-r.html#referencing-data-from-inside-a-data-frame" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We saw above that we can access a specific variable within a dataset using the <code>$</code> notation. We can also access specific observations in the dataset based on rules we may wish to implement. As a working example we will consider the university admissions data we read in above.</p>
<p><strong>Example:</strong> University admissions (originally in <span class="citation">Kutner et al. (<a href="#ref-KutnerText">2004</a>)</span>).</p>
<p>The director of admissions at a state university wanted to determine how accurately students’ grade point averages at the end of their freshman year could be predicted by entrance test scores and high school class rank. The academic years covered 1996 through 2000. This example uses the <code>univadmissions.txt</code> dataset in the repository. The variables are as follows:</p>
<ul>
<li><code>id</code> – Identification number</li>
<li><code>gpa.endyr1</code> – Grade point average following freshman year</li>
<li><code>hs.pct</code> – High school class rank (as a percentile)</li>
<li><code>act</code> – ACT entrance exam score</li>
<li><code>year</code> – Calendar year the freshman entered university</li>
</ul>
<p>This is the first dataset we input above in the <code>uadata</code> data frame.</p>
<p>The <code>tidyverse</code> package <span class="citation">(<a href="#ref-R-tidyverse">Wickham, 2017</a>)</span> is actually a wrapper for many R packages. One of the key packages we use for data processing is the <code>dplyr</code> package <span class="citation">(<a href="#ref-R-dplyr">Wickham, François, et al., 2021</a>)</span>. It includes many functions that are similar to <a href="https://www.tutorialspoint.com/sql/sql-overview.htm">SQL</a> (for those who know it). These tools tend to be very readable and easy to understand. First we will load the package <code>tidyverse</code> and then take a <em>glimpse</em> of the dataset:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="introductory-statistics-in-r.html#cb29-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   <span class="co"># Load the necessary package</span></span>
<span id="cb29-2"><a href="introductory-statistics-in-r.html#cb29-2" tabindex="-1"></a><span class="fu">glimpse</span>(uadata)      <span class="co"># Take a glimpse at the data</span></span></code></pre></div>
<pre><code>## Rows: 705
## Columns: 5
## $ id         &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …
## $ gpa.endyr1 &lt;dbl&gt; 0.98, 1.13, 1.25, 1.32, 1.48, 1.57, 1.67, 1.73, 1.75, 1.76,…
## $ hs.pct     &lt;dbl&gt; 61, 84, 74, 95, 77, 47, 67, 69, 83, 72, 83, 66, 76, 88, 46,…
## $ act        &lt;dbl&gt; 20, 20, 19, 23, 28, 23, 28, 20, 22, 24, 27, 21, 23, 27, 21,…
## $ year       &lt;dbl&gt; 1996, 1996, 1996, 1996, 1996, 1996, 1996, 1996, 1996, 1996,…</code></pre>
<p>In the code above, you may note that everything to the right of a <code>#</code> is a <em>comment</em> – this is, text included in code that does function or execute as code. Comments are a useful tool to provide notes to use yourself about the code.</p>
<p>Key features when using the <code>tidyverse</code> is the pipe command, <code>|&gt;</code> and <em>actions</em> on a <code>data.frame</code>. These <em>actions</em> are function calls and other sources may call them <em>verbs</em>, as you are performing some action on he data. We will introduce the function calls as needed.</p>
<p><strong>Note:</strong> there are actually two different syntax for using the pipe in R, <code>|&gt;</code> and <code>%&gt;%</code>. In the original version of this text, we used the latter <code>%&gt;%</code> as the newer <code>|&gt;</code> was not included in previous versions of R. At this point, <code>|&gt;</code> is preferred but some examples may still use the older <code>%&gt;%</code> notation.</p>
<p>As an example of some basic data processing, consider the case of extracting students with a GPA greater than 3.9:</p>
<ul>
<li>Take the <code>data.frame</code> <code>uadata</code> (from above) and pipe it (send it) to a function (or action), in this case the <em>filter</em> function.</li>
<li>Then <code>filter</code> it based on some criteria, say <code>gpa.endyr1 &gt; 3.9</code>.</li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="introductory-statistics-in-r.html#cb31-1" tabindex="-1"></a>uadata <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="introductory-statistics-in-r.html#cb31-2" tabindex="-1"></a>  <span class="fu">filter</span>(gpa.endyr1 <span class="sc">&gt;</span> <span class="fl">3.9</span>)</span></code></pre></div>
<pre><code>## # A tibble: 29 × 5
##       id gpa.endyr1 hs.pct   act  year
##    &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1   138       3.91     99    28  1996
##  2   139       3.92     93    28  1996
##  3   140       4        99    25  1996
##  4   141       4        92    28  1996
##  5   142       4        99    33  1996
##  6   266       3.92     85    15  1997
##  7   267       3.92     63    23  1997
##  8   268       3.92     98    23  1997
##  9   269       3.93     99    29  1997
## 10   270       3.96     99    29  1997
## # ℹ 19 more rows</code></pre>
<p>Another useful <code>dplyr</code> command for choosing specific variables is the <code>select</code> function. Below we select the ACT scores for students who have a first year GPA greater than 3.9 and with a graduating year of 1998.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="introductory-statistics-in-r.html#cb33-1" tabindex="-1"></a>uadata <span class="sc">|&gt;</span></span>
<span id="cb33-2"><a href="introductory-statistics-in-r.html#cb33-2" tabindex="-1"></a>  <span class="fu">filter</span>(gpa.endyr1 <span class="sc">&gt;</span> <span class="fl">3.9</span>, </span>
<span id="cb33-3"><a href="introductory-statistics-in-r.html#cb33-3" tabindex="-1"></a>         year<span class="sc">==</span><span class="dv">1998</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="introductory-statistics-in-r.html#cb33-4" tabindex="-1"></a>  <span class="fu">select</span>(act)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 1
##     act
##   &lt;dbl&gt;
## 1    28
## 2    31
## 3    31
## 4    21
## 5    27
## 6    32</code></pre>
<p>Note in the above, we take the <code>uadata</code> and pipe it to a <code>filter</code>, which selects only those observations with <code>gpa.endyr1</code> greater than 3.9 and <code>year</code> equal (<code>==</code>) to 1998, then we pipe that subset of the data to the <code>select</code> function that returns the variable <code>act</code>.</p>
<p><strong>IMPORTANT NOTE</strong> - R is <strong>an <em>evolving</em> language</strong> and as such occasionally has some wonky behavior. In fact, there are multiple versions of both the <code>filter</code> and <code>select</code> functions in R. If you ever use one and receive a strange error (<code>comparison is possible only for atomic and list types</code> or an <code>unused argument</code> error), first check for a typo. If the error still occurs it is likely the case that R is trying to use a different version of the <code>filter</code> or <code>select</code>. You can always force R to use the <code>dplyr</code> version by specifying the package as in the below example:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="introductory-statistics-in-r.html#cb35-1" tabindex="-1"></a>uadata <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="introductory-statistics-in-r.html#cb35-2" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(gpa.endyr1 <span class="sc">&gt;</span> <span class="fl">3.9</span>, </span>
<span id="cb35-3"><a href="introductory-statistics-in-r.html#cb35-3" tabindex="-1"></a>                year<span class="sc">==</span><span class="dv">1998</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="introductory-statistics-in-r.html#cb35-4" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(act)</span></code></pre></div>
</div>
<div id="missing-values-and-computer-arithmetic-in-r" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Missing values and computer arithmetic in R<a href="introductory-statistics-in-r.html#missing-values-and-computer-arithmetic-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sometimes data from an individual is lost or not available, these are known as missing values. R indicates such occurrences using the value <code>NA</code>. Missing values often need to be addressed because simply ignoring them when performing certain functions will result in no useful output.</p>
<p>As an example, we cannot find the mean of the elements of a data vector when some are set to <code>NA</code>. Consider the simple case of a vector of 6 values with one <code>NA</code>.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="introductory-statistics-in-r.html#cb36-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">14</span>, <span class="dv">18</span>, <span class="dv">12</span>, <span class="cn">NA</span>, <span class="dv">22</span>, <span class="dv">16</span>)</span>
<span id="cb36-2"><a href="introductory-statistics-in-r.html#cb36-2" tabindex="-1"></a><span class="fu">class</span>(x)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="introductory-statistics-in-r.html#cb38-1" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>Here, the object <code>x</code> is a <em>vector</em> of class <code>numeric</code>. We will not be working with vectors much in this class (although a column in a data frame can be considered a vector) but we do so here to demonstrate functionality.</p>
<p>Since one of the observations is missing, <code>NA</code>, the mean of the vector is also “not available” or <code>NA</code>.<br />
This is not incorrect: logically speaking there is no way to know the mean of these observations when one of them is missing. However, in many cases we may still wish to calculate the mean of the non-missing observations.</p>
<p><strong>Many R functions have a <code>na.rm=</code> logical argument</strong>, which is set to <code>FALSE</code> by default. It basically asks if you want to skip, or remove, the missing values before applying the function. It can be set to <code>TRUE</code> in order to remove the <code>NA</code> terms. For example,</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="introductory-statistics-in-r.html#cb40-1" tabindex="-1"></a><span class="fu">mean</span>(x, <span class="at">na.rm=</span><span class="cn">TRUE</span>)    <span class="co"># mean of the non-missing elements</span></span></code></pre></div>
<pre><code>## [1] 16.4</code></pre>
<p>The number system used by R has the following ways of accommodating results of calculations on missing values or extreme values:</p>
<ul>
<li><p><code>NA</code>: <strong>Not Available</strong>. Any data value, numeric or not, can be <code>NA</code>. This is what you use for missing data. Always use <code>NA</code> for this purpose.</p></li>
<li><p><code>NaN</code>: <strong>Not a Number</strong>. This is a special value that only numeric variables can take. It is the result of an undefined operation such as 0/0.</p></li>
<li><p><code>Inf</code>: <strong>Infinity</strong>. Numeric variables can also take the values <code>-Inf</code> and <code>Inf</code>. These are produced by the low level arithmetic of all modern computers by operations such as 1/0. (You should not think of these as values as real infinities, but rather the result of the correct calculation if the computer could handle extremely large (or extremely small, near 0) numbers; that is, results that are larger than the largest numbers the computer can hold (about <span class="math inline">\(10^{300}\)</span>)).</p></li>
</ul>
<p><strong>Scientific notation</strong>. This is a shorthand way of displaying very small or very large numbers. For example, if R displays <code>3e-8</code> as a value, it means <span class="math inline">\(3\times 10^{-8} = 0.00000003\)</span>. Similarly, <code>1.2e4</code> is <span class="math inline">\(1.2\times 10^4 = 12000\)</span>.</p>
</div>
<div id="exploratory-data-analysis-eda" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Exploratory Data Analysis (EDA)<a href="introductory-statistics-in-r.html#exploratory-data-analysis-eda" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The material presented in this section is typically called <em>descriptive statistics</em> in Intro Statistics books. This is an important step that should always be performed prior to a formal analysis. It looks simple but it is vital to conducting a meaningful analysis. EDA is comprised of:</p>
<ul>
<li>Numerical summaries
<ul>
<li>Means &amp; medians (measures of centrality)</li>
<li>Standard deviations, range, Interquartile Range (IQR) (measures of spread)</li>
<li>Percentiles/quantiles &amp; Five-number summaries (assessment of distributions)</li>
<li>Correlations (measures of association)</li>
</ul></li>
<li>Graphical summaries
<ul>
<li>One variable: boxplots, histograms, density plots, etc.</li>
<li>Two variables: scatterplots, side-by-side boxplots, overlaid density plots</li>
<li>Many variables: scatterplot matrices, interactive graphics</li>
</ul></li>
</ul>
<p>We look for outliers, data-entry errors, skewness or unusual distributions using EDA.
We may ask ourselves: “are the data distributed as you expect?”
Getting data into a form suitable for analysis by cleaning out mistakes and aberrations is often time consuming.
It often takes more time than the data analysis itself!
In this course, data will usually be ready to analyze but we will occasionally intermix messy data.
You should realize that in practice it is rare to receive <em>clean</em> data.</p>
<div id="numeric-summaries" class="section level3 hasAnchor" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Numeric Summaries<a href="introductory-statistics-in-r.html#numeric-summaries" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="measures-of-centrality-and-quantiles" class="section level4 hasAnchor" number="1.6.1.1">
<h4><span class="header-section-number">1.6.1.1</span> Measures of centrality and quantiles<a href="introductory-statistics-in-r.html#measures-of-centrality-and-quantiles" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Common descriptive measures of centrality and quantiles from a sample include</p>
<ul>
<li>Sample mean – typically denoted by <span class="math inline">\(\bar{x}\)</span>, this is implemented in the function <code>mean()</code></li>
<li>Sample median – this is implemented in the function <code>median()</code></li>
<li>Quantiles – Quantiles, or sample percentiles, can be found using the <code>quantile()</code> function.
<ul>
<li>Three common quantiles are <span class="math inline">\(Q_1\)</span> (the sample <span class="math inline">\(25^\mathrm{th}\)</span> percentile, or first quartile), <span class="math inline">\(Q_2\)</span> (the <span class="math inline">\(50^\mathrm{th}\)</span> percentile, second quartile or <em>median</em>) and <span class="math inline">\(Q_3\)</span> (the sample <span class="math inline">\(75^\mathrm{th}\)</span> percentile or third quartile).</li>
</ul></li>
<li>Min and Max – the Minimum and Maximum values of a sample can be found using the <code>min()</code> or <code>max()</code> functions.</li>
</ul>
<p>Each of these measures are covered in a typical introductory statistics course. We refer you to that material for more details.</p>
</div>
<div id="variabilityDiscussion" class="section level4 hasAnchor" number="1.6.1.2">
<h4><span class="header-section-number">1.6.1.2</span> Measuring variability<a href="introductory-statistics-in-r.html#variabilityDiscussion" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Earlier we defined statistics as the ‘study of variation’. The truth is that everything naturally varies:</p>
<ul>
<li>If you measure the same characteristic on two different individuals, you would likely get two different values (subject variability).
<ul>
<li><em>e.g.</em>, the pulse rate of two individuals is likely to be different.</li>
</ul></li>
<li>If you measure the same characteristic twice on the same individual, you may get two different values (measurement error).
<ul>
<li><em>e.g.</em>, if two different people manually measured someone’s pulse rate, you may get different results.</li>
</ul></li>
<li>If you measure the same characteristic on the same individual but at different times, you would potentially get two different values (temporal variability).
<ul>
<li><em>e.g.</em>, measuring someone’s pulse rate while resting compared to while performing exercise sometime later.</li>
</ul></li>
</ul>
<p>Because almost everything varies, simply determining that a variable <em>varies</em> is not very interesting.
The goal is to find a way to discriminate between variation that is scientifically interesting and variation that reflects background fluctuations that occur naturally.
This is what the science of statistics does!</p>
<p>Having some intuition about the amount of variation that we would expect to occur just by chance alone when nothing scientifically interesting is key.
If we observe bigger differences than we would expect by chance alone, we may say the result is statistically significant.
If instead we observe differences no larger than we would expect by chance alone, we say the result is not statistically significant.</p>
<p>Although often covered in introductory statistics courses, due to importance we review measuring the variance of a sample.</p>
<p><strong>Variance</strong></p>
<p>A <em>variance</em> is a numeric descriptor of the variation of a quantity.
Variances will serve as the foundation for much of what we use in making statistical inferences in this course.
In fact, a standard method of data analysis for many of the problems we will encounter is known as analysis of variance (shorthanded ANOVA).</p>
<p>You were exposed to variance in your introductory statistics course.
What is crucial now is that you understand what you are finding the variance of; <em>i.e.</em>, what is the “quantity” we referred to in the preceding paragraph?
Consider the following example:</p>
<ul>
<li><p><em>Example</em>. Suppose you collect a simple random sample of fasting blood glucose measurements from a population of <span class="math inline">\(n\)</span> diabetic patients, where <span class="math inline">\(n\)</span> is the standard notation for the size of a sample. The measurements, or observations, are denoted <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(x_n\)</span>. What are some of the different “variances” that one might encounter in this scenario?</p>
<ol style="list-style-type: decimal">
<li>The <span class="math inline">\(n\)</span> sampled measurements vary around their sample mean <span class="math inline">\(\bar{x}\)</span>. This is called the sample variance (traditionally denoted <span class="math inline">\(s^2\)</span>). The formula for <span class="math inline">\(s^2\)</span> is provided below. In R, we compute this with the function <code>var()</code>.</li>
<li>All fasting blood glucose values in the population vary around the true mean of the population (typically denoted with <span class="math inline">\(\mu\)</span>, the lowercase Greek ‘mu’). This is called the population variance (usually denoted <span class="math inline">\(\sigma^2\)</span> where <span class="math inline">\(\sigma\)</span> is the lowercase Greek ‘sigma’). Note that <span class="math inline">\(\sigma^2\)</span> cannot be calculated without a census of the entire population, so <span class="math inline">\(s^2\)</span> serves as an estimate of <span class="math inline">\(\sigma^2\)</span>.</li>
<li><span class="math inline">\(\bar{x}\)</span> is only a sample estimate of <span class="math inline">\(\mu\)</span>, so we should expect that it will vary depending on which <span class="math inline">\(n\)</span> individual diabetic patients are sampled (<em>i.e.</em>, with a different sample we will calculate a different sample mean). This is called the variance of <span class="math inline">\(\bar{x}\)</span>, and is denoted <span class="math inline">\(\sigma_{\bar{x}}^2\)</span>. This variance, unlike the sample or population variance, describes how sample estimates of <span class="math inline">\(\mu\)</span> vary around <span class="math inline">\(\mu\)</span> itself. We will need to estimate <span class="math inline">\(\sigma_{\bar{x}}^2\)</span>, since it cannot be determined without a full survey of the population. The estimate of <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> is denoted <span class="math inline">\(s_{\bar{x}}^2\)</span>.</li>
</ol></li>
</ul>
<p>The variances cited above are each different measures. Even more measures of variability exist; for example, each different possible random sample of <span class="math inline">\(n\)</span> patients will produce a different sample variance <span class="math inline">\(s^2\)</span>. Since these would all be estimates of the population variance <span class="math inline">\(\sigma^2\)</span>, we could even find the variance of the sample variances!</p>
<p>Some formulas:</p>
<p><span class="math display">\[\textbf{Sample Variance:}~~~ s^2 = \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2, \textrm{ for sample size } n\]</span></p>
<p><span class="math display">\[\textbf{Estimated Variance of}~ \bar{x}:~~~ s^2_{\bar{x}} = \frac{s^2}{n}\]</span></p>
<p>Three important notes:</p>
<ol style="list-style-type: decimal">
<li>The general form of any variance is a sum of squared deviations, divided by a quantity related to the number of independent elements in the sum known as the <strong>degrees of freedom</strong>. So in general,</li>
</ol>
<p><span class="math display">\[\textrm{Variance} = \frac{\textrm{sum of square deviations}}{\textrm{degrees of freedom}} = \frac{SS}{\textrm{df}}\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li><p>The formula for the population variance <span class="math inline">\(\sigma^2\)</span> is omitted since it is rarely used and requires the <span class="math inline">\(\mu\)</span> to be a known value. In practice, this can only be calculated with a population census.</p></li>
<li><p>When considering how a statistic (like <span class="math inline">\(\bar{x}\)</span>) varies around the parameter it is estimating (<span class="math inline">\(\mu\)</span>), it makes sense that the more data you have, the better it should perform as an estimator. This is precisely why the variance of <span class="math inline">\(\bar{x}\)</span> is inversely related to the sample size <span class="math inline">\(n\)</span>. <strong>As</strong> <span class="math inline">\(n\)</span> <strong>increases</strong>, the variance of the estimate decreases; <em>i.e.</em>, the estimate will be closer to the thing it is estimating. This phenomenon is known as the law of large numbers and is typically discussed in Introductory Statistics courses.</p></li>
</ol>
<p><strong>Standard deviations and standard errors</strong></p>
<p>While variances are the usual items of interest for statistical testing, variances are always in units squared (look at the equation for <span class="math inline">\(s^2\)</span> above).
Often we will find that a description of variation in the original units of the quantity being studied is preferred, so we take their square roots and are back to the original units. The square root of a variance is called a <strong>standard deviation</strong> (SD).
The square root of the variance of an estimate is called the <strong>standard error</strong> (SE) of the estimate:</p>
<p><span class="math display">\[\textbf{Sample Standard Deviation:}~~~ s = \sqrt{s^2} = \sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2}, ~~~\textrm{ for sample size } n\]</span></p>
<p><span class="math display">\[\textbf{Standard error of}~ \bar{x}:~~~ s_{\bar{x}} = \sqrt{s^2_{\bar{x}}} = \sqrt{\frac{s^2}{n}} = \frac{s}{\sqrt{n}}\]</span></p>
</div>
</div>
<div id="numericSummaries" class="section level3 hasAnchor" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> Numeric Summaries in R<a href="introductory-statistics-in-r.html#numericSummaries" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We recommend using <code>dplyr</code> for data handling and summary statistics. We can pipe (<code>|&gt;</code>) our data frame into a function to calculate numeric summaries, this function is <code>summarize()</code>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="introductory-statistics-in-r.html#cb42-1" tabindex="-1"></a>uadata <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="introductory-statistics-in-r.html#cb42-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to=</span><span class="st">&quot;Variable&quot;</span>, <span class="at">values_to=</span><span class="st">&quot;value&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb42-3"><a href="introductory-statistics-in-r.html#cb42-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Variable) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="introductory-statistics-in-r.html#cb42-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb42-5"><a href="introductory-statistics-in-r.html#cb42-5" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="at">Mean=</span>mean, <span class="at">SD=</span>sd, <span class="at">Min=</span>min, <span class="at">Median=</span>median, <span class="at">Max=</span>max) ) )</span></code></pre></div>
<pre><code>## # A tibble: 5 × 6
##   Variable   value_Mean value_SD value_Min value_Median value_Max
##   &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;
## 1 act             24.5     4.01      13           25           35
## 2 gpa.endyr1       2.98    0.635      0.51         3.05         4
## 3 hs.pct          77.0    18.6        4           81           99
## 4 id             353     204.         1          353          705
## 5 year          1998       1.40    1996         1998         2000</code></pre>
<p>For a brief moment ignore the code (we described below). Presented here are the mean, standard deviation, the minimum, median and maximum of each numeric variable in the University Admissions data frame. For example, the mean freshman year-end GPA over the period 1996-2000 was 2.98; the median over the same period was 3.05, suggesting the GPA distribution is slightly skewed left (not surprising). The range of the GPA distribution is from 0.51 to 4. The median ACT score for entering freshman was 25, and and the range of ACT scores was from 13 to 35.</p>
<div id="coding-notes" class="section level4 hasAnchor" number="1.6.2.1">
<h4><span class="header-section-number">1.6.2.1</span> Coding Notes<a href="introductory-statistics-in-r.html#coding-notes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In <code>tidyverse</code> there is package called <code>tidyr</code> <span class="citation">(<a href="#ref-R-tidyr">Wickham, 2021</a>)</span> which is mainly comprised of two main functions: <code>pivot_longer()</code> and <code>pivot_wider()</code>.
The purpose of the <code>pivot_longer()</code> function is to collect variables in a dataset and create a <em>tall</em> (or <em>longer</em>) dataset (this is typically known as going from wide-to-tall or wide-to-long format).
We specify the variables (or columns) we want to pivot (here we pivot on everything, thus <code>everything()</code> in the code), the name of the new variable (here called <code>Variable</code>) storing the column names, and the variable name that will store the values (here called <code>value</code>).
The <code>pivot_wider()</code> function essentially does the opposite, turning a tall data frame into a wide format.</p>
<p>In <code>dplyr</code> resides the function <code>group_by()</code>.
This function essentially does some <em>internal organization</em> of our data.
Specifically, for each unique <code>Variable</code> name, it would group the data together.
So, all the <code>gpa.endyr1</code> values will be considered a group, and separate from all the <code>hs.pct</code> and <code>act</code> <em>groups</em>.
This function is particularly useful when coupled with <code>summarize()</code> (such as in the example above) because summary statistics will be calculated for each group.</p>
<p>The function <code>summarize()</code> tells R to calculate summary statistics across rows (or grouped rows) within a <code>data.frame</code>. In the above example, we compute a list of summary statistics (hence, <code>list(Mean=mean, SD=sd, Min=min, Median=median, Max=max)</code>) on all the non-grouped variables (<code>everything()</code>). We will see more examples below.</p>
<p>The code above introduces a few keys points to know:</p>
<ul>
<li>The code is spread across multiple lines with most lines ending with the piping operator <code>|&gt;</code>. This is done for readability (and recommended by all users of R). When performing an analysis, you often will revisit the code at a later time. Readable code is paramount to reproducibility.</li>
<li>The <code>tidyverse</code> structure of data processing is meant to be highly readable. Look back at the code and consider the following:
<ul>
<li>We get the university admissions data, and then send it to (<code>uadata |&gt;</code>)</li>
<li>the function <code>pivot_longer()</code> that takes all columns, or variables (<code>everything()</code>) in the data set and stacks them on top of one another where a new variable called <code>Variable</code> designates the variable from the wide version of the data, and the new variable <code>Values</code> provides the corresponding value, and then send it to (<code>|&gt;</code>)</li>
<li>a function that internally organizes the dataset, treating all <code>Values</code> with the same <code>Variable</code> value as a group (<code>group_by(Variable)</code>), and then send it to (<code>|&gt;</code>)</li>
<li>a function that will calculate summary statistics (<code>summarize()</code>). This includes the mean, standard deviation, minimum, median and maximum of the <code>Values</code> for each <code>Variable</code> value since the data had been grouped.</li>
</ul></li>
</ul>
<p>Also note:</p>
<ul>
<li>Since we applied the command to the entire data frame (<code>everything()</code>), we also see numeric summaries of the variable <code>id</code>, even though it is meaningless to do. (note: just because a computer outputs it, that doesn’t mean it’s useful)</li>
<li>If you look carefully, you’ll note that <code>year</code> is treated as a number as well (<em>e.g.</em>, 1996, 1997, etc.). However, that doesn’t necessarily mean it should be treated as a numeric variable! It is meaningless to find numeric summaries, such as means or medians, for the <code>year</code> variable because it is qualitative (categorical) variable in the context of these data (again, just because a computer outputs it, that does not mean it is contextually correct).</li>
</ul>
<p>These are common mistake to make. When R encounters a variable whose values are entered as numbers in a data frame, R will treat the variable as if it were a numeric variable (whether it is contextually or not).
If R encounters a variable whose values are character strings, R will treat the variable as a categorical <code>factor</code>.
But, in a case like <code>year</code> or <code>id</code> above, you have to explicitly tell R that the variable is really a <code>factor</code> since it was coded with numbers.
To do this, we will <code>mutate</code> the variables <code>id</code> and <code>year</code> and turn them into factors.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="introductory-statistics-in-r.html#cb44-1" tabindex="-1"></a>uadata <span class="ot">&lt;-</span> uadata <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="introductory-statistics-in-r.html#cb44-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">id=</span><span class="fu">factor</span>(id),</span>
<span id="cb44-3"><a href="introductory-statistics-in-r.html#cb44-3" tabindex="-1"></a>         <span class="at">year=</span><span class="fu">factor</span>(year))</span></code></pre></div>
<p>Here we tell R to take the <code>uadata</code> data, pipe it to the <code>mutate</code> function (which allows us to create and/or replace variables by changing/mutating them). We then assign the variables <code>id</code> and <code>year</code> as versions of themselves that are being treated as <em>factors</em> (or categories).</p>
<p>We can then check the type of each variable by <em>summarizing</em> over <em>all</em> the variables using the <code>class</code> function.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="introductory-statistics-in-r.html#cb45-1" tabindex="-1"></a>uadata <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="introductory-statistics-in-r.html#cb45-2" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), class))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 5
##   id     gpa.endyr1 hs.pct  act     year  
##   &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt; 
## 1 factor numeric    numeric numeric factor</code></pre>
<p>Now calculate the summary statistics for only numeric variables (<em>i.e.</em>, the use of the <code>select(where(is.numeric))</code> function).</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="introductory-statistics-in-r.html#cb47-1" tabindex="-1"></a>uadata <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="introductory-statistics-in-r.html#cb47-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="introductory-statistics-in-r.html#cb47-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to=</span><span class="st">&quot;Variable&quot;</span>, <span class="at">values_to=</span><span class="st">&quot;value&quot;</span>) <span class="sc">|&gt;</span> </span>
<span id="cb47-4"><a href="introductory-statistics-in-r.html#cb47-4" tabindex="-1"></a>  <span class="fu">group_by</span>(Variable) <span class="sc">|&gt;</span></span>
<span id="cb47-5"><a href="introductory-statistics-in-r.html#cb47-5" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb47-6"><a href="introductory-statistics-in-r.html#cb47-6" tabindex="-1"></a>                   <span class="fu">list</span>(<span class="at">Mean=</span>mean, <span class="at">SD=</span>sd, <span class="at">Min=</span>min, <span class="at">Median=</span>median, <span class="at">Max=</span>max) ) )</span></code></pre></div>
<pre><code>## # A tibble: 3 × 6
##   Variable   value_Mean value_SD value_Min value_Median value_Max
##   &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;     &lt;dbl&gt;
## 1 act             24.5     4.01      13           25           35
## 2 gpa.endyr1       2.98    0.635      0.51         3.05         4
## 3 hs.pct          77.0    18.6        4           81           99</code></pre>
<p>When a dataset includes categorical variables, the main numeric measure to consider is the count (or proportions) of each category. To do this in R, we tell it to treat each category as a <em>group</em> and then count within the group. We will <code>group_by</code> the <code>year</code> and then within that year, count the number of observations (<code>summarize(Count=n() )</code>. We also add a new variable (using <code>mutate</code>) that is the proportion.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="introductory-statistics-in-r.html#cb49-1" tabindex="-1"></a>uadata <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="introductory-statistics-in-r.html#cb49-2" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="introductory-statistics-in-r.html#cb49-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Count=</span><span class="fu">n</span>() ) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="introductory-statistics-in-r.html#cb49-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Prop =</span> Count<span class="sc">/</span><span class="fu">sum</span>(Count))</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   year  Count  Prop
##   &lt;fct&gt; &lt;int&gt; &lt;dbl&gt;
## 1 1996    142 0.201
## 2 1997    131 0.186
## 3 1998    154 0.218
## 4 1999    141 0.2  
## 5 2000    137 0.194</code></pre>
<p>Note the power of using the <code>tidyverse</code> tools <span class="citation">(<a href="#ref-R-tidyverse">Wickham, 2017</a>)</span>.
We are only <em>scratching the surface</em> of what can be done here.
For more information, we recommend looking into the <em>Wrangling</em> chapters in the book <a href="https://r4ds.had.co.nz/index.html">R for Data Science</a> <span class="citation">(<a href="#ref-Wickham2017R">Wickham et al., 2017</a>)</span>.</p>
</div>
</div>
<div id="graphical-summaries" class="section level3 hasAnchor" number="1.6.3">
<h3><span class="header-section-number">1.6.3</span> Graphical Summaries<a href="introductory-statistics-in-r.html#graphical-summaries" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We begin a graphical summary with a matrix (or table) of univariate and bivariate plots using the <code>ggpairs()</code> function in the <code>GGally</code> package <span class="citation">(<a href="#ref-R-GGally">Schloerke et al., 2018</a>)</span>. The results can be seen in Figure <a href="introductory-statistics-in-r.html#fig:ch1-17">1.1</a>.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="introductory-statistics-in-r.html#cb51-1" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb51-2"><a href="introductory-statistics-in-r.html#cb51-2" tabindex="-1"></a><span class="fu">ggpairs</span>(uadata, <span class="at">columns=</span><span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-17"></span>
<img src="introStatModeling_files/figure-html/ch1-17-1.png" alt="Pairs plot showing the relationship between the variables `gpa.endy1`, `hs.pct`, `act` and `year`." width="70%" />
<p class="caption">
Figure 1.1: Pairs plot showing the relationship between the variables <code>gpa.endy1</code>, <code>hs.pct</code>, <code>act</code> and <code>year</code>.
</p>
</div>
<div id="coding-note" class="section level4 hasAnchor" number="1.6.3.1">
<h4><span class="header-section-number">1.6.3.1</span> Coding note<a href="introductory-statistics-in-r.html#coding-note" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Here we specify to only plot using the variables in columns 2, 3, 4 and 5 (the <code>2:5</code>). We do this because the <code>id</code> variable in <code>uadata</code> is an identifier (column 1) and unique identifies each observations – it is not a variable of statistical interest – we do not want to try and plot it.</p>
<p>Note that by default the function provides a collection of univariate and bivariate plots (Figure <a href="introductory-statistics-in-r.html#fig:ch1-17">1.1</a>).
We recap each of the plots provided (further details on each plot type is provided below).</p>
<ul>
<li>On the diagonal of the matrix we see univariate plots – density plots for the numeric variables and a bargraph of frequencies for categorical variable `year.</li>
<li>In the upper right triangle of the matrix we see numeric measures for the amount of correlation between each of the numeric variables (Pearson Correlation coefficients, typically denoted with <span class="math inline">\(r\)</span>). In the case of a numeric variable matched with a categorical variable, side-by-side boxplots are provided.</li>
<li>In the bottom left triangle of the matrix scatterplots are provided to show the relationship between numeric variables. We also see histograms for each of the numerical variable stratified by the categorical variable <code>year</code>. Now we will discuss each of the elements in more detail.</li>
</ul>
</div>
</div>
<div id="distribution-of-univariate-variables" class="section level3 hasAnchor" number="1.6.4">
<h3><span class="header-section-number">1.6.4</span> Distribution of Univariate Variables<a href="introductory-statistics-in-r.html#distribution-of-univariate-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <code>ggpairs</code> function provides a look at the distributional shape of each variable using what is known as a <em>density plot</em> (this can be consider a more-modern, and arguably less subjective, histogram). The <code>ggpairs</code> function builds off a function known as <code>ggplot()</code> from the <code>ggplot2</code> package <span class="citation">(<a href="#ref-R-ggplot2">Wickham, 2016</a>)</span> which is included in <code>tidyverse</code> <span class="citation">(<a href="#ref-R-tidyverse">Wickham, 2017</a>)</span>.</p>
<p>We can build density plots directly using the <code>geom_density()</code> function as seen in the code below. The resulting density plot is in Figure <a href="introductory-statistics-in-r.html#fig:ch1-18">1.2</a>.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="introductory-statistics-in-r.html#cb52-1" tabindex="-1"></a><span class="fu">ggplot</span>(uadata) <span class="sc">+</span> </span>
<span id="cb52-2"><a href="introductory-statistics-in-r.html#cb52-2" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>gpa.endyr1))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-18"></span>
<img src="introStatModeling_files/figure-html/ch1-18-1.png" alt="Density plot showing left-skewed distribution for the `gpa.endyr1` variable" width="60%" />
<p class="caption">
Figure 1.2: Density plot showing left-skewed distribution for the <code>gpa.endyr1</code> variable
</p>
</div>
<div id="coding-notes-1" class="section level4 hasAnchor" number="1.6.4.1">
<h4><span class="header-section-number">1.6.4.1</span> Coding Notes<a href="introductory-statistics-in-r.html#coding-notes-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Note the code is similar to the <code>|&gt;</code> operator but with a <code>+</code>.
The trick to working with plotting on the computer is to think in terms of <em>layers</em>.
The first line <code>ggplot(uadata)</code> sets up a plot object based on the dataset <code>uadata</code>.
The <code>+</code> says to add a layer, this layer is a density plot (<code>geom_density</code>) where the aesthetic values include an <span class="math inline">\(x\)</span>-axis variable matching that of <code>gpa.endyr</code>.</p>
<p>To generate even more complex distributional plots, first we need to perform some data processing.
Above we saw <code>pivot_longer()</code>.
The purpose of the <code>pivot_longer()</code> function is to collect variables in a dataset and create a <em>tall</em> (or <em>longer</em>, wide-to-long) dataset.
We specify the variables (or columns) we want to pivot (the <code>c(gpa.endyr1, hs.pct, act)</code> part in the below code), the name of the new variable (here called <code>var_names</code>) storing the column names, and the variable name that will store the values (here called <code>values</code>).</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="introductory-statistics-in-r.html#cb53-1" tabindex="-1"></a>uadata.tall <span class="ot">&lt;-</span> uadata <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="introductory-statistics-in-r.html#cb53-2" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">c</span>(gpa.endyr1, hs.pct, act), </span>
<span id="cb53-3"><a href="introductory-statistics-in-r.html#cb53-3" tabindex="-1"></a>               <span class="at">names_to=</span><span class="st">&quot;var_names&quot;</span>, <span class="at">values_to=</span><span class="st">&quot;values&quot;</span> )</span>
<span id="cb53-4"><a href="introductory-statistics-in-r.html#cb53-4" tabindex="-1"></a><span class="fu">head</span>(uadata)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   id    gpa.endyr1 hs.pct   act year 
##   &lt;fct&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;
## 1 1           0.98     61    20 1996 
## 2 2           1.13     84    20 1996 
## 3 3           1.25     74    19 1996 
## 4 4           1.32     95    23 1996 
## 5 5           1.48     77    28 1996 
## 6 6           1.57     47    23 1996</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="introductory-statistics-in-r.html#cb55-1" tabindex="-1"></a><span class="fu">head</span>(uadata.tall)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   id    year  var_names  values
##   &lt;fct&gt; &lt;fct&gt; &lt;chr&gt;       &lt;dbl&gt;
## 1 1     1996  gpa.endyr1   0.98
## 2 1     1996  hs.pct      61   
## 3 1     1996  act         20   
## 4 2     1996  gpa.endyr1   1.13
## 5 2     1996  hs.pct      84   
## 6 2     1996  act         20</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="introductory-statistics-in-r.html#cb57-1" tabindex="-1"></a><span class="fu">dim</span>(uadata)</span></code></pre></div>
<pre><code>## [1] 705   5</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="introductory-statistics-in-r.html#cb59-1" tabindex="-1"></a><span class="fu">dim</span>(uadata.tall)</span></code></pre></div>
<pre><code>## [1] 2115    4</code></pre>
<p>Take a minute and step through the above code to understand it.
The data is now in a <em>tall</em>, or <em>long</em>, format.
We can now utilize the <code>ggplot2</code> package for more advanced plotting.
Here we want to draw a density plot for the <code>values</code> in the tall, or long, version of the dataset, called <code>uadata.tall</code>.
But we want a different plot for each <code>var_names</code> <em>variable</em> (that is, <code>act</code>, <code>gpa.endyr1</code>, and <code>hs.pct</code>) so we add a <code>facet_grid()</code> layer.
Figure <a href="introductory-statistics-in-r.html#fig:ch1-20">1.3</a> provides the result for the below code.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="introductory-statistics-in-r.html#cb61-1" tabindex="-1"></a><span class="fu">ggplot</span>(uadata.tall) <span class="sc">+</span></span>
<span id="cb61-2"><a href="introductory-statistics-in-r.html#cb61-2" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>values)) <span class="sc">+</span> </span>
<span id="cb61-3"><a href="introductory-statistics-in-r.html#cb61-3" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>var_names, <span class="at">scales=</span><span class="st">&quot;free_x&quot;</span>) <span class="sc">+</span> </span>
<span id="cb61-4"><a href="introductory-statistics-in-r.html#cb61-4" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-20"></span>
<img src="introStatModeling_files/figure-html/ch1-20-1.png" alt="Side-by-side density plots showing the relative distributions of `act`, `gpa.endyr1` and `hs.pct`." width="70%" />
<p class="caption">
Figure 1.3: Side-by-side density plots showing the relative distributions of <code>act</code>, <code>gpa.endyr1</code> and <code>hs.pct</code>.
</p>
</div>
</div>
<div id="coding-notes-2" class="section level4 hasAnchor" number="1.6.4.2">
<h4><span class="header-section-number">1.6.4.2</span> Coding Notes<a href="introductory-statistics-in-r.html#coding-notes-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <code>facet_grid</code> option tells the plot to draw each density plot for each observed value in <code>var_names</code>.
The <em>facet</em> feature is similar to the <code>group_by</code> statement when calculating summary statistics.
The <code>theme_bw()</code> specifies the plotting style (there are many others but we will typically use <code>theme_bw()</code>, <code>theme_minimal()</code> or the default behavior which corresponds to <code>theme_grey()</code>).
The <code>free_x</code> option tells the plot that each <span class="math inline">\(x\)</span>-axis is on a different scale.
Feel free to modify the code to see how the plot changes!</p>
<p>We can see that GPA and high school percentile rankings are skewed left, and that ACT scores are reasonably symmetrically distributed.</p>
<p>Alternatively, we could build histograms to make the comparison.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="introductory-statistics-in-r.html#cb62-1" tabindex="-1"></a><span class="fu">ggplot</span>(uadata.tall) <span class="sc">+</span></span>
<span id="cb62-2"><a href="introductory-statistics-in-r.html#cb62-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>values), <span class="at">binwidth =</span> <span class="fl">2.5</span>) <span class="sc">+</span> </span>
<span id="cb62-3"><a href="introductory-statistics-in-r.html#cb62-3" tabindex="-1"></a>  <span class="fu">facet_grid</span>(var_names<span class="sc">~</span>., <span class="at">scales=</span><span class="st">&quot;free_y&quot;</span>) <span class="sc">+</span> </span>
<span id="cb62-4"><a href="introductory-statistics-in-r.html#cb62-4" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-20a"></span>
<img src="introStatModeling_files/figure-html/ch1-20a-1.png" alt="Stacked histogram showing the relative distributions of `act`, `gpa.endyr1` and `hs.pct`." width="60%" />
<p class="caption">
Figure 1.4: Stacked histogram showing the relative distributions of <code>act</code>, <code>gpa.endyr1</code> and <code>hs.pct</code>.
</p>
</div>
<p>Note the similarities and difference in Figures <a href="introductory-statistics-in-r.html#fig:ch1-20">1.3</a> and <a href="introductory-statistics-in-r.html#fig:ch1-20a">1.4</a>.
Depending on whether we facet on the <span class="math inline">\(y\)</span>-axis or <span class="math inline">\(x\)</span>-axis we can get different appearances.
Also note that the code for plotting a histogram is similar to that of a density plot (<code>geom_histogram</code> vs <code>geom_density</code>).</p>
<p><strong>Bar Graphs</strong></p>
<p>The best visual tool for simple counts is the Bar Graph (<strong>note:</strong> you should never use a pie chart, see <a href="http://www.businessinsider.com/pie-charts-are-the-worst-2013-6">here for an explanation</a> ).
The below code generates a simple (and fairly boring) bar graph (Figure <a href="introductory-statistics-in-r.html#fig:ch1-21">1.5</a>) displaying the number of observations for each <code>year</code> in the <code>uadata</code>.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="introductory-statistics-in-r.html#cb63-1" tabindex="-1"></a><span class="fu">ggplot</span>(uadata) <span class="sc">+</span> </span>
<span id="cb63-2"><a href="introductory-statistics-in-r.html#cb63-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x=</span>year) )</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-21"></span>
<img src="introStatModeling_files/figure-html/ch1-21-1.png" alt="Bar graph displaying the number of observations in the `uadata` per `year`." width="60%" />
<p class="caption">
Figure 1.5: Bar graph displaying the number of observations in the <code>uadata</code> per <code>year</code>.
</p>
</div>
<p>We see here that nothing too interesting is happening. A fairly uniform distribution of counts is seen across years.</p>
</div>
</div>
<div id="descriptive-statistics-and-visualizations-by-levels-of-a-factor-variable" class="section level3 hasAnchor" number="1.6.5">
<h3><span class="header-section-number">1.6.5</span> Descriptive statistics and visualizations by levels of a factor variable<a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-by-levels-of-a-factor-variable" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>While the above summaries are informative, they overlook the fact that we have several years of data and that it may be more interesting to see how things might be changing year-to-year. This is why treating <code>year</code> as a factor is important, because it enables us to split out descriptions of the numeric variables by levels of the factor.</p>
<p>One of the simplest and best visualization tool for comparing distributions is the side-by-side boxplot, which displays information about quartiles (<span class="math inline">\(Q_1\)</span>, <span class="math inline">\(Q_2\)</span> and <span class="math inline">\(Q_3\)</span>) and potential outliers. The below code generates Figure <a href="introductory-statistics-in-r.html#fig:ch1-22">1.6</a>.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="introductory-statistics-in-r.html#cb64-1" tabindex="-1"></a><span class="fu">ggplot</span>(uadata) <span class="sc">+</span></span>
<span id="cb64-2"><a href="introductory-statistics-in-r.html#cb64-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>act, <span class="at">y=</span>year) ) <span class="sc">+</span></span>
<span id="cb64-3"><a href="introductory-statistics-in-r.html#cb64-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;ACT scores of Incoming Freshmen&quot;</span>,</span>
<span id="cb64-4"><a href="introductory-statistics-in-r.html#cb64-4" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&quot;Composite ACT Score&quot;</span>,</span>
<span id="cb64-5"><a href="introductory-statistics-in-r.html#cb64-5" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;Year&quot;</span>) <span class="sc">+</span> </span>
<span id="cb64-6"><a href="introductory-statistics-in-r.html#cb64-6" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-22"></span>
<img src="introStatModeling_files/figure-html/ch1-22-1.png" alt="Side-by-side Box-whiskers plots showing the distribution of ACT scores in the `uadata` per year." width="60%" />
<p class="caption">
Figure 1.6: Side-by-side Box-whiskers plots showing the distribution of ACT scores in the <code>uadata</code> per year.
</p>
</div>
<p>The code is similar to the examples above except now we call the <code>geom_boxplot</code> function.
Also note we are using <code>theme_classic()</code> which has some subtle differences compared to <code>theme_bw()</code> used above.
Lastly, we include proper labels and titles on our plot here for a more professional appearance.</p>
<p>Next we construct side-by-side boxplots by year for each of the three numeric variables in the data frame.
We utilize the taller or longer format of the admissions data in <code>uadata.tall</code>.
Two versions of this plot are provided in Figure <a href="introductory-statistics-in-r.html#fig:ch1-23">1.7</a> and Figure <a href="introductory-statistics-in-r.html#fig:ch1-23a">1.8</a>.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="introductory-statistics-in-r.html#cb65-1" tabindex="-1"></a><span class="co"># Code for Figure 1.6</span></span>
<span id="cb65-2"><a href="introductory-statistics-in-r.html#cb65-2" tabindex="-1"></a><span class="fu">ggplot</span>(uadata.tall) <span class="sc">+</span> </span>
<span id="cb65-3"><a href="introductory-statistics-in-r.html#cb65-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>values, <span class="at">y=</span>year) ) <span class="sc">+</span></span>
<span id="cb65-4"><a href="introductory-statistics-in-r.html#cb65-4" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>var_names, <span class="at">scales=</span><span class="st">&quot;free_x&quot;</span>) <span class="sc">+</span> </span>
<span id="cb65-5"><a href="introductory-statistics-in-r.html#cb65-5" tabindex="-1"></a>  <span class="fu">theme_dark</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-23"></span>
<img src="introStatModeling_files/figure-html/ch1-23-1.png" alt="Side-by-side Box-whiskers plots showing the distributions of the variables `act`, `gpa.endyr1` and `hs.pct` for each year in the `uadata` dataset." width="70%" />
<p class="caption">
Figure 1.7: Side-by-side Box-whiskers plots showing the distributions of the variables <code>act</code>, <code>gpa.endyr1</code> and <code>hs.pct</code> for each year in the <code>uadata</code> dataset.
</p>
</div>
<p>Note another theme option, <code>theme_dark()</code> (obviously you will NOT want to use this theme if planning to print the document).
A more aesthetically pleasing version of the plot (with proper labeling) is generated with the code below and can be seen in Figure <a href="introductory-statistics-in-r.html#fig:ch1-23a">1.8</a>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="introductory-statistics-in-r.html#cb66-1" tabindex="-1"></a><span class="co"># Code for Figure 1.7</span></span>
<span id="cb66-2"><a href="introductory-statistics-in-r.html#cb66-2" tabindex="-1"></a><span class="fu">ggplot</span>(uadata.tall) <span class="sc">+</span> </span>
<span id="cb66-3"><a href="introductory-statistics-in-r.html#cb66-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>values, <span class="at">y=</span>year) ) <span class="sc">+</span></span>
<span id="cb66-4"><a href="introductory-statistics-in-r.html#cb66-4" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span>var_names, <span class="at">scales=</span><span class="st">&quot;free_x&quot;</span>) <span class="sc">+</span> </span>
<span id="cb66-5"><a href="introductory-statistics-in-r.html#cb66-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span><span class="st">&quot;Year&quot;</span>, <span class="at">x=</span><span class="st">&quot;&quot;</span>, <span class="at">title=</span><span class="st">&quot;Distribution of ACT, GPA and HS Rank by Year&quot;</span>) <span class="sc">+</span></span>
<span id="cb66-6"><a href="introductory-statistics-in-r.html#cb66-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-23a"></span>
<img src="introStatModeling_files/figure-html/ch1-23a-1.png" alt="Side-by-side Box-whiskers plots showing the distributions of the variables `act`, `gpa.endyr1` and `hs.pct` for each year in the `uadata` dataset." width="70%" />
<p class="caption">
Figure 1.8: Side-by-side Box-whiskers plots showing the distributions of the variables <code>act</code>, <code>gpa.endyr1</code> and <code>hs.pct</code> for each year in the <code>uadata</code> dataset.
</p>
</div>
<p>This is a nice compact visual description of the changes in patterns of response of these three variables over time.<br />
All three variables appear pretty stable over the years; the left skews in GPA and high school percentile rankings are still evident here (note the detection of some low outliers on these two variables).</p>
<p>We now revisit calculating summary statistics.
Extensive grouped numeric summary statistics are available by using the <code>group_by()</code> and <code>summarize()</code> functions in <code>tidyverse</code>.
Recall that the <code>group_by</code> function tells R to treat each value of the specified variable (in this case, called <code>var_names</code>) as a collection of similar options, then to perform the <code>summarize</code> function on each value in the grouped variables.
The below example is a more detailed version of the summary table from above.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="introductory-statistics-in-r.html#cb67-1" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb67-2"><a href="introductory-statistics-in-r.html#cb67-2" tabindex="-1"></a></span>
<span id="cb67-3"><a href="introductory-statistics-in-r.html#cb67-3" tabindex="-1"></a>summary.table <span class="ot">&lt;-</span> uadata.tall <span class="sc">|&gt;</span></span>
<span id="cb67-4"><a href="introductory-statistics-in-r.html#cb67-4" tabindex="-1"></a>  <span class="fu">group_by</span>(var_names) <span class="sc">|&gt;</span></span>
<span id="cb67-5"><a href="introductory-statistics-in-r.html#cb67-5" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Mean=</span><span class="fu">mean</span>(values),</span>
<span id="cb67-6"><a href="introductory-statistics-in-r.html#cb67-6" tabindex="-1"></a>            <span class="at">StDev=</span><span class="fu">sd</span>(values),</span>
<span id="cb67-7"><a href="introductory-statistics-in-r.html#cb67-7" tabindex="-1"></a>            <span class="at">Min=</span><span class="fu">min</span>(values),</span>
<span id="cb67-8"><a href="introductory-statistics-in-r.html#cb67-8" tabindex="-1"></a>            <span class="at">Q2=</span><span class="fu">quantile</span>(values, <span class="at">prob=</span><span class="fl">0.25</span>),</span>
<span id="cb67-9"><a href="introductory-statistics-in-r.html#cb67-9" tabindex="-1"></a>            <span class="at">Median=</span><span class="fu">median</span>(values),</span>
<span id="cb67-10"><a href="introductory-statistics-in-r.html#cb67-10" tabindex="-1"></a>            <span class="at">Q3=</span><span class="fu">quantile</span>(values, <span class="at">prob=</span><span class="fl">0.75</span>),</span>
<span id="cb67-11"><a href="introductory-statistics-in-r.html#cb67-11" tabindex="-1"></a>            <span class="at">Max=</span><span class="fu">max</span>(values) )</span>
<span id="cb67-12"><a href="introductory-statistics-in-r.html#cb67-12" tabindex="-1"></a></span>
<span id="cb67-13"><a href="introductory-statistics-in-r.html#cb67-13" tabindex="-1"></a><span class="fu">kable</span>(summary.table, <span class="at">digits=</span><span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb67-14"><a href="introductory-statistics-in-r.html#cb67-14" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
var_names
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
StDev
</th>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Q2
</th>
<th style="text-align:right;">
Median
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
Max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
act
</td>
<td style="text-align:right;">
24.543
</td>
<td style="text-align:right;">
4.014
</td>
<td style="text-align:right;">
13.00
</td>
<td style="text-align:right;">
22.000
</td>
<td style="text-align:right;">
25.00
</td>
<td style="text-align:right;">
28.00
</td>
<td style="text-align:right;">
35
</td>
</tr>
<tr>
<td style="text-align:left;">
gpa.endyr1
</td>
<td style="text-align:right;">
2.977
</td>
<td style="text-align:right;">
0.635
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
2.609
</td>
<td style="text-align:right;">
3.05
</td>
<td style="text-align:right;">
3.47
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
hs.pct
</td>
<td style="text-align:right;">
76.953
</td>
<td style="text-align:right;">
18.634
</td>
<td style="text-align:right;">
4.00
</td>
<td style="text-align:right;">
68.000
</td>
<td style="text-align:right;">
81.00
</td>
<td style="text-align:right;">
92.00
</td>
<td style="text-align:right;">
99
</td>
</tr>
</tbody>
</table>
<p>Here, we first pipe the <code>uadata.tall</code> into a <code>group_by()</code> function grouping by the <code>var_names</code> variable.
Then we take that output and pipe it to the <code>summarize</code> function which allows us to calculate various summary statistics for each of the groups.
In the above we calculate the mean and standard deviation of each group, along with the 5-number summary.
Lastly, we wrap the constructed table (its technically a data frame) in the <code>kable()</code> function from the <code>knitr</code> package <span class="citation">(<a href="#ref-R-knitr">Xie, 2025</a>)</span> (where <code>kable</code> means ‘knitr’ ‘table’) for a nice display.
We pipe that output to the <code>kable_styling()</code> function in the <code>kableExtra</code> package <span class="citation">(<a href="#ref-R-kableExtra">Zhu, 2024</a>)</span> for some additional formatting options (here, we condence the width of the table).</p>
<p>In the next example we group by both the <code>year</code> and the variables of interest.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="introductory-statistics-in-r.html#cb68-1" tabindex="-1"></a>summary.table2 <span class="ot">&lt;-</span> uadata.tall <span class="sc">|&gt;</span></span>
<span id="cb68-2"><a href="introductory-statistics-in-r.html#cb68-2" tabindex="-1"></a>  <span class="fu">group_by</span>(var_names, year) <span class="sc">|&gt;</span></span>
<span id="cb68-3"><a href="introductory-statistics-in-r.html#cb68-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Mean=</span><span class="fu">mean</span>(values),</span>
<span id="cb68-4"><a href="introductory-statistics-in-r.html#cb68-4" tabindex="-1"></a>            <span class="at">StDev=</span><span class="fu">sd</span>(values))</span>
<span id="cb68-5"><a href="introductory-statistics-in-r.html#cb68-5" tabindex="-1"></a><span class="fu">kable</span>(summary.table2, <span class="at">digits=</span><span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb68-6"><a href="introductory-statistics-in-r.html#cb68-6" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
var_names
</th>
<th style="text-align:left;">
year
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
StDev
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
act
</td>
<td style="text-align:left;">
1996
</td>
<td style="text-align:right;">
24.690
</td>
<td style="text-align:right;">
3.885
</td>
</tr>
<tr>
<td style="text-align:left;">
act
</td>
<td style="text-align:left;">
1997
</td>
<td style="text-align:right;">
24.099
</td>
<td style="text-align:right;">
3.819
</td>
</tr>
<tr>
<td style="text-align:left;">
act
</td>
<td style="text-align:left;">
1998
</td>
<td style="text-align:right;">
24.506
</td>
<td style="text-align:right;">
4.277
</td>
</tr>
<tr>
<td style="text-align:left;">
act
</td>
<td style="text-align:left;">
1999
</td>
<td style="text-align:right;">
24.837
</td>
<td style="text-align:right;">
4.396
</td>
</tr>
<tr>
<td style="text-align:left;">
act
</td>
<td style="text-align:left;">
2000
</td>
<td style="text-align:right;">
24.555
</td>
<td style="text-align:right;">
3.609
</td>
</tr>
<tr>
<td style="text-align:left;">
gpa.endyr1
</td>
<td style="text-align:left;">
1996
</td>
<td style="text-align:right;">
2.929
</td>
<td style="text-align:right;">
0.653
</td>
</tr>
<tr>
<td style="text-align:left;">
gpa.endyr1
</td>
<td style="text-align:left;">
1997
</td>
<td style="text-align:right;">
2.974
</td>
<td style="text-align:right;">
0.634
</td>
</tr>
<tr>
<td style="text-align:left;">
gpa.endyr1
</td>
<td style="text-align:left;">
1998
</td>
<td style="text-align:right;">
3.000
</td>
<td style="text-align:right;">
0.654
</td>
</tr>
<tr>
<td style="text-align:left;">
gpa.endyr1
</td>
<td style="text-align:left;">
1999
</td>
<td style="text-align:right;">
3.026
</td>
<td style="text-align:right;">
0.601
</td>
</tr>
<tr>
<td style="text-align:left;">
gpa.endyr1
</td>
<td style="text-align:left;">
2000
</td>
<td style="text-align:right;">
2.955
</td>
<td style="text-align:right;">
0.632
</td>
</tr>
<tr>
<td style="text-align:left;">
hs.pct
</td>
<td style="text-align:left;">
1996
</td>
<td style="text-align:right;">
78.296
</td>
<td style="text-align:right;">
15.894
</td>
</tr>
<tr>
<td style="text-align:left;">
hs.pct
</td>
<td style="text-align:left;">
1997
</td>
<td style="text-align:right;">
76.641
</td>
<td style="text-align:right;">
20.197
</td>
</tr>
<tr>
<td style="text-align:left;">
hs.pct
</td>
<td style="text-align:left;">
1998
</td>
<td style="text-align:right;">
74.649
</td>
<td style="text-align:right;">
19.983
</td>
</tr>
<tr>
<td style="text-align:left;">
hs.pct
</td>
<td style="text-align:left;">
1999
</td>
<td style="text-align:right;">
79.454
</td>
<td style="text-align:right;">
17.045
</td>
</tr>
<tr>
<td style="text-align:left;">
hs.pct
</td>
<td style="text-align:left;">
2000
</td>
<td style="text-align:right;">
75.876
</td>
<td style="text-align:right;">
19.535
</td>
</tr>
</tbody>
</table>
</div>
<div id="descriptive-statistics-and-visualizations-for-two-numeric-variables" class="section level3 hasAnchor" number="1.6.6">
<h3><span class="header-section-number">1.6.6</span> Descriptive statistics and visualizations for two numeric variables<a href="introductory-statistics-in-r.html#descriptive-statistics-and-visualizations-for-two-numeric-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a pair of numeric variables the amount of linear association between the variables can be measured with the Pearson correlation.
The Pearson correlation assesses the <em>strength</em> and <em>direction</em> of any linear relationship existing between two numeric variables.
The correlation coefficients between the GPA, ACT and HS rank variables are provided Figure <a href="introductory-statistics-in-r.html#fig:ch1-17">1.1</a>.</p>
<p>Recall from introductory statistics that the Pearson correlation <span class="math inline">\(r\)</span> between two variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is given by the formula
<span class="math display">\[r = \frac{1}{n-1}\sum_{i=1}^n\left(\frac{x_i - \bar{x}}{s_x}\right)\left(\frac{y_i - \bar{y}}{s_y}\right).\]</span>
<span class="math inline">\(r\)</span> is a unitless measure with the property that <span class="math inline">\(-1 \leq r \leq 1\)</span>.<br />
Values of <span class="math inline">\(r\)</span> near <span class="math inline">\(\pm 1\)</span> indicate a near perfect (positive or negative) linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.
A frequently used rule of thumb is that <span class="math inline">\(|r| &gt; 0.80\)</span> or so qualifies as a strong linear relationship.
We can calculate the Pearson correlation with the <code>cor()</code> function in R.
When applied to a <code>data.frame</code>, or <code>matrix</code>, it displays a correlation matrix (correlation of all variable pairs).
In the below code we specify to only calculate the correlation based on the 3 numeric variables.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="introductory-statistics-in-r.html#cb69-1" tabindex="-1"></a><span class="fu">cor</span>(uadata <span class="sc">|&gt;</span> <span class="fu">select</span>(gpa.endyr1, hs.pct, act))</span></code></pre></div>
<pre><code>##            gpa.endyr1   hs.pct      act
## gpa.endyr1   1.000000 0.398479 0.365611
## hs.pct       0.398479 1.000000 0.442507
## act          0.365611 0.442507 1.000000</code></pre>
<p>All pairwise correlations in this example are of modest magnitude (<span class="math inline">\(r \approx 0.4\)</span>) (see Figure <a href="introductory-statistics-in-r.html#fig:ch1-17">1.1</a> or the above correlation matrix).</p>
<p>To visualize the relationship between numeric variables, we typically use a scatterplot.
A scatterplot is a simple bivariate plot where dots, or points, are plotted at each (<span class="math inline">\(x,y\)</span>) pair on the Cartesian plane.
The code below uses <code>ggplot</code>() to build a scatterplot using <code>geom_point()</code>.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="introductory-statistics-in-r.html#cb71-1" tabindex="-1"></a><span class="fu">ggplot</span>(uadata) <span class="sc">+</span> </span>
<span id="cb71-2"><a href="introductory-statistics-in-r.html#cb71-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>act, <span class="at">y=</span>gpa.endyr1) ) <span class="sc">+</span></span>
<span id="cb71-3"><a href="introductory-statistics-in-r.html#cb71-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Composite ACT Score&quot;</span>,</span>
<span id="cb71-4"><a href="introductory-statistics-in-r.html#cb71-4" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;Grade point average following freshman year&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-5"><a href="introductory-statistics-in-r.html#cb71-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-25-scatter"></span>
<img src="introStatModeling_files/figure-html/ch1-25-scatter-1.png" alt="Scatterplot showing the relationship between the variables `act` and `gpa.endyr1` in the `uadata` dataset." width="60%" />
<p class="caption">
Figure 1.9: Scatterplot showing the relationship between the variables <code>act</code> and <code>gpa.endyr1</code> in the <code>uadata</code> dataset.
</p>
</div>
<p>You should note in Figure <a href="introductory-statistics-in-r.html#fig:ch1-25-scatter">1.9</a> the overall positive relationship (higher ACT scores tend to correspond to higher GPAs and corresponds to the Pearson correlation value of <span class="math inline">\(0.366\)</span>).
We also note that due to the rounding of the ACT scores (always a whole number) the resulting plot has vertical striations.</p>
<p>We attempt to visually address the striations with <em>jittering</em> (adding some visual random perturbations) in Figure <a href="introductory-statistics-in-r.html#fig:ch1-25-jitter">1.10</a> with the code below using <code>geom_jitter()</code>.
There, we specify no jittering on the vertical axis (thus, <code>height=0</code>) and let <code>ggplot2</code> use the default behavior horizontally.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="introductory-statistics-in-r.html#cb72-1" tabindex="-1"></a><span class="fu">ggplot</span>(uadata) <span class="sc">+</span> </span>
<span id="cb72-2"><a href="introductory-statistics-in-r.html#cb72-2" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="fu">aes</span>(<span class="at">x=</span>act, <span class="at">y=</span>gpa.endyr1), <span class="at">height=</span><span class="dv">0</span> ) <span class="sc">+</span></span>
<span id="cb72-3"><a href="introductory-statistics-in-r.html#cb72-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Composite ACT Score&quot;</span>,</span>
<span id="cb72-4"><a href="introductory-statistics-in-r.html#cb72-4" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;Grade point average following freshman year&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-5"><a href="introductory-statistics-in-r.html#cb72-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-25-jitter"></span>
<img src="introStatModeling_files/figure-html/ch1-25-jitter-1.png" alt="Jittered scatterplot showing the relationship between the variables `act` and `gpa.endyr1` in the `uadata` dataset." width="60%" />
<p class="caption">
Figure 1.10: Jittered scatterplot showing the relationship between the variables <code>act</code> and <code>gpa.endyr1</code> in the <code>uadata</code> dataset.
</p>
</div>
<p>Note, with jittering we are only adding <em>randomness</em> to the <strong>plot</strong>, we are not changing the recorded values in the <code>data.frame</code>.</p>
</div>
</div>
<div id="sampling-distributions-describing-how-a-statistic-varies" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Sampling distributions: describing how a statistic varies<a href="introductory-statistics-in-r.html#sampling-distributions-describing-how-a-statistic-varies" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As described in the discussion on variability above, each of the numeric quantities calculated has some associated uncertainty.
It is not enough to simply know the variance or standard deviation of an estimate.
That only provides one measure of the inconsistency in an estimate’s value from sample to sample of a given size <span class="math inline">\(n\)</span>.</p>
<p>If we wish to make a confident conclusion about an unknown population parameter using a sample statistic (<em>e.g.</em>, <span class="math inline">\(\bar{x}\)</span>), we also need to know something about the general pattern of behavior that statistic will take if we had observed it over many, many different random samples.
This long-run behavior pattern is described via the probability distribution of the statistic, which is known as the <strong>sampling distribution</strong> of the statistic.</p>
<p>It is important to remember that we usually only collect one sample, so only one sample estimate will be available in practice.
However, knowledge of the sampling distribution of our statistic or estimate is important because it will enable us to assess the reliability or confidence we can place in any generalizations we make about the population using our estimate.</p>
<p><strong>Two useful sampling distributions:</strong> Normal and <span class="math inline">\(t\)</span></p>
<p>You should be very familiar with Normal distributions and <span class="math inline">\(t\)</span>-distributions from your introductory statistics course.
In particular, both serve as useful sampling distributions to describe the behavior of the sample mean <span class="math inline">\(\bar{x}\)</span> as an estimator for a population mean <span class="math inline">\(\mu\)</span>. We briefly review them here.</p>
<p><strong>Normal distributions.</strong></p>
<p>A random variable <span class="math inline">\(X\)</span> that is normally distributed is one that has a symmetric bell-shaped density curve.
A normal density curve has two parameters: its mean <span class="math inline">\(\mu\)</span> and its variance <span class="math inline">\(\sigma^2\)</span>.
Notationally, we indicate that a random variable <span class="math inline">\(X\)</span> is normal by writing <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span>.</p>
<p>The normal distribution serves as a good sampling distribution model for the sample mean <span class="math inline">\(\bar{x}\)</span> because of the powerful Central Limit Theorem, which states that if <span class="math inline">\(n\)</span> is sufficiently large, the sampling distribution of <span class="math inline">\(\bar{x}\)</span> will be approximately normal, regardless of the shape of the distribution of the original parent population from which you collect your sample (when making a few assumptions).</p>
<p><strong>t distributions.</strong></p>
<p>The formula given by
<span class="math display">\[t_0 = \frac{\bar{x}-\mu}{{SE}_{\bar{x}}}\]</span>
counts the number of standard error units between the true value of <span class="math inline">\(\mu\)</span> and its sample estimate <span class="math inline">\(\bar{x}\)</span>; it can be thought of as the standardized distance between a sample mean estimate and the true mean value.
If the original population was normally distributed, then the quantity <span class="math inline">\(t_0\)</span> will follow the Students’ <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n - 1\)</span> degrees of freedom.
The <em>degrees of freedom</em> is the only parameter of a <span class="math inline">\(t\)</span>-distribution.<br />
Notationally, we indicate this by writing <span class="math inline">\(t_0 \sim t(\textrm{df})\)</span> or <span class="math inline">\(t_0 \sim t(\nu)\)</span> where <span class="math inline">\(\nu\)</span> is a lowercase Greek ‘nu’ (pronounced ‘new’) and is the notation for degrees of freedom.</p>
<p><span class="math inline">\(t\)</span>-distributions look like the standard normal distribution, <span class="math inline">\(N(0, 1)\)</span>: they are both centered at 0, are symmetric and bell-shaped (see below).
The key difference is due to the fact that the quantity <span class="math inline">\(t\)</span> includes two <strong>sample summaries</strong> in its construction: the sample mean <span class="math inline">\(\bar{x}\)</span>, and <span class="math inline">\(SE_{\bar{x}}\)</span>, which incorporates the sample standard deviation <span class="math inline">\(s\)</span>.
Because of this, <span class="math inline">\(t\)</span> is more variable than <span class="math inline">\(N(0, 1)\)</span> (more room for noise).
However, as <span class="math inline">\(n\)</span> (and hence degrees of freedom) increases, <span class="math inline">\(s\)</span> becomes a better estimate of the true population standard deviation, so the distinction ultimately vanishes with larger samples.
This can all be visualized in Figure <a href="introductory-statistics-in-r.html#fig:ch1-26">1.11</a> where the degress of freedom increase from 2 to 10 and you see the <span class="math inline">\(t\)</span>-distribution approaches the Normal bell curve.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ch1-26"></span>
<img src="introStatModeling_files/figure-html/ch1-26-1.png" alt="Overlayed distribution functions showing the relationship between a standard normal distribution and that of a $t$ distribution with 3, 5 and 10 degrees of freedom. As the degrees of freedom increases, the $t$ distribution becomes more *normal*" width="75%" />
<p class="caption">
Figure 1.11: Overlayed distribution functions showing the relationship between a standard normal distribution and that of a <span class="math inline">\(t\)</span> distribution with 3, 5 and 10 degrees of freedom. As the degrees of freedom increases, the <span class="math inline">\(t\)</span> distribution becomes more <em>normal</em>
</p>
</div>
<p>The <span class="math inline">\(t\)</span>-distribution is usually the relevant sampling distribution when we use a sample mean <span class="math inline">\(\bar{x}\)</span> to make inferences about the corresponding population mean <span class="math inline">\(\mu\)</span>.
Later in the course, the need to make more complicated inferences will require us to develop different sampling distribution models to facilitate the statistics involved. These will be presented as needed.</p>
</div>
<div id="twoSampleInference" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> Two-sample inference<a href="introductory-statistics-in-r.html#twoSampleInference" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A key concept from your introductory statistics course that builds off sampling distribution theory is the comparison of the mean from two populations based on the sample means using a “two-sample <span class="math inline">\(t\)</span>-test”.
Consider testing
<span class="math display">\[H_0:\ \mu_A = \mu_B ~~~\textrm{versus}~~~ H_A:\ \mu_A &lt;\neq&gt; \mu_B\]</span>
where the notation <span class="math inline">\(&lt;\neq&gt;\)</span> represents one of the common alternative hypotheses from your introductory statistics course (less than <span class="math inline">\(&lt;\)</span>, not equal to <span class="math inline">\(\neq\)</span>, or greater than <span class="math inline">\(&gt;\)</span>) and, <span class="math inline">\(\mu_A\)</span> is the population mean from population <span class="math inline">\(A\)</span> and <span class="math inline">\(\mu_B\)</span> is the population mean from population <span class="math inline">\(B\)</span>.
We statistically test this hypothesis via
<span class="math display">\[t_0 = \frac{\bar{x}_A - \bar{x}_B}{{SE}_{\bar{x}_A-\bar{x}_B}}\]</span>
where <span class="math inline">\({SE}_{\bar{x}_A-\bar{x}_B}\)</span> is the standard error of the difference of sample means <span class="math inline">\(\bar{x}_A\)</span> and <span class="math inline">\(\bar{x}_B\)</span>.
It can be estimated in one of two ways (depending if we assume the population variances are equal or not) and we reference your intro stat class for details (you may recall, pooled versus non-pooled variance).
In R, we can perform this test, and construct the associated <span class="math inline">\((1-\alpha)100\%\)</span> confidence interval for <span class="math inline">\(\mu_A-\mu_B\)</span>,
<span class="math display">\[\bar{x}_A - \bar{x}_B \pm t_{\alpha/2} {SE}_{\bar{x}_A-\bar{x}_B}\]</span>
using the function <code>t.test()</code>.
Here <span class="math inline">\(t_{\alpha/2}\)</span> is the <span class="math inline">\(1-\alpha/2\)</span> quantile from the <span class="math inline">\(t\)</span>-distribution (the degrees of freedom depend on your assumption about equal variance).</p>
<p>Before jumping to an example, take a moment to look at the above null and alternative hypotheses.
The null hypothesis states <span class="math inline">\(\mu_A=\mu_B\)</span>, which effectively says there is no difference in the mean between the two groups.
That is, whether the data came from group A or group B it does not provide any explanation about the variability in the data.
However, the alternative says that there is a difference and that knowing the group from which the data came helps explain some of the observed variability.</p>
<p>Now for an example, consider comparing the ACT scores for incoming freshmen in 1996 to 2000 using the university admission data. Perhaps we have a theory that ACT scores were higher in 1996 than 2000.
That is, we formally wish to test <span class="math display">\[H_0:\ \mu_{1996} = \mu_{2000} ~~~\textrm{versus}~~~ \mu_{1996} &gt; \mu_{2000}\]</span></p>
<p>First we need to select a subset of the data corresponding to those two years.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="introductory-statistics-in-r.html#cb73-1" tabindex="-1"></a>uadata.trim <span class="ot">&lt;-</span> uadata <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="introductory-statistics-in-r.html#cb73-2" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1996</span>, <span class="dv">2000</span>) )</span></code></pre></div>
<p>Here we <code>filter()</code> the <code>uadata</code> so that only years in the vector <code>c(1996, 2000)</code> are included. Now that we have a proper subset of the data, we can compare the ACT scores between the two years and build a 98% confidence interval for the mean difference.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="introductory-statistics-in-r.html#cb74-1" tabindex="-1"></a><span class="fu">t.test</span>(act <span class="sc">~</span> year, <span class="at">data=</span>uadata.trim, <span class="at">conf.level=</span><span class="fl">0.98</span>, </span>
<span id="cb74-2"><a href="introductory-statistics-in-r.html#cb74-2" tabindex="-1"></a>       <span class="at">alternative=</span><span class="st">&quot;greater&quot;</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  act by year
## t = 0.3013, df = 277, p-value = 0.382
## alternative hypothesis: true difference in means between group 1996 and group 2000 is greater than 0
## 98 percent confidence interval:
##  -0.791858       Inf
## sample estimates:
## mean in group 1996 mean in group 2000 
##            24.6901            24.5547</code></pre>
<p>We are 98% confident that the mean difference between 1996 ACT scores and 2000 ACT scores is in the interval (-0.792, <span class="math inline">\(\infty\)</span>).
Further, we lack significant evidence (<span class="math inline">\(p\)</span>-value <span class="math inline">\(\approx 0.3817\)</span>) to conclude that the average ACT score in 1996 is greater than that in 2000 for incoming freshmen (also note that the value 0 is included in the confidence interval).</p>
<div id="coding-notes-3" class="section level4 hasAnchor" number="1.8.0.1">
<h4><span class="header-section-number">1.8.0.1</span> Coding Notes<a href="introductory-statistics-in-r.html#coding-notes-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A few things about the code above.</p>
<ul>
<li>We use the notation <code>act ~ year</code>, this tells R that the <code>act</code> scores are a function of <code>year</code>. This is known as a <code>formula</code> and will be important throughout the course.</li>
<li>We specify the data set to be used to perform the test (<code>data=uadata.trim</code>).</li>
<li>We specify the confidence level (by default it is 0.95) with <code>conf.level=0.98</code> and the alternative hypothesis (by default it is a not-equal test) with <code>alternative=greater</code>.</li>
<li>Lastly, we set <code>var.equal=TRUE</code> so the standard error (and degrees of freedom) are calculated under the assumption that the variance of the two populations is equal (pooled variance).</li>
</ul>

</div>
</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-Faraway2004linear" class="csl-entry">
Faraway, J. J., <em>Linear Models with r</em>, Taylor &amp; Francis, from <a href="https://books.google.com/books?id=fvenzpofkagC">https://books.google.com/books?id=fvenzpofkagC</a>, 2004.
</div>
<div id="ref-KutnerText" class="csl-entry">
Kutner, M. H., Nachtsheim, C., Neter, J. and Li, W., <em>Applied Linear Statistical Models</em>, New York, NY: McGraw-Hill Irwin, 2004.
</div>
<div id="ref-R-base" class="csl-entry">
R Core Team, <em>R: A Language and Environment for Statistical Computing</em>, Vienna, Austria: R Foundation for Statistical Computing, from <a href="https://www.R-project.org/">https://www.R-project.org/</a>, 2019.
</div>
<div id="ref-R-GGally" class="csl-entry">
Schloerke, B., Crowley, J., Cook, D., Briatte, F., Marbach, M., Thoen, E., Elberg, A. and Larmarange, J., <em>GGally: Extension to ’Ggplot2’</em>, from <a href="https://CRAN.R-project.org/package=GGally">https://CRAN.R-project.org/package=GGally</a>, 2018.
</div>
<div id="ref-R-ggplot2" class="csl-entry">
Wickham, H., <em>Ggplot2: Elegant Graphics for Data Analysis</em>, Springer-Verlag New York, from <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>, 2016.
</div>
<div id="ref-R-tidyr" class="csl-entry">
Wickham, H., <em>Tidyr: Tidy Messy Data</em>, from <a href="https://CRAN.R-project.org/package=tidyr">https://CRAN.R-project.org/package=tidyr</a>, 2021.
</div>
<div id="ref-R-tidyverse" class="csl-entry">
Wickham, H., <em>Tidyverse: Easily Install and Load the ’Tidyverse’</em>, from <a href="https://CRAN.R-project.org/package=tidyverse">https://CRAN.R-project.org/package=tidyverse</a>, 2017.
</div>
<div id="ref-R-dplyr" class="csl-entry">
Wickham, H., François, R., Henry, L. and Müller, K., <em>Dplyr: A Grammar of Data Manipulation</em>, from <a href="https://CRAN.R-project.org/package=dplyr">https://CRAN.R-project.org/package=dplyr</a>, 2021.
</div>
<div id="ref-Wickham2017R" class="csl-entry">
Wickham, H. and Grolemund, G., <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>, O’Reilly Media, from <a href="http://r4ds.had.co.nz/">http://r4ds.had.co.nz/</a>, 2017.
</div>
<div id="ref-R-readr" class="csl-entry">
Wickham, H. and Hester, J., <em>Readr: Read Rectangular Text Data</em>, from <a href="https://CRAN.R-project.org/package=readr">https://CRAN.R-project.org/package=readr</a>, 2021.
</div>
<div id="ref-R-knitr" class="csl-entry">
Xie, Y., <em>Knitr: A General-Purpose Package for Dynamic Report Generation in <span>R</span></em>, from <a href="https://yihui.org/knitr/">https://yihui.org/knitr/</a>, 2025.
</div>
<div id="ref-R-kableExtra" class="csl-entry">
Zhu, H., <em>kableExtra: Construct Complex Table with ’Kable’ and Pipe Syntax</em>, from <a href="https://CRAN.R-project.org/package=kableExtra">https://CRAN.R-project.org/package=kableExtra</a>, 2024.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="important-preliminary-review.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="statistical-modeling-and-designed-experiments.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["introStatModeling.pdf", "introStatModeling.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
